<#
.SYNOPSIS
  Pure, network-free, secret-free helper functions for the Ω3-CHECKOUT Phase 0
  Flutterwave evidence collector. Dot-sourced by both
  Invoke-FlutterwaveEvidenceCapture.ps1 (the real, network-calling tool) and
  tests/FlutterwaveEvidenceLib.Tests.ps1 (the focused test suite).

  Nothing in this file makes a network call, reads a secret, or writes a file.
  That separation is what makes every function here directly unit-testable
  with synthetic inputs, with no mocking of HTTP or credentials required.

  Hardened, this revision (Blockers 1/2, Highs 1/2 from Codex's collector
  re-audit):
    - REMOVED: ConvertTo-RedactedObject (a denylist that retained every
      unrecognized field by default -- structurally unable to keep pace with
      undocumented provider fields, and confirmed to miss Flutterwave's real
      `first_6digits`/`last_4digits` field names, which the denylist spelled
      differently). No function in this file, and no code path in the real
      collector, ever again returns "the whole response, minus some keys."
    - ADDED: Get-AllowlistedEvidenceFields -- a strict ALLOWLIST projector.
      It walks a parsed response and returns ONLY fields whose key name is
      exactly 'status'/'amount'/'currency', or looks like a timestamp field
      by name, with the source's full JSON path preserved. Everything else --
      named or not, known or not -- is discarded by construction, not by
      exclusion.
    - ADDED: session-binding primitives (capture session id is generated by
      the caller and threaded through every stage; this library only
      validates/hashes, it does not generate the session id itself since
      that must happen exactly once, at CreateCheckout, in the real script).
    - ADDED: Test-TimelineOrdering -- validates the full six-timestamp
      ordering constraint and the Test-B 600-second minimum, rejecting any
      malformed, non-UTC, or impossible timeline.
    - HARDENED: Test-IsTestModeKey now validates the documented Flutterwave
      TEST secret-key format (FLWSECK_TEST-<32 hex>-X), case-sensitive, fail-
      closed -- no longer a bare substring check.
#>

Set-StrictMode -Version Latest

function Get-UtcTimestamp {
    [OutputType([string])]
    param()
    return [DateTime]::UtcNow.ToString('o')
}

function Test-IsValidUtcTimestamp {
    <#
    Strictly validates that $Value is a parseable, round-trippable ISO-8601
    timestamp whose Kind is Utc. Used to reject malformed or non-UTC
    timestamps pulled from a stage file on disk (defense-in-depth: every
    timestamp in this tool is machine-generated via Get-UtcTimestamp, but a
    hand-edited or corrupted stage file must still be caught here, not
    silently trusted).
    #>
    [OutputType([bool])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowNull()]
        [AllowEmptyString()]
        [string]$Value
    )
    if ([string]::IsNullOrWhiteSpace($Value)) { return $false }
    try {
        $parsed = [DateTime]::Parse($Value, [System.Globalization.CultureInfo]::InvariantCulture, [System.Globalization.DateTimeStyles]::RoundtripKind)
    }
    catch {
        return $false
    }
    return ($parsed.Kind -eq [System.DateTimeKind]::Utc)
}

function Get-Sha256Hex {
    [OutputType([string])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowEmptyString()]
        [string]$Text
    )
    $sha256 = [System.Security.Cryptography.SHA256]::Create()
    try {
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($Text)
        $hashBytes = $sha256.ComputeHash($bytes)
        return ([System.BitConverter]::ToString($hashBytes)).Replace('-', '').ToLowerInvariant()
    }
    finally {
        $sha256.Dispose()
    }
}

function Get-Sha256HexFromBytes {
    <#
    BYTE-AUTHORITY RULE (Codex provenance-closure re-audit, Blocker 1): the
    persisted bytes, hashed bytes, and parsed bytes must be the SAME byte
    sequence. This function hashes a raw byte array directly -- it never
    goes through a string encode/decode step, and it is called on the
    EXACT SAME `[byte[]]` that gets persisted to the raw evidence file and
    later decoded for JSON parsing. `Get-Sha256Hex` (string-based) remains
    for non-provenance uses (hashing a tx_ref/transaction-id value); this
    function exists specifically so a provider RESPONSE is never hashed by
    way of a re-serialized/reconstructed representation.
    #>
    [OutputType([string])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowNull()]
        [byte[]]$Bytes
    )
    if ($null -eq $Bytes) { $Bytes = [byte[]]@() }
    $sha256 = [System.Security.Cryptography.SHA256]::Create()
    try {
        $hashBytes = $sha256.ComputeHash($Bytes)
        return ([System.BitConverter]::ToString($hashBytes)).Replace('-', '').ToLowerInvariant()
    }
    finally {
        $sha256.Dispose()
    }
}

function Test-IsValidHttpStatusCode {
    <#
    CORRECTED (Codex FINAL LIVE HTTP BYTE-BOUNDARY audit): a genuine HTTP
    response always carries a status code in the real HTTP range [100,599].
    The prior real-adapter implementation used the INVENTED value 0 to mean
    "no response at all" -- but 0 is not itself validated anywhere as
    unsafe, so a future change that let 0 flow through as if it were a real
    status code would silently be accepted. This function is the single
    place that decides whether a StatusCode value could ever have come from
    an actual HTTP response. $null and 0 both fail -- neither represents a
    response Flutterwave (or any HTTP server) could genuinely return.
    #>
    [OutputType([bool])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowNull()]
        [Nullable[int]]$StatusCode
    )
    if ($null -eq $StatusCode) { return $false }
    if ($StatusCode -lt 100 -or $StatusCode -gt 599) { return $false }
    return $true
}

function Test-IsSafeResponseBoundary {
    <#
    The "validate safe response boundary" step of the required byte-
    authority sequence (HTTP bytes -> validate boundary -> persist -> hash
    -> decode -> stage). This is deliberately NOT a content/JSON validity
    check (that happens later, via Get-CaptureOutcome, AFTER the bytes are
    already persisted) -- it exists only to refuse to attempt persisting a
    genuinely absent response (a total transport failure with no status
    code and no bytes at all), where there is nothing meaningful to write.
    A non-2xx status WITH a real body (e.g. a 400 with a JSON error) still
    passes this boundary check and gets its bytes persisted -- an orphaned
    raw file for a rejected capture is explicitly acceptable; persisting
    nothing for a connection that never produced a response is not useful
    evidence to begin with.

    CORRECTED (Codex FINAL LIVE HTTP BYTE-BOUNDARY audit): StatusCode is now
    validated via Test-IsValidHttpStatusCode -- $null OR 0 OR any value
    outside [100,599] fails this boundary, closing the gap where an
    invented sentinel status code could have been mistaken for a genuine
    response.
    #>
    [OutputType([bool])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowNull()]
        [Nullable[int]]$StatusCode,

        [Parameter(Mandatory = $true)]
        [AllowNull()]
        [byte[]]$BodyBytes
    )
    if (-not (Test-IsValidHttpStatusCode -StatusCode $StatusCode)) { return $false }
    if ($null -eq $BodyBytes) { return $false }
    return $true
}

function Get-WebResponseBytes {
    <#
    CORRECTED (Codex FINAL LIVE HTTP BYTE-BOUNDARY audit): extracts the
    GENUINE byte sequence of a successful Invoke-WebRequest response body,
    never through $webResponse.Content (a decoded STRING -- re-encoding it
    via UTF8.GetBytes() does not reproduce the original bytes unless the
    response happened to be UTF-8 with no BOM/encoding quirks, which cannot
    be assumed for a third-party provider). Invoke-WebRequest's response
    object (WebResponseObject / BasicHtmlWebResponseObject, identical shape
    on Windows PowerShell 5.1 and PowerShell 7+) exposes RawContentStream --
    the actual bytes read off the wire, before any string decoding -- and
    this function reads that stream directly into a byte array. Property
    access is duck-typed (via .PSObject.Properties) rather than a type
    check, so the SAME function is directly callable from tests with a
    lightweight fake object carrying just a RawContentStream property --
    the production adapter and the tests exercise this exact code path,
    never two parallel implementations.
    #>
    [OutputType([hashtable])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowNull()]
        $WebResponse
    )
    if ($null -eq $WebResponse) {
        return @{ Success = $false; Reason = 'RAW_RESPONSE_BYTES_UNAVAILABLE'; Bytes = $null }
    }
    try {
        $rawStreamProperty = $WebResponse.PSObject.Properties['RawContentStream']
        $stream = if ($rawStreamProperty) { $rawStreamProperty.Value } else { $null }
        if ($null -eq $stream) {
            return @{ Success = $false; Reason = 'RAW_RESPONSE_BYTES_UNAVAILABLE'; Bytes = $null }
        }
        if ($stream.CanSeek) { $stream.Position = 0 }
        $memoryStream = New-Object System.IO.MemoryStream
        $stream.CopyTo($memoryStream)
        return @{ Success = $true; Reason = 'OK'; Bytes = $memoryStream.ToArray() }
    }
    catch {
        return @{ Success = $false; Reason = 'RAW_RESPONSE_BYTES_UNAVAILABLE'; Bytes = $null }
    }
}

function Get-ErrorResponseBytes {
    <#
    CORRECTED (Codex FINAL LIVE HTTP BYTE-BOUNDARY audit): extracts the
    GENUINE byte sequence of a non-2xx error response body, never through a
    StreamReader-decoded string (the same byte-fidelity problem as
    Get-WebResponseBytes above -- ReadToEnd() decodes to a STRING using a
    detected/default encoding, and there is no safe way back to the exact
    original bytes from that string). Windows PowerShell 5.1 throws
    System.Net.WebException with a .Response of type
    System.Net.HttpWebResponse (GetResponseStream()); PowerShell 7+ throws
    Microsoft.PowerShell.Commands.HttpResponseException with a .Response of
    type System.Net.Http.HttpResponseMessage (.Content.ReadAsByteArrayAsync().
    Result). Both shapes are tried, via duck-typed member detection (never a
    hard [type] check, so a lightweight fake object of either shape is
    directly usable from tests) -- neither call touches a decoded string at
    any point. If neither shape is present/usable, this fails closed rather
    than guessing.
    #>
    [OutputType([hashtable])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowNull()]
        $ErrorResponse
    )
    if ($null -eq $ErrorResponse) {
        return @{ Success = $false; Reason = 'RAW_RESPONSE_BYTES_UNAVAILABLE'; Bytes = $null }
    }

    $getResponseStreamMethod = $ErrorResponse.PSObject.Methods['GetResponseStream']
    if ($getResponseStreamMethod) {
        try {
            $stream = $ErrorResponse.GetResponseStream()
            if ($stream) {
                $memoryStream = New-Object System.IO.MemoryStream
                $stream.CopyTo($memoryStream)
                return @{ Success = $true; Reason = 'OK'; Bytes = $memoryStream.ToArray() }
            }
        }
        catch { }
    }

    $contentProperty = $ErrorResponse.PSObject.Properties['Content']
    if ($contentProperty -and $contentProperty.Value) {
        try {
            $readMethod = $contentProperty.Value.PSObject.Methods['ReadAsByteArrayAsync']
            if ($readMethod) {
                $task = $contentProperty.Value.ReadAsByteArrayAsync()
                $bytes = $task.Result
                if ($null -ne $bytes) {
                    return @{ Success = $true; Reason = 'OK'; Bytes = $bytes }
                }
            }
        }
        catch { }
    }

    return @{ Success = $false; Reason = 'RAW_RESPONSE_BYTES_UNAVAILABLE'; Bytes = $null }
}

function New-ImmutableBytesFile {
    <#
    The raw-evidence counterpart of New-ImmutableJsonFile: atomic CREATE-NEW
    write of an exact byte sequence (never text-encoded/decoded first, so
    no intermediate encoding step can alter what gets written). Fails with
    'RAW_ALREADY_EXISTS' if the target already exists -- never overwrites,
    never appends, never silently picks a different filename -- and
    'RAW_WRITE_FAILED' for any other I/O error.
    #>
    [OutputType([hashtable])]
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][AllowNull()][byte[]]$Bytes
    )
    if ($null -eq $Bytes) { $Bytes = [byte[]]@() }
    $stream = $null
    try {
        $stream = [System.IO.File]::Open($Path, [System.IO.FileMode]::CreateNew, [System.IO.FileAccess]::Write)
        $stream.Write($Bytes, 0, $Bytes.Length)
        $stream.Flush()
        return @{ Success = $true; Reason = 'OK' }
    }
    catch [System.IO.IOException] {
        return @{ Success = $false; Reason = 'RAW_ALREADY_EXISTS' }
    }
    catch {
        return @{ Success = $false; Reason = 'RAW_WRITE_FAILED' }
    }
    finally {
        if ($stream) { $stream.Dispose() }
    }
}

function Get-RawEvidenceFileName {
    <#
    The one, deterministic, session-bound raw-evidence filename builder --
    used identically when WRITING (CreateCheckout/Verify orchestration) and
    when RE-READING (FinalizeManifest's independent hash re-verification),
    so there is only one naming rule to keep in sync. Never includes a
    random/timestamp suffix -- the whole point is that this exact filename
    is reproducible from (ActionName, TestLabel, CaptureSessionId) alone,
    which is also what makes atomic create-new semantics meaningful (a
    retry of the same action for the same session correctly collides,
    rather than silently creating a second, differently-named raw file).
    #>
    [OutputType([string])]
    param(
        [Parameter(Mandatory = $true)][string]$ActionName,
        [Parameter(Mandatory = $true)][string]$TestLabel,
        [Parameter(Mandatory = $true)][string]$CaptureSessionId
    )
    return "raw-$ActionName-Test$TestLabel-$CaptureSessionId.json"
}

function Get-RetainedRawBytes {
    <#
    Loads the exact retained raw-evidence bytes for one (ActionName,
    TestLabel, CaptureSessionId), by EXACT filename match -- the same
    missing/duplicate discipline as Get-StageCapture, applied to raw
    evidence. Used by FinalizeManifest to independently re-hash the
    retained originals and compare against each stage's own recorded
    raw_response_sha256, per the finalization-integrity requirement.
    Returns @{ Success; Reason; Bytes }. Reason: 'MISSING', 'DUPLICATE',
    'UNREADABLE', or 'OK'.
    #>
    [OutputType([hashtable])]
    param(
        [Parameter(Mandatory = $true)][string]$EvidenceRoot,
        [Parameter(Mandatory = $true)][string]$ActionName,
        [Parameter(Mandatory = $true)][string]$TestLabel,
        [Parameter(Mandatory = $true)][string]$CaptureSessionId
    )
    $pattern = Get-RawEvidenceFileName -ActionName $ActionName -TestLabel $TestLabel -CaptureSessionId $CaptureSessionId
    $found = @(Get-ChildItem -Path $EvidenceRoot -Filter $pattern -ErrorAction SilentlyContinue)

    if ($found.Count -eq 0) {
        return @{ Success = $false; Reason = 'MISSING'; Bytes = $null }
    }
    if ($found.Count -gt 1) {
        return @{ Success = $false; Reason = 'DUPLICATE'; Bytes = $null }
    }
    try {
        $bytes = [System.IO.File]::ReadAllBytes($found[0].FullName)
        return @{ Success = $true; Reason = 'OK'; Bytes = $bytes }
    }
    catch {
        return @{ Success = $false; Reason = 'UNREADABLE'; Bytes = $null }
    }
}

function Format-CreateCheckoutFailureMessage {
    <#
    CORRECTED (Codex FINAL BOUNDED POWERSHELL STRICT-MODE audit): builds the
    exact CreateCheckout failure message the CLI wrapper (Invoke-
    FlutterwaveEvidenceCapture.ps1) prints to the operator. Extracted here,
    rather than left inline in the CLI wrapper's switch statement, so the
    SAME implementation is what both the real CLI failure branch and the
    test suite exercise -- never a parallel reimplementation that could
    silently drift from what actually runs.

    A real Windows execution proved the CLI wrapper's prior inline logic
    unsafe: it dot-accessed $result.Detail directly. Detail is an OPTIONAL
    key on an Invoke-CreateCheckoutOrchestration failure result -- it is
    present ONLY for the BROWSER_LAUNCH_FAILED reason; every other failure
    reason (NO_RESPONSE_RECEIVED, RAW_RESPONSE_BYTES_UNAVAILABLE,
    RAW_ALREADY_EXISTS, MALFORMED_JSON, NON_2XX, MISSING_LINK,
    MALFORMED_LINK, NOT_HTTPS, UNAPPROVED_HOST, STAGE_ALREADY_EXISTS, ...)
    returns a hashtable with NO Detail key at all -- not Detail = $null, but
    the key genuinely absent. Under Set-StrictMode -Version Latest (active
    in both the CLI wrapper and this library), dot-accessing an ABSENT
    hashtable key throws PropertyNotFoundStrict, which masked the real
    Reason and prevented safe diagnosis of every failure except the one
    reason that happens to carry Detail. Fixed by using ContainsKey/indexed
    access exclusively -- never dot notation -- for the optional Detail key.
    Reason itself is NOT treated as optional here: every single return path
    of Invoke-CreateCheckoutOrchestration includes a Reason key, so dot-
    accessing it is provably safe and is not defensively guarded.
    #>
    [OutputType([string])]
    param(
        [Parameter(Mandatory = $true)]
        [hashtable]$Result
    )
    $reason = if ($Result.ContainsKey('Reason')) { [string]$Result['Reason'] } else { 'UNKNOWN' }
    $detail = ''
    if ($Result.ContainsKey('Detail') -and -not [string]::IsNullOrWhiteSpace([string]$Result['Detail'])) {
        $detail = " ($([string]$Result['Detail']))"
    }
    return "CreateCheckout failed: $reason$detail. No stage file written."
}

function Test-IsTestModeKey {
    <#
    Fail-closed validation of Flutterwave's documented TEST secret-key
    format: FLWSECK_TEST-<32 hex characters>-X, case-sensitive prefix and
    suffix. A key that merely CONTAINS the substring "test" anywhere (e.g.
    in an unrelated comment, a mistyped live key, or an attacker-supplied
    string) is REJECTED -- only an exact, documented-shape match is accepted.
    This is a defense-in-depth backstop; the explicit human TEST-MODE-
    CONFIRMED prompt in the real collector is the primary control and is
    never removed or weakened by this check.
    #>
    [OutputType([bool])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowEmptyString()]
        [string]$KeyValue
    )
    if ([string]::IsNullOrWhiteSpace($KeyValue)) { return $false }
    return ($KeyValue -cmatch '^FLWSECK_TEST-[a-fA-F0-9]{32}-X$')
}

function Get-CaptureOutcome {
    <#
    Pure decision function: given an HTTP status code and a raw response
    body, decides whether this capture is usable evidence.
      - Reason 'NON_2XX'       : status code outside [200,299] -- abort.
      - Reason 'MALFORMED_JSON': status was 2xx but the body is empty,
                                  whitespace-only, or does not parse -- abort.
      - Reason 'OK'            : status was 2xx and the body parsed -- proceed.
    Never throws for a malformed body; malformed input is a normal, expected
    outcome this function reports, not an exceptional one.
    #>
    [OutputType([hashtable])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowNull()]
        [Nullable[int]]$StatusCode,

        [Parameter(Mandatory = $true)]
        [AllowNull()]
        [AllowEmptyString()]
        [string]$RawBody
    )

    if ($null -eq $StatusCode -or $StatusCode -lt 200 -or $StatusCode -ge 300) {
        return @{ Success = $false; Reason = 'NON_2XX'; Parsed = $null }
    }

    if ([string]::IsNullOrWhiteSpace($RawBody)) {
        return @{ Success = $false; Reason = 'MALFORMED_JSON'; Parsed = $null }
    }

    try {
        $parsed = $RawBody | ConvertFrom-Json -ErrorAction Stop
    }
    catch {
        return @{ Success = $false; Reason = 'MALFORMED_JSON'; Parsed = $null }
    }

    return @{ Success = $true; Reason = 'OK'; Parsed = $parsed }
}

# ---------------------------------------------------------------------------
# ALLOWLIST evidence projection (replaces the removed denylist redaction).
# ---------------------------------------------------------------------------

# CORRECTED, this revision (Blocker 2 of the live-path re-audit): the prior
# pattern matched broad SUBSTRINGS ('created', 'completed', 'processed',
# 'expire', 'expiry', ...) against ANY key name, with no check on the VALUE
# at all. Two concrete failures resulted: (1) a card field literally named
# `expiry` (Flutterwave's real card-expiry field, e.g. "09/22") matched the
# substring 'expire|expiry' and would have entered the manifest as if it
# were a timestamp; (2) unrelated fields like `created_by`/`processed_by`
# (an actor identifier, not a time) matched the substrings 'created'/
# 'processed' with no value check to catch the mistake.
#
# Corrected to an EXACT-KEY allowlist (never a substring) combined with a
# MANDATORY value-shape check (Test-IsApprovedTimestampValue, below) -- a
# field enters provider_evidence_fields only when BOTH conditions hold.
# `expiry`/`expiration` are not in this list and never will be; a card
# expiry value like "09/22" also fails the value check independently (it is
# neither a valid ISO-8601 timestamp nor a plausible epoch number), so even
# a hypothetical future field named exactly `created_at` that somehow held
# a non-timestamp string would still be rejected on the value side.
$script:ApprovedTimestampExactKeys = @('created_at', 'completed_at', 'processed_at', 'settled_at', 'timestamp')
$script:ApprovedTimestampKeySuffixPattern = '(?i)_datetime$'

function Test-IsApprovedTimestampKey {
    <#
    EXACT match only (case-insensitive) against a fixed, closed list, plus
    the one explicitly-approved suffix pattern (*_datetime). Never a
    substring match against 'created'/'completed'/'processed'/'expire' or
    similar -- that broad-substring behavior is exactly what let `expiry`
    and `created_by` through in the prior revision.
    #>
    [OutputType([bool])]
    param([Parameter(Mandatory = $true)][string]$KeyName)
    $lname = $KeyName.ToLowerInvariant()
    if ($script:ApprovedTimestampExactKeys -contains $lname) { return $true }
    if ($KeyName -match $script:ApprovedTimestampKeySuffixPattern) { return $true }
    return $false
}

function Test-IsApprovedTimestampValue {
    <#
    A field's KEY name alone is never sufficient -- the VALUE must also
    independently validate as either:
      (a) a strict ISO-8601 UTC/offset timestamp (date, time, and an
          explicit 'Z' or +hh:mm/-hh:mm offset -- never a bare date, never
          a locale-ambiguous format like "09/22" or "22/09/2020"), or
      (b) an explicitly-supported epoch representation: a purely-numeric
          string of EXACTLY 10 digits (epoch seconds) or 13 digits (epoch
          milliseconds), whose resulting instant falls within a sane
          [2000-01-01, 2100-01-01) range.
    A card expiry value such as "09/22" satisfies NEITHER shape (it is not
    ISO-8601 -- no time component, no zone -- and it is not purely numeric
    for the epoch check, since it contains "/"), so it is rejected on the
    value side independent of whatever key name it might appear under.
    #>
    [OutputType([bool])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowNull()]
        $Value
    )
    if ($null -eq $Value) { return $false }

    $textValue = $null
    if ($Value -is [string]) { $textValue = $Value }
    elseif ($Value -is [DateTime]) {
        # CROSS-PLATFORM: PowerShell 7+ (this project's CI) auto-converts an
        # ISO-8601-shaped JSON string into a real [DateTime] during
        # ConvertFrom-Json -- this happens for FRESH HTTP response bodies
        # too, not only stage files re-read from disk (Get-StageCapture's
        # own ConvertTo-NormalizedJsonValue only protects the latter). A
        # genuine [DateTime] object is unambiguously a real timestamp by
        # construction -- it cannot be a card-expiry-shaped false positive
        # like "09/22" -- so it is reformatted to the same canonical
        # round-trip UTC string form and re-validated the same way a
        # string value would be, never trusted blindly.
        $textValue = ([DateTime]::SpecifyKind($Value, [System.DateTimeKind]::Utc)).ToString('o')
    }
    elseif ($Value -is [int] -or $Value -is [long] -or $Value -is [double] -or $Value -is [decimal]) {
        $textValue = [string]$Value
    }
    else { return $false }

    if ([string]::IsNullOrWhiteSpace($textValue)) { return $false }

    if ($textValue -match '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})$') {
        try {
            [void][DateTime]::Parse($textValue, [System.Globalization.CultureInfo]::InvariantCulture, [System.Globalization.DateTimeStyles]::RoundtripKind)
            return $true
        }
        catch { return $false }
    }

    if ($textValue -match '^\d{10}$' -or $textValue -match '^\d{13}$') {
        $epochSeconds = if ($textValue.Length -eq 13) { [long]([double]$textValue / 1000) } else { [long]$textValue }
        $minEpoch = 946684800   # 2000-01-01T00:00:00Z
        $maxEpoch = 4102444800  # 2100-01-01T00:00:00Z
        return ($epochSeconds -ge $minEpoch -and $epochSeconds -lt $maxEpoch)
    }

    return $false
}

# The ONLY non-timestamp scalar key names ever allowed into shareable
# evidence, matched case-insensitively, anywhere in the tree.
$script:AllowlistedScalarKeys = @('status', 'amount', 'currency')

function Get-AllowlistedEvidenceFields {
    <#
    Walks a parsed JSON tree and returns a FLAT ARRAY of only the fields
    that pass the allowlist -- each entry is @{ path; key; value }, where
    `path` is the field's full JSON path (e.g. 'data.customer.created_at' or
    'data.events[2].created_at'), so provenance is preserved without ever
    reconstructing or returning the original nested object.

    Everything not explicitly allowed -- card/token fields, identifiers,
    contact details, device/IP fields, and any field this allowlist has
    never seen before -- is silently absent from the result. There is no
    "unless recognized as sensitive" branch: absence is the default.
    #>
    [OutputType([object[]])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowNull()]
        $Node,

        # Empty by default: paths are built purely from the REAL structure of
        # $Node (e.g. a response shaped { status, data: { created_at, ... } }
        # naturally yields paths 'status' and 'data.created_at'). Only pass a
        # non-empty prefix if $Node itself is already a sub-tree whose true
        # root path is known to the caller.
        [string]$PathPrefix = ''
    )

    $results = New-Object System.Collections.Generic.List[object]
    Add-AllowlistedFields -Node $Node -Path $PathPrefix -Results $results
    return , @($results.ToArray())
}

function Add-AllowlistedFields {
    param($Node, [string]$Path, $Results)

    if ($null -eq $Node) { return }

    if ($Node -is [System.Management.Automation.PSCustomObject]) {
        foreach ($prop in $Node.PSObject.Properties) {
            $childPath = if ([string]::IsNullOrEmpty($Path)) { $prop.Name } else { "$Path.$($prop.Name)" }
            $val = $prop.Value
            $lname = $prop.Name.ToLowerInvariant()

            $isContainer = ($val -is [System.Management.Automation.PSCustomObject]) -or
                           ($val -is [System.Collections.IEnumerable] -and -not ($val -is [string]))

            if ($isContainer) {
                Add-AllowlistedFields -Node $val -Path $childPath -Results $Results
            }
            elseif ($script:AllowlistedScalarKeys -contains $lname) {
                $Results.Add([PSCustomObject]@{ path = $childPath; key = $prop.Name; value = $val })
            }
            elseif ((Test-IsApprovedTimestampKey -KeyName $prop.Name) -and (Test-IsApprovedTimestampValue -Value $val)) {
                # BOTH the exact-key check AND the value-shape check must pass.
                # A field named exactly `created_at` whose value is NOT a
                # valid timestamp (a hypothetical malformed/mistyped date) is
                # still rejected here -- the key alone is never sufficient.
                # The STORED value is always normalized to a plain string
                # (never a raw [DateTime] object) -- PS7's ConvertFrom-Json
                # can hand back a real DateTime for an ISO-shaped value even
                # for a FRESH HTTP response (not only a re-read stage file),
                # and storing that object as-is would reintroduce the exact
                # culture-formatting/precision-loss defect
                # ConvertTo-NormalizedJsonValue exists to prevent elsewhere.
                $storedValue = if ($val -is [DateTime]) { ([DateTime]::SpecifyKind($val, [System.DateTimeKind]::Utc)).ToString('o') } else { $val }
                $Results.Add([PSCustomObject]@{ path = $childPath; key = $prop.Name; value = $storedValue })
            }
            # Every other field -- named or not, including `expiry`/
            # `expiration`/`created_by`/`processed_by` and any field whose
            # name merely CONTAINS created/completed/processed/settled/
            # expire without being an exact match -- is discarded here, by
            # omission, never by an exclusion rule that could miss a case.
        }
    }
    elseif ($Node -is [System.Collections.IEnumerable] -and -not ($Node -is [string])) {
        $i = 0
        foreach ($item in $Node) {
            Add-AllowlistedFields -Node $item -Path "$Path[$i]" -Results $Results
            $i++
        }
    }
    # Bare scalars at the root (no key name) are never allowlisted -- the
    # allowlist is a NAME-based decision and a bare scalar has no name.
}

function Get-DataField {
    <#
    Targeted, non-recursive lookup of $Parsed.data.<FieldName> -- used to
    extract tx_ref and the transaction id from a real Flutterwave v3
    response shape ({ status, message, data: { id, tx_ref, ... } }).
    Deliberately NOT a recursive "find any key named X anywhere" search,
    which could silently grab an unrelated nested field of the same name
    (e.g. customer.id instead of data.id).
    #>
    [OutputType([string])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowNull()]
        $Parsed,

        [Parameter(Mandatory = $true)]
        [string]$FieldName
    )
    # NOTE: property-existence is checked via `@(...Properties.Name) -contains
    # ...` rather than `.Properties.Match(...).Count` -- the latter's exact
    # behavior on an empty/absent match differs across PowerShell versions
    # (Windows PowerShell 5.1 vs. PowerShell 7+ on Linux, as run in CI), and
    # this project has already hit that class of cross-version quirk more
    # than once. `-contains` against a plain string array is unambiguous and
    # version-stable everywhere.
    if ($null -eq $Parsed) { return $null }
    $topLevelNames = @($Parsed.PSObject.Properties | ForEach-Object { $_.Name })
    if ($topLevelNames -notcontains 'data') { return $null }
    $data = $Parsed.data
    if ($null -eq $data) { return $null }
    $dataNames = @($data.PSObject.Properties | ForEach-Object { $_.Name })
    if ($dataNames -notcontains $FieldName) { return $null }
    $value = $data.$FieldName
    if ($null -eq $value) { return $null }
    return [string]$value
}

# The one documented Flutterwave v3 hosted-checkout domain, per Flutterwave's
# own Standard Checkout documentation example response
# ({"status":"success","message":"Hosted Link","data":{"link":"https://checkout.flutterwave.com/v3/hosted/pay/..."}}).
# A strict, exact-host allowlist -- never a substring/wildcard match -- so a
# link on an unrelated or look-alike domain is rejected, not "close enough."
$script:ApprovedHostedCheckoutHost = 'checkout.flutterwave.com'

function Get-HostedCheckoutLink {
    <#
    CORRECTED, this revision (Blocker 1 of the live-path re-audit): the
    collector previously called Start-Process against the API REQUEST URI
    (https://api.flutterwave.com/v3/payments) instead of the hosted
    checkout page Flutterwave's response actually returns in `data.link` --
    it never even read that field. This function is the single, pure
    extraction-and-validation point every caller must go through before
    opening anything in a browser.

    Requires ALL of, in order:
      - $Parsed.status is exactly 'success' (Flutterwave's own documented
        success indicator for this endpoint)
      - $Parsed.data.link exists and is non-empty
      - it parses as an ABSOLUTE URI
      - its scheme is exactly 'https' (never a bare http link)
      - its host is exactly the documented Flutterwave hosted-checkout host

    Returns @{ Success; Reason; Link } -- Link is $null on any failure.
    Reason values: 'NULL_RESPONSE', 'STATUS_NOT_SUCCESS', 'MISSING_LINK',
    'MALFORMED_LINK', 'NOT_HTTPS', 'UNAPPROVED_HOST', 'OK'.
    #>
    [OutputType([hashtable])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowNull()]
        $Parsed
    )

    if ($null -eq $Parsed) {
        return @{ Success = $false; Reason = 'NULL_RESPONSE'; Link = $null }
    }

    $status = $null
    $topLevelNames = @($Parsed.PSObject.Properties | ForEach-Object { $_.Name })
    if ($topLevelNames -contains 'status') { $status = $Parsed.status }
    if ($status -ne 'success') {
        return @{ Success = $false; Reason = 'STATUS_NOT_SUCCESS'; Link = $null }
    }

    $link = Get-DataField -Parsed $Parsed -FieldName 'link'
    if ([string]::IsNullOrWhiteSpace($link)) {
        return @{ Success = $false; Reason = 'MISSING_LINK'; Link = $null }
    }

    $uri = $null
    if (-not [System.Uri]::TryCreate($link, [System.UriKind]::Absolute, [ref]$uri)) {
        return @{ Success = $false; Reason = 'MALFORMED_LINK'; Link = $null }
    }

    if ($uri.Scheme -ne 'https') {
        return @{ Success = $false; Reason = 'NOT_HTTPS'; Link = $null }
    }

    if ($uri.Host -ne $script:ApprovedHostedCheckoutHost) {
        return @{ Success = $false; Reason = 'UNAPPROVED_HOST'; Link = $null }
    }

    return @{ Success = $true; Reason = 'OK'; Link = $link }
}

function New-ImmutableJsonFile {
    <#
    CORRECTED, this revision (write-once stages, Codex re-audit High):
    writes $Content to $Path using atomic CREATE-NEW file semantics --
    [System.IO.FileMode]::CreateNew throws if the file already exists,
    which .NET/the OS guarantee is checked atomically (no separate
    Test-Path-then-write race window). If the target already exists, this
    function returns failure and writes NOTHING -- it never overwrites,
    never appends, and never silently picks a different filename.
    Returns @{ Success; Reason } -- Reason 'OK' or 'STAGE_ALREADY_EXISTS'
    (or 'WRITE_FAILED' for any other I/O error, e.g. an unwritable
    directory, which is a distinct failure mode from "already exists").
    #>
    [OutputType([hashtable])]
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$Content
    )
    $stream = $null
    try {
        $stream = [System.IO.File]::Open($Path, [System.IO.FileMode]::CreateNew, [System.IO.FileAccess]::Write)
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($Content)
        $stream.Write($bytes, 0, $bytes.Length)
        $stream.Flush()
        return @{ Success = $true; Reason = 'OK' }
    }
    catch [System.IO.IOException] {
        return @{ Success = $false; Reason = 'STAGE_ALREADY_EXISTS' }
    }
    catch {
        return @{ Success = $false; Reason = 'WRITE_FAILED' }
    }
    finally {
        if ($stream) { $stream.Dispose() }
    }
}

function Test-TimelineOrdering {
    <#
    Validates the full six-point capture timeline. Every timestamp must be a
    valid, round-trippable UTC ISO-8601 string, and they must be
    non-decreasing in this exact order:
      CheckoutRequestStartUtc <= CheckoutRequestEndUtc <= CheckoutOpenedUtc
        <= PaymentCompletionObservedUtc <= VerifyRequestStartUtc <= VerifyRequestEndUtc
    For a Test B capture, PaymentCompletionObservedUtc - CheckoutOpenedUtc
    must additionally be >= 600 seconds.
    Returns @{ Valid = [bool]; Reason = [string] } -- never throws on bad
    input; a malformed/non-UTC/out-of-order/too-fast timeline is a normal,
    reportable outcome, not an exception.
    #>
    [OutputType([hashtable])]
    param(
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$CheckoutRequestStartUtc,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$CheckoutRequestEndUtc,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$CheckoutOpenedUtc,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$PaymentCompletionObservedUtc,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$VerifyRequestStartUtc,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$VerifyRequestEndUtc,
        [Parameter(Mandatory = $true)][bool]$IsTestB
    )

    $labels = @('CheckoutRequestStartUtc', 'CheckoutRequestEndUtc', 'CheckoutOpenedUtc', 'PaymentCompletionObservedUtc', 'VerifyRequestStartUtc', 'VerifyRequestEndUtc')
    $values = @($CheckoutRequestStartUtc, $CheckoutRequestEndUtc, $CheckoutOpenedUtc, $PaymentCompletionObservedUtc, $VerifyRequestStartUtc, $VerifyRequestEndUtc)

    $parsed = New-Object System.Collections.Generic.List[DateTime]
    for ($i = 0; $i -lt $values.Count; $i++) {
        if (-not (Test-IsValidUtcTimestamp -Value $values[$i])) {
            return @{ Valid = $false; Reason = "MALFORMED_OR_NON_UTC:$($labels[$i])" }
        }
        $parsed.Add([DateTime]::Parse($values[$i], [System.Globalization.CultureInfo]::InvariantCulture, [System.Globalization.DateTimeStyles]::RoundtripKind))
    }

    for ($i = 0; $i -lt $parsed.Count - 1; $i++) {
        if ($parsed[$i] -gt $parsed[$i + 1]) {
            return @{ Valid = $false; Reason = "ORDER_VIOLATION:$($labels[$i])>$($labels[$i + 1])" }
        }
    }

    if ($IsTestB) {
        $elapsedSeconds = ($parsed[3] - $parsed[2]).TotalSeconds
        if ($elapsedSeconds -lt 600) {
            return @{ Valid = $false; Reason = "TEST_B_MINIMUM_NOT_MET:$([math]::Round($elapsedSeconds, 3))s" }
        }
    }

    return @{ Valid = $true; Reason = 'OK' }
}

function ConvertTo-NormalizedJsonValue {
    <#
    CROSS-PLATFORM FIX: `ConvertFrom-Json` on PowerShell 7+ (the engine this
    project's CI runs under, on Linux) auto-detects ISO-8601-shaped JSON
    string values and silently deserializes them as real `[DateTime]`
    objects -- Windows PowerShell 5.1 (used for local development on this
    project) does NOT do this; it keeps them as plain strings. The practical
    effect: a stage file written as `"request_start_utc":
    "2026-09-11T18:00:30.3901135Z"` reads back, on PS7, as a genuine
    `[DateTime]` object; a later NAIVE `[string]$value` cast on it then uses
    the CURRENT CULTURE's default ToString() format ("09/11/2026 18:00:30")
    -- silently dropping the 'Z'/UTC marker AND all sub-second precision,
    which then fails `Test-IsValidUtcTimestamp`'s round-trip check. This was
    confirmed empirically via an isolated JSON round-trip repro in
    tests/FlutterwaveEvidenceLib.Tests.ps1 before this fix was written.

    This function walks a parsed JSON object graph (PSCustomObject/array/
    scalar) and converts any `[DateTime]`-typed value back to the SAME
    round-trippable ISO-8601 UTC string form `Get-UtcTimestamp` itself
    produces (`.ToString('o')`), so every consumer downstream of
    `Get-StageCapture` sees the identical string shape regardless of which
    PowerShell version/engine wrote or read the file.
    #>
    [OutputType([object])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowNull()]
        $Node
    )

    if ($null -eq $Node) { return $Node }

    if ($Node -is [DateTime]) {
        # RELABEL (never re-convert) as Utc: PS7's auto-parse of a
        # 'Z'-suffixed ISO string preserves the correct underlying instant
        # (confirmed empirically -- the wall-clock digits survive the round
        # trip unchanged) but can leave the object's own .Kind tag as
        # something other than Utc, and a naive default ToString() also
        # drops sub-second precision from the display. `SpecifyKind` re-tags
        # the SAME numeric value as Utc without shifting it (unlike
        # `ToUniversalTime()`, which would incorrectly shift an
        # Unspecified-kind value by treating it as local time first) --
        # exactly correct here, since Get-UtcTimestamp only ever produces
        # genuinely UTC instants in the first place.
        $asUtc = [DateTime]::SpecifyKind($Node, [System.DateTimeKind]::Utc)
        return $asUtc.ToString('o')
    }

    if ($Node -is [System.Management.Automation.PSCustomObject]) {
        $result = [ordered]@{}
        foreach ($prop in $Node.PSObject.Properties) {
            $result[$prop.Name] = ConvertTo-NormalizedJsonValue -Node $prop.Value
        }
        return [PSCustomObject]$result
    }

    if ($Node -is [System.Collections.IEnumerable] -and -not ($Node -is [string])) {
        return @($Node | ForEach-Object { ConvertTo-NormalizedJsonValue -Node $_ })
    }

    return $Node
}

function Get-StageCapture {
    <#
    Loads exactly one stage-capture file for a given (ActionName, TestLabel,
    CaptureSessionId) triple, by EXACT filename match -- never "the newest
    file matching a prefix." This is the function that structurally replaces
    the earlier collector's "select the latest stage-* file" logic; there is
    no sorting by timestamp anywhere in this function or its caller.

    Returns @{ Success; Reason; Data }:
      Reason 'MISSING'          -- zero files match the exact filename.
      Reason 'DUPLICATE'        -- more than one file matches (should be
                                    structurally impossible given an exact
                                    filename, but checked explicitly rather
                                    than assumed).
      Reason 'SESSION_MISMATCH' -- the file's OWN capture_session_id field
                                    disagrees with the filename/request.
      Reason 'LABEL_MISMATCH'   -- the file's OWN test_label field disagrees
                                    with the filename/request.
      Reason 'OK'               -- exactly one matching, internally-
                                    consistent file was found; Data holds its
                                    parsed content.
    Reads a file from disk (EvidenceRoot); makes no network call, touches no
    secret. Directly testable against a temp directory of synthetic files.
    #>
    [OutputType([hashtable])]
    param(
        [Parameter(Mandatory = $true)][string]$EvidenceRoot,
        [Parameter(Mandatory = $true)][string]$ActionName,
        [Parameter(Mandatory = $true)][string]$TestLabel,
        [Parameter(Mandatory = $true)][string]$CaptureSessionId
    )

    $pattern = "stage-$ActionName-Test$TestLabel-$CaptureSessionId.json"
    $found = @(Get-ChildItem -Path $EvidenceRoot -Filter $pattern -ErrorAction SilentlyContinue)

    if ($found.Count -eq 0) {
        return @{ Success = $false; Reason = 'MISSING'; Data = $null }
    }
    if ($found.Count -gt 1) {
        return @{ Success = $false; Reason = 'DUPLICATE'; Data = $null }
    }

    $data = Get-Content -Path $found[0].FullName -Raw | ConvertFrom-Json
    # Normalize away any PS7-vs-5.1 auto-DateTime-conversion difference
    # BEFORE this data is used for anything -- see ConvertTo-NormalizedJsonValue.
    $data = ConvertTo-NormalizedJsonValue -Node $data

    if ($data.capture_session_id -ne $CaptureSessionId) {
        return @{ Success = $false; Reason = 'SESSION_MISMATCH'; Data = $null }
    }
    if ($data.test_label -ne $TestLabel) {
        return @{ Success = $false; Reason = 'LABEL_MISMATCH'; Data = $null }
    }

    return @{ Success = $true; Reason = 'OK'; Data = $data }
}

function Test-IsSafeFlagResult {
    <#
    A disposable, executable PowerShell mirror of the STRICT discriminated-
    union contract pinned in IMPLEMENTATION_CONDITIONS_PINNED.md (Condition 2
    of that document). Calls no network, touches no checkout logic -- exists
    solely to prove, executably, that the pinned specification is internally
    consistent.

    Accepts EXACTLY:
      { flagged: true }                                   -- exactly one key
      { flagged: false, reason: 'ALREADY_FLAGGED' }        -- exactly two keys
      { flagged: false, reason: 'INTENT_NOT_PENDING' }     -- exactly two keys
    Rejects everything else, including an otherwise-valid shape carrying any
    additional property.
    #>
    [OutputType([bool])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowNull()]
        $FlagResult
    )

    if ($null -eq $FlagResult) { return $false }
    if ($FlagResult -is [System.Array]) { return $false }
    if ($FlagResult -is [string] -or $FlagResult -is [int] -or $FlagResult -is [double] -or $FlagResult -is [bool]) {
        return $false
    }
    if (-not ($FlagResult -is [System.Management.Automation.PSCustomObject] -or $FlagResult -is [hashtable])) {
        return $false
    }

    if ($FlagResult -is [hashtable]) {
        $keys = @($FlagResult.Keys | Sort-Object)
        $get = { param($k) $FlagResult[$k] }
    }
    else {
        $keys = @($FlagResult.PSObject.Properties | ForEach-Object { $_.Name } | Sort-Object)
        $get = { param($k) $FlagResult.$k }
    }

    if ($keys.Count -eq 1 -and $keys[0] -eq 'flagged') {
        $flaggedValue = & $get 'flagged'
        if ($flaggedValue -is [bool] -and $flaggedValue -eq $true) { return $true }
        return $false
    }

    if ($keys.Count -eq 2 -and $keys[0] -eq 'flagged' -and $keys[1] -eq 'reason') {
        $flaggedValue = & $get 'flagged'
        $reasonValue = & $get 'reason'
        if ($flaggedValue -is [bool] -and $flaggedValue -eq $false -and $reasonValue -is [string]) {
            if ($reasonValue -eq 'ALREADY_FLAGGED' -or $reasonValue -eq 'INTENT_NOT_PENDING') {
                return $true
            }
        }
        return $false
    }

    return $false
}

function New-EvidenceManifest {
    <#
    Builds the final provenance manifest object binding together every
    session-correlated field. Pure -- takes already-computed, already-
    validated inputs, writes nothing, makes no network call. Contains NO
    complete provider response, redacted or otherwise -- only the allow-
    listed evidence fields, hashes, and collector-generated provenance.
    #>
    [OutputType([System.Collections.Specialized.OrderedDictionary])]
    param(
        [Parameter(Mandatory = $true)][string]$CaptureSessionId,
        [Parameter(Mandatory = $true)][ValidateSet('A', 'B')][string]$TestLabel,
        [Parameter(Mandatory = $true)][string]$TxRefSha256,
        [Parameter(Mandatory = $true)][string]$TransactionIdSha256,
        [Parameter(Mandatory = $true)][bool]$TestModeConfirmed,
        [Parameter(Mandatory = $true)][string]$ApiVersion,
        [Parameter(Mandatory = $true)][string]$CheckoutEndpoint,
        [Parameter(Mandatory = $true)][string]$VerifyEndpoint,
        [Parameter(Mandatory = $true)][string]$CheckoutRequestStartUtc,
        [Parameter(Mandatory = $true)][string]$CheckoutRequestEndUtc,
        [Parameter(Mandatory = $true)][string]$CheckoutOpenedUtc,
        [Parameter(Mandatory = $true)][string]$PaymentCompletionObservedUtc,
        [Parameter(Mandatory = $true)][string]$VerifyRequestStartUtc,
        [Parameter(Mandatory = $true)][string]$VerifyRequestEndUtc,
        [Parameter(Mandatory = $true)][double]$ElapsedSecondsSinceCheckoutOpened,
        [Parameter(Mandatory = $true)][bool]$TimelineValid,
        [Parameter(Mandatory = $true)][object[]]$ProviderEvidenceFields,
        [Parameter(Mandatory = $true)][string]$CheckoutRawResponseSha256,
        [Parameter(Mandatory = $true)][string]$VerifyRawResponseSha256,
        [Parameter(Mandatory = $true)][string]$CheckoutRawEvidenceFilename,
        [Parameter(Mandatory = $true)][string]$VerifyRawEvidenceFilename,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$CollectorScriptGitSha,
        [Parameter(Mandatory = $true)][string]$CollectorScriptContentSha256,
        [Parameter(Mandatory = $true)][string]$PowerShellVersion,
        [Parameter(Mandatory = $true)][double]$MachineUtcOffsetMinutes
    )

    return [ordered]@{
        capture_session_id                = $CaptureSessionId
        test_label                        = $TestLabel
        tx_ref_sha256                      = $TxRefSha256
        transaction_id_sha256              = $TransactionIdSha256
        test_mode_confirmed                = $TestModeConfirmed
        api_version                        = $ApiVersion
        checkout_endpoint                  = $CheckoutEndpoint
        verify_endpoint                    = $VerifyEndpoint
        checkout_request_start_utc         = $CheckoutRequestStartUtc
        checkout_request_end_utc           = $CheckoutRequestEndUtc
        checkout_opened_utc                = $CheckoutOpenedUtc
        payment_completion_observed_utc    = $PaymentCompletionObservedUtc
        verify_request_start_utc           = $VerifyRequestStartUtc
        verify_request_end_utc             = $VerifyRequestEndUtc
        elapsed_seconds_since_checkout_opened = $ElapsedSecondsSinceCheckoutOpened
        timeline_valid                     = $TimelineValid
        provider_evidence_fields           = $ProviderEvidenceFields
        checkout_raw_response_sha256       = $CheckoutRawResponseSha256
        verify_raw_response_sha256         = $VerifyRawResponseSha256
        checkout_raw_evidence_filename     = $CheckoutRawEvidenceFilename
        verify_raw_evidence_filename       = $VerifyRawEvidenceFilename
        collector_script_git_sha           = $CollectorScriptGitSha
        collector_script_content_sha256    = $CollectorScriptContentSha256
        powershell_version                 = $PowerShellVersion
        machine_utc_offset_minutes         = $MachineUtcOffsetMinutes
    }
}

# ===========================================================================
# ORCHESTRATION FUNCTIONS (Codex live-path re-audit, item 5)
# ===========================================================================
# Each function below implements ONE full action end to end (HTTP call,
# validation, stage write) using ONLY: pure functions from this file, and
# four injected PORTS -- HttpPost/HttpGet (network transport), OpenUrl
# (browser dispatch), and NowUtc (the clock). Filesystem writes go through
# EvidenceRoot + New-ImmutableJsonFile (a real, deterministic filesystem
# operation against whatever directory is passed in -- a temp directory in
# tests, the real evidence root in production -- rather than a mocked
# filesystem, since a real write-once check against a real temp directory
# is stronger evidence than a recorded mock call).
#
# The REAL CLI script (Invoke-FlutterwaveEvidenceCapture.ps1) builds the
# real ports (Invoke-WebRequest, Start-Process, Get-UtcTimestamp) as
# closures capturing the secret/headers, and calls these same functions.
# The test suite builds SYNTHETIC ports (canned responses, a fake clock, a
# browser-open recorder) and calls the identical functions -- proving the
# real orchestration logic, not a parallel re-implementation of it.
# ===========================================================================

function Invoke-CreateCheckoutOrchestration {
    <#
    CORRECTED, this revision (Codex provenance-closure re-audit, Blocker 1):
    the raw provider response is now RETAINED, not merely hashed. The exact
    byte sequence returned by the HTTP port is persisted, write-once, to a
    deterministic session-bound raw-evidence file OUTSIDE the repository,
    BEFORE the browser is ever opened and BEFORE the sanitized stage is
    written -- following the required sequence: bytes -> validate safe
    response boundary -> persist -> hash THOSE SAME bytes -> decode THOSE
    SAME bytes for JSON parsing -> build the sanitized stage. If raw
    persistence fails for any reason, this function aborts immediately: it
    never launches the hosted checkout and never writes a stage. A
    sanitized stage is therefore never created without its corresponding
    raw file already existing on disk.
    #>
    [OutputType([hashtable])]
    param(
        [Parameter(Mandatory = $true)][ValidateSet('A', 'B')][string]$TestLabel,
        [Parameter(Mandatory = $true)][string]$CaptureSessionId,
        [Parameter(Mandatory = $true)][string]$TxRef,
        [Parameter(Mandatory = $true)][string]$Amount,
        [Parameter(Mandatory = $true)][string]$Currency,
        [Parameter(Mandatory = $true)][string]$RedirectUrl,
        [Parameter(Mandatory = $true)][string]$CustomerEmail,
        [Parameter(Mandatory = $true)][string]$EvidenceRoot,
        [Parameter(Mandatory = $true)][scriptblock]$HttpPost,   # param($Uri, $BodyJson) -> @{StatusCode; BodyBytes}
        [Parameter(Mandatory = $true)][scriptblock]$OpenUrl,    # param($Url) -> (throws on failure, never suppressed)
        [Parameter(Mandatory = $true)][scriptblock]$NowUtc,     # () -> UTC ISO-8601 string
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$CollectorScriptGitSha,
        [Parameter(Mandatory = $true)][string]$CollectorScriptContentSha256
    )

    $uri = 'https://api.flutterwave.com/v3/payments'
    $bodyJson = (@{
            tx_ref       = $TxRef
            amount       = $Amount
            currency     = $Currency
            redirect_url = $RedirectUrl
            customer     = @{ email = $CustomerEmail }
        }) | ConvertTo-Json -Depth 5

    $requestStartUtc = & $NowUtc
    $httpResult = & $HttpPost $uri $bodyJson
    $requestEndUtc = & $NowUtc

    # Step 1 of the byte-authority sequence: validate a real response
    # boundary exists at all (never attempt to persist a total transport
    # failure with no status code and no bytes). CORRECTED (Codex FINAL
    # LIVE HTTP BYTE-BOUNDARY audit): the two distinct failure modes are
    # now told apart, since they mean different things -- no HTTP response
    # was ever received at all (a genuine transport failure, StatusCode
    # null/0/out-of-range) versus a real HTTP response WAS received but its
    # body bytes could not be genuinely extracted (the port's own
    # byte-extraction boundary failed, e.g. an unreadable response stream).
    if (-not (Test-IsValidHttpStatusCode -StatusCode $httpResult.StatusCode)) {
        return @{ Success = $false; Reason = 'NO_RESPONSE_RECEIVED' }
    }
    if ($null -eq $httpResult.BodyBytes) {
        return @{ Success = $false; Reason = 'RAW_RESPONSE_BYTES_UNAVAILABLE' }
    }

    # Step 2: atomically persist the EXACT bytes received -- write-once,
    # outside the repo (EvidenceRoot is already verified outside the repo
    # by the caller), deterministic session-bound filename, never
    # overwritten. If this fails, abort immediately: no browser launch, no
    # stage. An orphan raw file from a PRIOR failed attempt is acceptable;
    # a stage without a raw file is not, so this check gates everything
    # that follows.
    $rawFileName = Get-RawEvidenceFileName -ActionName 'CreateCheckout' -TestLabel $TestLabel -CaptureSessionId $CaptureSessionId
    $rawPath = Join-Path $EvidenceRoot $rawFileName
    $rawWriteResult = New-ImmutableBytesFile -Path $rawPath -Bytes $httpResult.BodyBytes
    if (-not $rawWriteResult.Success) {
        return @{ Success = $false; Reason = $rawWriteResult.Reason }
    }

    # Step 3: hash the SAME bytes just persisted -- never a re-encoded or
    # re-serialized representation.
    $rawResponseSha256 = Get-Sha256HexFromBytes -Bytes $httpResult.BodyBytes

    # Step 4: decode those SAME bytes (never different bytes) for parsing.
    $bodyText = [System.Text.Encoding]::UTF8.GetString($httpResult.BodyBytes)

    $outcome = Get-CaptureOutcome -StatusCode $httpResult.StatusCode -RawBody $bodyText
    if (-not $outcome.Success) {
        # The raw file remains on disk as an explicitly-acceptable orphan --
        # this rejection produces no stage, per the required behavior.
        return @{ Success = $false; Reason = $outcome.Reason }
    }

    # CORRECTED (Blocker 1 of the prior live-path re-audit, unchanged here):
    # extract and validate data.link -- the ONLY URL this function will
    # ever pass to OpenUrl. $uri (the API endpoint) is NEVER passed to
    # OpenUrl anywhere in this function.
    $linkResult = Get-HostedCheckoutLink -Parsed $outcome.Parsed
    if (-not $linkResult.Success) {
        return @{ Success = $false; Reason = $linkResult.Reason }
    }

    try {
        & $OpenUrl $linkResult.Link
    }
    catch {
        # Browser-launch failure is NOT suppressed -- it aborts this action
        # and writes no stage file, exactly like every other failure path.
        return @{ Success = $false; Reason = 'BROWSER_LAUNCH_FAILED'; Detail = $_.Exception.Message }
    }

    # checkout_opened_utc is captured ONLY after OpenUrl returned without
    # throwing -- a timestamp is never recorded for a dispatch that failed.
    $checkoutOpenedUtc = & $NowUtc

    $stage = [ordered]@{
        capture_session_id              = $CaptureSessionId
        test_label                      = $TestLabel
        action                          = 'CreateCheckout'
        endpoint                        = $uri
        tx_ref_sha256                   = Get-Sha256Hex -Text $TxRef
        request_start_utc               = $requestStartUtc
        request_end_utc                 = $requestEndUtc
        checkout_opened_utc             = $checkoutOpenedUtc
        http_status                     = $httpResult.StatusCode
        raw_evidence_filename           = $rawFileName
        raw_response_sha256             = $rawResponseSha256
        provider_evidence_fields        = Get-AllowlistedEvidenceFields -Node $outcome.Parsed
        collector_script_git_sha        = $CollectorScriptGitSha
        collector_script_content_sha256 = $CollectorScriptContentSha256
    }
    $stagePath = Join-Path $EvidenceRoot "stage-CreateCheckout-Test$TestLabel-$CaptureSessionId.json"
    $writeResult = New-ImmutableJsonFile -Path $stagePath -Content ($stage | ConvertTo-Json -Depth 12)
    if (-not $writeResult.Success) {
        return @{ Success = $false; Reason = $writeResult.Reason }
    }

    return @{ Success = $true; Reason = 'OK'; StagePath = $stagePath; Link = $linkResult.Link; RawPath = $rawPath }
}

function Invoke-ObservePaymentSuccessOrchestration {
    [OutputType([hashtable])]
    param(
        [Parameter(Mandatory = $true)][ValidateSet('A', 'B')][string]$TestLabel,
        [Parameter(Mandatory = $true)][string]$CaptureSessionId,
        [Parameter(Mandatory = $true)][string]$EvidenceRoot,
        [Parameter(Mandatory = $true)][bool]$Confirmed,
        [Parameter(Mandatory = $true)][scriptblock]$NowUtc,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$CollectorScriptGitSha,
        [Parameter(Mandatory = $true)][string]$CollectorScriptContentSha256
    )

    $checkoutResult = Get-StageCapture -EvidenceRoot $EvidenceRoot -ActionName 'CreateCheckout' -TestLabel $TestLabel -CaptureSessionId $CaptureSessionId
    if (-not $checkoutResult.Success) {
        return @{ Success = $false; Reason = "CHECKOUT_STAGE_$($checkoutResult.Reason)" }
    }

    if (-not $Confirmed) {
        return @{ Success = $false; Reason = 'CONFIRMATION_NOT_PROVIDED' }
    }

    $observedUtc = & $NowUtc
    $elapsedSeconds = ([DateTime]::Parse($observedUtc, [System.Globalization.CultureInfo]::InvariantCulture, [System.Globalization.DateTimeStyles]::RoundtripKind) -
                        [DateTime]::Parse([string]$checkoutResult.Data.checkout_opened_utc, [System.Globalization.CultureInfo]::InvariantCulture, [System.Globalization.DateTimeStyles]::RoundtripKind)).TotalSeconds

    $isTestB = ($TestLabel -eq 'B')
    if ($isTestB -and $elapsedSeconds -lt 600) {
        return @{ Success = $false; Reason = "TEST_B_MINIMUM_NOT_MET:$([math]::Round($elapsedSeconds, 3))s" }
    }

    $stage = [ordered]@{
        capture_session_id                    = $CaptureSessionId
        test_label                            = $TestLabel
        action                                 = 'ObservePaymentSuccess'
        checkout_opened_utc                   = [string]$checkoutResult.Data.checkout_opened_utc
        payment_completion_observed_utc       = $observedUtc
        elapsed_seconds_since_checkout_opened = $elapsedSeconds
        test_b_minimum_met                    = $(if ($isTestB) { $elapsedSeconds -ge 600 } else { $null })
        collector_script_git_sha              = $CollectorScriptGitSha
        collector_script_content_sha256       = $CollectorScriptContentSha256
    }
    $stagePath = Join-Path $EvidenceRoot "stage-ObservePaymentSuccess-Test$TestLabel-$CaptureSessionId.json"
    $writeResult = New-ImmutableJsonFile -Path $stagePath -Content ($stage | ConvertTo-Json -Depth 8)
    if (-not $writeResult.Success) {
        return @{ Success = $false; Reason = $writeResult.Reason }
    }

    return @{ Success = $true; Reason = 'OK'; StagePath = $stagePath }
}

function Invoke-VerifyOrchestration {
    <#
    CORRECTED, this revision (Codex provenance-closure re-audit, Blocker 1):
    the raw verify response is now RETAINED, not merely hashed -- same
    byte-authority sequence as Invoke-CreateCheckoutOrchestration. If raw
    persistence fails, this function aborts immediately: it never writes a
    verification stage (and therefore FinalizeManifest can never succeed
    for this session, since it requires a Verify stage to exist).
    #>
    [OutputType([hashtable])]
    param(
        [Parameter(Mandatory = $true)][ValidateSet('A', 'B')][string]$TestLabel,
        [Parameter(Mandatory = $true)][string]$CaptureSessionId,
        [Parameter(Mandatory = $true)][string]$TransactionId,
        [Parameter(Mandatory = $true)][string]$EvidenceRoot,
        [Parameter(Mandatory = $true)][scriptblock]$HttpGet,   # param($Uri) -> @{StatusCode; BodyBytes}
        [Parameter(Mandatory = $true)][scriptblock]$NowUtc,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$CollectorScriptGitSha,
        [Parameter(Mandatory = $true)][string]$CollectorScriptContentSha256
    )

    $checkoutResult = Get-StageCapture -EvidenceRoot $EvidenceRoot -ActionName 'CreateCheckout' -TestLabel $TestLabel -CaptureSessionId $CaptureSessionId
    if (-not $checkoutResult.Success) {
        return @{ Success = $false; Reason = "CHECKOUT_STAGE_$($checkoutResult.Reason)" }
    }
    $observeResult = Get-StageCapture -EvidenceRoot $EvidenceRoot -ActionName 'ObservePaymentSuccess' -TestLabel $TestLabel -CaptureSessionId $CaptureSessionId
    if (-not $observeResult.Success) {
        return @{ Success = $false; Reason = "OBSERVE_STAGE_$($observeResult.Reason)" }
    }

    $uri = "https://api.flutterwave.com/v3/transactions/$TransactionId/verify"
    $requestStartUtc = & $NowUtc
    $httpResult = & $HttpGet $uri
    $requestEndUtc = & $NowUtc

    # See the identical comment in Invoke-CreateCheckoutOrchestration: these
    # are two distinct failure modes with two distinct reasons.
    if (-not (Test-IsValidHttpStatusCode -StatusCode $httpResult.StatusCode)) {
        return @{ Success = $false; Reason = 'NO_RESPONSE_RECEIVED' }
    }
    if ($null -eq $httpResult.BodyBytes) {
        return @{ Success = $false; Reason = 'RAW_RESPONSE_BYTES_UNAVAILABLE' }
    }

    $rawFileName = Get-RawEvidenceFileName -ActionName 'Verify' -TestLabel $TestLabel -CaptureSessionId $CaptureSessionId
    $rawPath = Join-Path $EvidenceRoot $rawFileName
    $rawWriteResult = New-ImmutableBytesFile -Path $rawPath -Bytes $httpResult.BodyBytes
    if (-not $rawWriteResult.Success) {
        return @{ Success = $false; Reason = $rawWriteResult.Reason }
    }

    $rawResponseSha256 = Get-Sha256HexFromBytes -Bytes $httpResult.BodyBytes
    $bodyText = [System.Text.Encoding]::UTF8.GetString($httpResult.BodyBytes)

    $outcome = Get-CaptureOutcome -StatusCode $httpResult.StatusCode -RawBody $bodyText
    if (-not $outcome.Success) {
        return @{ Success = $false; Reason = $outcome.Reason }
    }

    # CORRECTED (item 4, complete transaction binding): BOTH data.id and
    # data.tx_ref are now required, and BOTH are checked -- previously only
    # tx_ref was verified; data.id was hashed without ever confirming it
    # equals the TransactionId this call actually requested.
    $providerTxRef = Get-DataField -Parsed $outcome.Parsed -FieldName 'tx_ref'
    $providerId = Get-DataField -Parsed $outcome.Parsed -FieldName 'id'

    if ([string]::IsNullOrWhiteSpace($providerTxRef)) {
        return @{ Success = $false; Reason = 'MISSING_TX_REF' }
    }
    if ([string]::IsNullOrWhiteSpace($providerId)) {
        return @{ Success = $false; Reason = 'MISSING_TRANSACTION_ID' }
    }

    $providerTxRefSha256 = Get-Sha256Hex -Text $providerTxRef
    if ($providerTxRefSha256 -ne $checkoutResult.Data.tx_ref_sha256) {
        return @{ Success = $false; Reason = 'TX_REF_MISMATCH' }
    }

    if ($providerId -ne $TransactionId) {
        return @{ Success = $false; Reason = 'TRANSACTION_ID_MISMATCH' }
    }

    $timeline = Test-TimelineOrdering `
        -CheckoutRequestStartUtc ([string]$checkoutResult.Data.request_start_utc) `
        -CheckoutRequestEndUtc ([string]$checkoutResult.Data.request_end_utc) `
        -CheckoutOpenedUtc ([string]$checkoutResult.Data.checkout_opened_utc) `
        -PaymentCompletionObservedUtc ([string]$observeResult.Data.payment_completion_observed_utc) `
        -VerifyRequestStartUtc $requestStartUtc `
        -VerifyRequestEndUtc $requestEndUtc `
        -IsTestB ($TestLabel -eq 'B')
    if (-not $timeline.Valid) {
        return @{ Success = $false; Reason = $timeline.Reason }
    }

    $stage = [ordered]@{
        capture_session_id             = $CaptureSessionId
        test_label                     = $TestLabel
        action                          = 'Verify'
        endpoint                        = $uri
        tx_ref_sha256                   = $providerTxRefSha256
        transaction_id_sha256           = Get-Sha256Hex -Text $providerId
        tx_ref_hash_matches_checkout    = $true
        transaction_id_matches_request  = $true
        request_start_utc              = $requestStartUtc
        request_end_utc                = $requestEndUtc
        http_status                     = $httpResult.StatusCode
        raw_evidence_filename           = $rawFileName
        raw_response_sha256            = $rawResponseSha256
        provider_evidence_fields        = Get-AllowlistedEvidenceFields -Node $outcome.Parsed
        timeline_valid                   = $true
        collector_script_git_sha        = $CollectorScriptGitSha
        collector_script_content_sha256 = $CollectorScriptContentSha256
    }
    $stagePath = Join-Path $EvidenceRoot "stage-Verify-Test$TestLabel-$CaptureSessionId.json"
    $writeResult = New-ImmutableJsonFile -Path $stagePath -Content ($stage | ConvertTo-Json -Depth 12)
    if (-not $writeResult.Success) {
        return @{ Success = $false; Reason = $writeResult.Reason }
    }

    return @{ Success = $true; Reason = 'OK'; StagePath = $stagePath; RawPath = $rawPath }
}

function Invoke-FinalizeManifestOrchestration {
    [OutputType([hashtable])]
    param(
        [Parameter(Mandatory = $true)][ValidateSet('A', 'B')][string]$TestLabel,
        [Parameter(Mandatory = $true)][string]$CaptureSessionId,
        [Parameter(Mandatory = $true)][string]$EvidenceRoot,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$CollectorScriptGitSha,
        [Parameter(Mandatory = $true)][string]$CollectorScriptContentSha256,
        [Parameter(Mandatory = $true)][string]$PowerShellVersion,
        [Parameter(Mandatory = $true)][double]$MachineUtcOffsetMinutes
    )

    $checkoutResult = Get-StageCapture -EvidenceRoot $EvidenceRoot -ActionName 'CreateCheckout' -TestLabel $TestLabel -CaptureSessionId $CaptureSessionId
    if (-not $checkoutResult.Success) {
        return @{ Success = $false; Reason = "CHECKOUT_STAGE_$($checkoutResult.Reason)" }
    }
    $observeResult = Get-StageCapture -EvidenceRoot $EvidenceRoot -ActionName 'ObservePaymentSuccess' -TestLabel $TestLabel -CaptureSessionId $CaptureSessionId
    if (-not $observeResult.Success) {
        return @{ Success = $false; Reason = "OBSERVE_STAGE_$($observeResult.Reason)" }
    }
    $verifyResult = Get-StageCapture -EvidenceRoot $EvidenceRoot -ActionName 'Verify' -TestLabel $TestLabel -CaptureSessionId $CaptureSessionId
    if (-not $verifyResult.Success) {
        return @{ Success = $false; Reason = "VERIFY_STAGE_$($verifyResult.Reason)" }
    }

    # Cross-stage checks (item 4): Get-StageCapture already proved each
    # file's OWN capture_session_id/test_label match what was requested,
    # which transitively proves all three agree with EACH OTHER too. The
    # checks below are NOT already implied by that.
    if ($checkoutResult.Data.tx_ref_sha256 -ne $verifyResult.Data.tx_ref_sha256) {
        return @{ Success = $false; Reason = 'TX_REF_HASH_MISMATCH_ACROSS_STAGES' }
    }

    <#
    CORRECTED, this revision (Codex provenance-closure re-audit, Blocker 1):
    a sanitized stage can never exist without ITS OWN raw evidence file
    already having been written successfully at capture time (see
    Invoke-CreateCheckoutOrchestration / Invoke-VerifyOrchestration -- raw
    persistence failure aborts before the stage is ever written). But that
    guarantee is only as good as the file still being exactly what was
    persisted. FinalizeManifest is the ONE place that independently proves
    it, by reopening the exact session-bound raw files right now and
    re-hashing their CURRENT on-disk bytes -- never trusting the stage's
    own recorded hash as self-evidently still correct. Any of missing,
    duplicated (ambiguous which file is authoritative), unreadable, or a
    changed/substituted byte sequence fails closed here, before any
    manifest is written.
    #>
    $checkoutRaw = Get-RetainedRawBytes -EvidenceRoot $EvidenceRoot -ActionName 'CreateCheckout' -TestLabel $TestLabel -CaptureSessionId $CaptureSessionId
    if (-not $checkoutRaw.Success) {
        return @{ Success = $false; Reason = "CHECKOUT_RAW_$($checkoutRaw.Reason)" }
    }
    if ((Get-Sha256HexFromBytes -Bytes $checkoutRaw.Bytes) -ne [string]$checkoutResult.Data.raw_response_sha256) {
        return @{ Success = $false; Reason = 'CHECKOUT_RAW_HASH_MISMATCH' }
    }

    $verifyRaw = Get-RetainedRawBytes -EvidenceRoot $EvidenceRoot -ActionName 'Verify' -TestLabel $TestLabel -CaptureSessionId $CaptureSessionId
    if (-not $verifyRaw.Success) {
        return @{ Success = $false; Reason = "VERIFY_RAW_$($verifyRaw.Reason)" }
    }
    if ((Get-Sha256HexFromBytes -Bytes $verifyRaw.Bytes) -ne [string]$verifyResult.Data.raw_response_sha256) {
        return @{ Success = $false; Reason = 'VERIFY_RAW_HASH_MISMATCH' }
    }

    <#
    CORRECTED, this revision (Codex provenance-closure re-audit, Blocker 2):
    the OLD check here only proved the three stages agree WITH EACH OTHER
    (Select-Object -Unique .Count -eq 1) -- it never compared that common
    value against the CURRENTLY EXECUTING finalizer's own collector
    identity. That meant stages produced by collector version X could be
    finalized by a differently-versioned collector Y, and the manifest
    would still silently record whichever value happened to be common to
    the stages (or, worse, whatever the finalizer's own values were, never
    checked against the stages at all) -- neither of which proves the
    manifest names the version that ACTUALLY produced the evidence. The
    correct check is explicit three-way equality: every stage AND the
    current finalizer must agree, for content hash and Git SHA
    independently. Git SHA additionally may never be empty -- an
    undeterminable Git SHA is not a pass, it is a provenance gap.
    #>
    $contentHashes = @(
        [string]$checkoutResult.Data.collector_script_content_sha256,
        [string]$observeResult.Data.collector_script_content_sha256,
        [string]$verifyResult.Data.collector_script_content_sha256
    )
    $contentMismatch = $false
    foreach ($hash in $contentHashes) {
        if ([string]::IsNullOrEmpty($hash) -or $hash -ne $CollectorScriptContentSha256) {
            $contentMismatch = $true
        }
    }
    if ($contentMismatch) {
        return @{ Success = $false; Reason = 'COLLECTOR_CONTENT_VERSION_MISMATCH' }
    }

    $gitShas = @(
        [string]$checkoutResult.Data.collector_script_git_sha,
        [string]$observeResult.Data.collector_script_git_sha,
        [string]$verifyResult.Data.collector_script_git_sha
    )
    $gitShaMismatch = [string]::IsNullOrEmpty($CollectorScriptGitSha)
    foreach ($sha in $gitShas) {
        if ([string]::IsNullOrEmpty($sha) -or $sha -ne $CollectorScriptGitSha) {
            $gitShaMismatch = $true
        }
    }
    if ($gitShaMismatch) {
        return @{ Success = $false; Reason = 'COLLECTOR_GIT_VERSION_MISMATCH' }
    }

    $timeline = Test-TimelineOrdering `
        -CheckoutRequestStartUtc ([string]$checkoutResult.Data.request_start_utc) `
        -CheckoutRequestEndUtc ([string]$checkoutResult.Data.request_end_utc) `
        -CheckoutOpenedUtc ([string]$checkoutResult.Data.checkout_opened_utc) `
        -PaymentCompletionObservedUtc ([string]$observeResult.Data.payment_completion_observed_utc) `
        -VerifyRequestStartUtc ([string]$verifyResult.Data.request_start_utc) `
        -VerifyRequestEndUtc ([string]$verifyResult.Data.request_end_utc) `
        -IsTestB ($TestLabel -eq 'B')
    if (-not $timeline.Valid) {
        return @{ Success = $false; Reason = $timeline.Reason }
    }

    $manifest = New-EvidenceManifest `
        -CaptureSessionId $CaptureSessionId `
        -TestLabel $TestLabel `
        -TxRefSha256 ([string]$checkoutResult.Data.tx_ref_sha256) `
        -TransactionIdSha256 ([string]$verifyResult.Data.transaction_id_sha256) `
        -TestModeConfirmed $true `
        -ApiVersion 'v3' `
        -CheckoutEndpoint ([string]$checkoutResult.Data.endpoint) `
        -VerifyEndpoint ([string]$verifyResult.Data.endpoint) `
        -CheckoutRequestStartUtc ([string]$checkoutResult.Data.request_start_utc) `
        -CheckoutRequestEndUtc ([string]$checkoutResult.Data.request_end_utc) `
        -CheckoutOpenedUtc ([string]$checkoutResult.Data.checkout_opened_utc) `
        -PaymentCompletionObservedUtc ([string]$observeResult.Data.payment_completion_observed_utc) `
        -VerifyRequestStartUtc ([string]$verifyResult.Data.request_start_utc) `
        -VerifyRequestEndUtc ([string]$verifyResult.Data.request_end_utc) `
        -ElapsedSecondsSinceCheckoutOpened ([double]$observeResult.Data.elapsed_seconds_since_checkout_opened) `
        -TimelineValid $true `
        -ProviderEvidenceFields (@($checkoutResult.Data.provider_evidence_fields) + @($verifyResult.Data.provider_evidence_fields)) `
        -CheckoutRawResponseSha256 ([string]$checkoutResult.Data.raw_response_sha256) `
        -VerifyRawResponseSha256 ([string]$verifyResult.Data.raw_response_sha256) `
        -CheckoutRawEvidenceFilename ([string]$checkoutResult.Data.raw_evidence_filename) `
        -VerifyRawEvidenceFilename ([string]$verifyResult.Data.raw_evidence_filename) `
        -CollectorScriptGitSha $CollectorScriptGitSha `
        -CollectorScriptContentSha256 $CollectorScriptContentSha256 `
        -PowerShellVersion $PowerShellVersion `
        -MachineUtcOffsetMinutes $MachineUtcOffsetMinutes

    $manifestPath = Join-Path $EvidenceRoot "manifest-Test$TestLabel-$CaptureSessionId.json"
    $writeResult = New-ImmutableJsonFile -Path $manifestPath -Content ($manifest | ConvertTo-Json -Depth 12)
    if (-not $writeResult.Success) {
        return @{ Success = $false; Reason = $writeResult.Reason }
    }

    return @{ Success = $true; Reason = 'OK'; ManifestPath = $manifestPath }
}
