<#
.SYNOPSIS
  Pure, network-free, secret-free helper functions for the Ω3-CHECKOUT Phase 0
  Flutterwave evidence collector. Dot-sourced by both
  Invoke-FlutterwaveEvidenceCapture.ps1 (the real, network-calling tool) and
  tests/FlutterwaveEvidenceLib.Tests.ps1 (the focused test suite).

  Nothing in this file makes a network call, reads a secret, or writes a file.
  That separation is what makes every function here directly unit-testable
  with synthetic inputs, with no mocking of HTTP or credentials required.

  Hardened, this revision (Blockers 1/2, Highs 1/2 from Codex's collector
  re-audit):
    - REMOVED: ConvertTo-RedactedObject (a denylist that retained every
      unrecognized field by default -- structurally unable to keep pace with
      undocumented provider fields, and confirmed to miss Flutterwave's real
      `first_6digits`/`last_4digits` field names, which the denylist spelled
      differently). No function in this file, and no code path in the real
      collector, ever again returns "the whole response, minus some keys."
    - ADDED: Get-AllowlistedEvidenceFields -- a strict ALLOWLIST projector.
      It walks a parsed response and returns ONLY fields whose key name is
      exactly 'status'/'amount'/'currency', or looks like a timestamp field
      by name, with the source's full JSON path preserved. Everything else --
      named or not, known or not -- is discarded by construction, not by
      exclusion.
    - ADDED: session-binding primitives (capture session id is generated by
      the caller and threaded through every stage; this library only
      validates/hashes, it does not generate the session id itself since
      that must happen exactly once, at CreateCheckout, in the real script).
    - ADDED: Test-TimelineOrdering -- validates the full six-timestamp
      ordering constraint and the Test-B 600-second minimum, rejecting any
      malformed, non-UTC, or impossible timeline.
    - HARDENED: Test-IsTestModeKey now validates the documented Flutterwave
      TEST secret-key format (FLWSECK_TEST-<32 hex>-X), case-sensitive, fail-
      closed -- no longer a bare substring check.
#>

Set-StrictMode -Version Latest

function Get-UtcTimestamp {
    [OutputType([string])]
    param()
    return [DateTime]::UtcNow.ToString('o')
}

function Test-IsValidUtcTimestamp {
    <#
    Strictly validates that $Value is a parseable, round-trippable ISO-8601
    timestamp whose Kind is Utc. Used to reject malformed or non-UTC
    timestamps pulled from a stage file on disk (defense-in-depth: every
    timestamp in this tool is machine-generated via Get-UtcTimestamp, but a
    hand-edited or corrupted stage file must still be caught here, not
    silently trusted).
    #>
    [OutputType([bool])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowNull()]
        [AllowEmptyString()]
        [string]$Value
    )
    if ([string]::IsNullOrWhiteSpace($Value)) { return $false }
    try {
        $parsed = [DateTime]::Parse($Value, [System.Globalization.CultureInfo]::InvariantCulture, [System.Globalization.DateTimeStyles]::RoundtripKind)
    }
    catch {
        return $false
    }
    return ($parsed.Kind -eq [System.DateTimeKind]::Utc)
}

function Get-Sha256Hex {
    [OutputType([string])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowEmptyString()]
        [string]$Text
    )
    $sha256 = [System.Security.Cryptography.SHA256]::Create()
    try {
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($Text)
        $hashBytes = $sha256.ComputeHash($bytes)
        return ([System.BitConverter]::ToString($hashBytes)).Replace('-', '').ToLowerInvariant()
    }
    finally {
        $sha256.Dispose()
    }
}

function Test-IsTestModeKey {
    <#
    Fail-closed validation of Flutterwave's documented TEST secret-key
    format: FLWSECK_TEST-<32 hex characters>-X, case-sensitive prefix and
    suffix. A key that merely CONTAINS the substring "test" anywhere (e.g.
    in an unrelated comment, a mistyped live key, or an attacker-supplied
    string) is REJECTED -- only an exact, documented-shape match is accepted.
    This is a defense-in-depth backstop; the explicit human TEST-MODE-
    CONFIRMED prompt in the real collector is the primary control and is
    never removed or weakened by this check.
    #>
    [OutputType([bool])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowEmptyString()]
        [string]$KeyValue
    )
    if ([string]::IsNullOrWhiteSpace($KeyValue)) { return $false }
    return ($KeyValue -cmatch '^FLWSECK_TEST-[a-fA-F0-9]{32}-X$')
}

function Get-CaptureOutcome {
    <#
    Pure decision function: given an HTTP status code and a raw response
    body, decides whether this capture is usable evidence.
      - Reason 'NON_2XX'       : status code outside [200,299] -- abort.
      - Reason 'MALFORMED_JSON': status was 2xx but the body is empty,
                                  whitespace-only, or does not parse -- abort.
      - Reason 'OK'            : status was 2xx and the body parsed -- proceed.
    Never throws for a malformed body; malformed input is a normal, expected
    outcome this function reports, not an exceptional one.
    #>
    [OutputType([hashtable])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowNull()]
        [Nullable[int]]$StatusCode,

        [Parameter(Mandatory = $true)]
        [AllowNull()]
        [AllowEmptyString()]
        [string]$RawBody
    )

    if ($null -eq $StatusCode -or $StatusCode -lt 200 -or $StatusCode -ge 300) {
        return @{ Success = $false; Reason = 'NON_2XX'; Parsed = $null }
    }

    if ([string]::IsNullOrWhiteSpace($RawBody)) {
        return @{ Success = $false; Reason = 'MALFORMED_JSON'; Parsed = $null }
    }

    try {
        $parsed = $RawBody | ConvertFrom-Json -ErrorAction Stop
    }
    catch {
        return @{ Success = $false; Reason = 'MALFORMED_JSON'; Parsed = $null }
    }

    return @{ Success = $true; Reason = 'OK'; Parsed = $parsed }
}

# ---------------------------------------------------------------------------
# ALLOWLIST evidence projection (replaces the removed denylist redaction).
# ---------------------------------------------------------------------------

# A field is treated as timestamp-shaped by NAME (case-insensitive). This is
# deliberately a NAME-based allowlist, not a "does the value parse as a
# date" heuristic -- a numeric-string field like first_6digits ("123456")
# must never be mistaken for a timestamp, and name-based matching also means
# a field is either obviously a timestamp by its own name or it is dropped,
# with no ambiguous middle ground.
$script:TimestampKeyPattern = '(?i)(_at$|_date$|^date$|datetime|created|completed|settled|charged|processed|expire|expiry|^timestamp$|_time$)'

# The ONLY non-timestamp scalar key names ever allowed into shareable
# evidence, matched case-insensitively, anywhere in the tree.
$script:AllowlistedScalarKeys = @('status', 'amount', 'currency')

function Get-AllowlistedEvidenceFields {
    <#
    Walks a parsed JSON tree and returns a FLAT ARRAY of only the fields
    that pass the allowlist -- each entry is @{ path; key; value }, where
    `path` is the field's full JSON path (e.g. 'data.customer.created_at' or
    'data.events[2].created_at'), so provenance is preserved without ever
    reconstructing or returning the original nested object.

    Everything not explicitly allowed -- card/token fields, identifiers,
    contact details, device/IP fields, and any field this allowlist has
    never seen before -- is silently absent from the result. There is no
    "unless recognized as sensitive" branch: absence is the default.
    #>
    [OutputType([object[]])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowNull()]
        $Node,

        # Empty by default: paths are built purely from the REAL structure of
        # $Node (e.g. a response shaped { status, data: { created_at, ... } }
        # naturally yields paths 'status' and 'data.created_at'). Only pass a
        # non-empty prefix if $Node itself is already a sub-tree whose true
        # root path is known to the caller.
        [string]$PathPrefix = ''
    )

    $results = New-Object System.Collections.Generic.List[object]
    Add-AllowlistedFields -Node $Node -Path $PathPrefix -Results $results
    return , @($results.ToArray())
}

function Add-AllowlistedFields {
    param($Node, [string]$Path, $Results)

    if ($null -eq $Node) { return }

    if ($Node -is [System.Management.Automation.PSCustomObject]) {
        foreach ($prop in $Node.PSObject.Properties) {
            $childPath = if ([string]::IsNullOrEmpty($Path)) { $prop.Name } else { "$Path.$($prop.Name)" }
            $val = $prop.Value
            $lname = $prop.Name.ToLowerInvariant()

            $isContainer = ($val -is [System.Management.Automation.PSCustomObject]) -or
                           ($val -is [System.Collections.IEnumerable] -and -not ($val -is [string]))

            if ($isContainer) {
                Add-AllowlistedFields -Node $val -Path $childPath -Results $Results
            }
            elseif ($script:AllowlistedScalarKeys -contains $lname) {
                $Results.Add([PSCustomObject]@{ path = $childPath; key = $prop.Name; value = $val })
            }
            elseif ($val -is [string] -and $lname -match $script:TimestampKeyPattern) {
                $Results.Add([PSCustomObject]@{ path = $childPath; key = $prop.Name; value = $val })
            }
            # Every other field -- named or not -- is discarded here, by omission.
        }
    }
    elseif ($Node -is [System.Collections.IEnumerable] -and -not ($Node -is [string])) {
        $i = 0
        foreach ($item in $Node) {
            Add-AllowlistedFields -Node $item -Path "$Path[$i]" -Results $Results
            $i++
        }
    }
    # Bare scalars at the root (no key name) are never allowlisted -- the
    # allowlist is a NAME-based decision and a bare scalar has no name.
}

function Get-DataField {
    <#
    Targeted, non-recursive lookup of $Parsed.data.<FieldName> -- used to
    extract tx_ref and the transaction id from a real Flutterwave v3
    response shape ({ status, message, data: { id, tx_ref, ... } }).
    Deliberately NOT a recursive "find any key named X anywhere" search,
    which could silently grab an unrelated nested field of the same name
    (e.g. customer.id instead of data.id).
    #>
    [OutputType([string])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowNull()]
        $Parsed,

        [Parameter(Mandatory = $true)]
        [string]$FieldName
    )
    if ($null -eq $Parsed) { return $null }
    if (-not ($Parsed.PSObject.Properties.Match('data').Count -gt 0)) { return $null }
    $data = $Parsed.data
    if ($null -eq $data) { return $null }
    if (-not ($data.PSObject.Properties.Match($FieldName).Count -gt 0)) { return $null }
    $value = $data.$FieldName
    if ($null -eq $value) { return $null }
    return [string]$value
}

function Test-TimelineOrdering {
    <#
    Validates the full six-point capture timeline. Every timestamp must be a
    valid, round-trippable UTC ISO-8601 string, and they must be
    non-decreasing in this exact order:
      CheckoutRequestStartUtc <= CheckoutRequestEndUtc <= CheckoutOpenedUtc
        <= PaymentCompletionObservedUtc <= VerifyRequestStartUtc <= VerifyRequestEndUtc
    For a Test B capture, PaymentCompletionObservedUtc - CheckoutOpenedUtc
    must additionally be >= 600 seconds.
    Returns @{ Valid = [bool]; Reason = [string] } -- never throws on bad
    input; a malformed/non-UTC/out-of-order/too-fast timeline is a normal,
    reportable outcome, not an exception.
    #>
    [OutputType([hashtable])]
    param(
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$CheckoutRequestStartUtc,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$CheckoutRequestEndUtc,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$CheckoutOpenedUtc,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$PaymentCompletionObservedUtc,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$VerifyRequestStartUtc,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$VerifyRequestEndUtc,
        [Parameter(Mandatory = $true)][bool]$IsTestB
    )

    $labels = @('CheckoutRequestStartUtc', 'CheckoutRequestEndUtc', 'CheckoutOpenedUtc', 'PaymentCompletionObservedUtc', 'VerifyRequestStartUtc', 'VerifyRequestEndUtc')
    $values = @($CheckoutRequestStartUtc, $CheckoutRequestEndUtc, $CheckoutOpenedUtc, $PaymentCompletionObservedUtc, $VerifyRequestStartUtc, $VerifyRequestEndUtc)

    $parsed = New-Object System.Collections.Generic.List[DateTime]
    for ($i = 0; $i -lt $values.Count; $i++) {
        if (-not (Test-IsValidUtcTimestamp -Value $values[$i])) {
            return @{ Valid = $false; Reason = "MALFORMED_OR_NON_UTC:$($labels[$i])" }
        }
        $parsed.Add([DateTime]::Parse($values[$i], [System.Globalization.CultureInfo]::InvariantCulture, [System.Globalization.DateTimeStyles]::RoundtripKind))
    }

    for ($i = 0; $i -lt $parsed.Count - 1; $i++) {
        if ($parsed[$i] -gt $parsed[$i + 1]) {
            return @{ Valid = $false; Reason = "ORDER_VIOLATION:$($labels[$i])>$($labels[$i + 1])" }
        }
    }

    if ($IsTestB) {
        $elapsedSeconds = ($parsed[3] - $parsed[2]).TotalSeconds
        if ($elapsedSeconds -lt 600) {
            return @{ Valid = $false; Reason = "TEST_B_MINIMUM_NOT_MET:$([math]::Round($elapsedSeconds, 3))s" }
        }
    }

    return @{ Valid = $true; Reason = 'OK' }
}

function Get-StageCapture {
    <#
    Loads exactly one stage-capture file for a given (ActionName, TestLabel,
    CaptureSessionId) triple, by EXACT filename match -- never "the newest
    file matching a prefix." This is the function that structurally replaces
    the earlier collector's "select the latest stage-* file" logic; there is
    no sorting by timestamp anywhere in this function or its caller.

    Returns @{ Success; Reason; Data }:
      Reason 'MISSING'          -- zero files match the exact filename.
      Reason 'DUPLICATE'        -- more than one file matches (should be
                                    structurally impossible given an exact
                                    filename, but checked explicitly rather
                                    than assumed).
      Reason 'SESSION_MISMATCH' -- the file's OWN capture_session_id field
                                    disagrees with the filename/request.
      Reason 'LABEL_MISMATCH'   -- the file's OWN test_label field disagrees
                                    with the filename/request.
      Reason 'OK'               -- exactly one matching, internally-
                                    consistent file was found; Data holds its
                                    parsed content.
    Reads a file from disk (EvidenceRoot); makes no network call, touches no
    secret. Directly testable against a temp directory of synthetic files.
    #>
    [OutputType([hashtable])]
    param(
        [Parameter(Mandatory = $true)][string]$EvidenceRoot,
        [Parameter(Mandatory = $true)][string]$ActionName,
        [Parameter(Mandatory = $true)][string]$TestLabel,
        [Parameter(Mandatory = $true)][string]$CaptureSessionId
    )

    $pattern = "stage-$ActionName-Test$TestLabel-$CaptureSessionId.json"
    $found = @(Get-ChildItem -Path $EvidenceRoot -Filter $pattern -ErrorAction SilentlyContinue)

    if ($found.Count -eq 0) {
        return @{ Success = $false; Reason = 'MISSING'; Data = $null }
    }
    if ($found.Count -gt 1) {
        return @{ Success = $false; Reason = 'DUPLICATE'; Data = $null }
    }

    $data = Get-Content -Path $found[0].FullName -Raw | ConvertFrom-Json

    if ($data.capture_session_id -ne $CaptureSessionId) {
        return @{ Success = $false; Reason = 'SESSION_MISMATCH'; Data = $null }
    }
    if ($data.test_label -ne $TestLabel) {
        return @{ Success = $false; Reason = 'LABEL_MISMATCH'; Data = $null }
    }

    return @{ Success = $true; Reason = 'OK'; Data = $data }
}

function Test-IsSafeFlagResult {
    <#
    A disposable, executable PowerShell mirror of the STRICT discriminated-
    union contract pinned in IMPLEMENTATION_CONDITIONS_PINNED.md (Condition 2
    of that document). Calls no network, touches no checkout logic -- exists
    solely to prove, executably, that the pinned specification is internally
    consistent.

    Accepts EXACTLY:
      { flagged: true }                                   -- exactly one key
      { flagged: false, reason: 'ALREADY_FLAGGED' }        -- exactly two keys
      { flagged: false, reason: 'INTENT_NOT_PENDING' }     -- exactly two keys
    Rejects everything else, including an otherwise-valid shape carrying any
    additional property.
    #>
    [OutputType([bool])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowNull()]
        $FlagResult
    )

    if ($null -eq $FlagResult) { return $false }
    if ($FlagResult -is [System.Array]) { return $false }
    if ($FlagResult -is [string] -or $FlagResult -is [int] -or $FlagResult -is [double] -or $FlagResult -is [bool]) {
        return $false
    }
    if (-not ($FlagResult -is [System.Management.Automation.PSCustomObject] -or $FlagResult -is [hashtable])) {
        return $false
    }

    if ($FlagResult -is [hashtable]) {
        $keys = @($FlagResult.Keys | Sort-Object)
        $get = { param($k) $FlagResult[$k] }
    }
    else {
        $keys = @($FlagResult.PSObject.Properties | ForEach-Object { $_.Name } | Sort-Object)
        $get = { param($k) $FlagResult.$k }
    }

    if ($keys.Count -eq 1 -and $keys[0] -eq 'flagged') {
        $flaggedValue = & $get 'flagged'
        if ($flaggedValue -is [bool] -and $flaggedValue -eq $true) { return $true }
        return $false
    }

    if ($keys.Count -eq 2 -and $keys[0] -eq 'flagged' -and $keys[1] -eq 'reason') {
        $flaggedValue = & $get 'flagged'
        $reasonValue = & $get 'reason'
        if ($flaggedValue -is [bool] -and $flaggedValue -eq $false -and $reasonValue -is [string]) {
            if ($reasonValue -eq 'ALREADY_FLAGGED' -or $reasonValue -eq 'INTENT_NOT_PENDING') {
                return $true
            }
        }
        return $false
    }

    return $false
}

function New-EvidenceManifest {
    <#
    Builds the final provenance manifest object binding together every
    session-correlated field. Pure -- takes already-computed, already-
    validated inputs, writes nothing, makes no network call. Contains NO
    complete provider response, redacted or otherwise -- only the allow-
    listed evidence fields, hashes, and collector-generated provenance.
    #>
    [OutputType([System.Collections.Specialized.OrderedDictionary])]
    param(
        [Parameter(Mandatory = $true)][string]$CaptureSessionId,
        [Parameter(Mandatory = $true)][ValidateSet('A', 'B')][string]$TestLabel,
        [Parameter(Mandatory = $true)][string]$TxRefSha256,
        [Parameter(Mandatory = $true)][string]$TransactionIdSha256,
        [Parameter(Mandatory = $true)][bool]$TestModeConfirmed,
        [Parameter(Mandatory = $true)][string]$ApiVersion,
        [Parameter(Mandatory = $true)][string]$CheckoutEndpoint,
        [Parameter(Mandatory = $true)][string]$VerifyEndpoint,
        [Parameter(Mandatory = $true)][string]$CheckoutRequestStartUtc,
        [Parameter(Mandatory = $true)][string]$CheckoutRequestEndUtc,
        [Parameter(Mandatory = $true)][string]$CheckoutOpenedUtc,
        [Parameter(Mandatory = $true)][string]$PaymentCompletionObservedUtc,
        [Parameter(Mandatory = $true)][string]$VerifyRequestStartUtc,
        [Parameter(Mandatory = $true)][string]$VerifyRequestEndUtc,
        [Parameter(Mandatory = $true)][double]$ElapsedSecondsSinceCheckoutOpened,
        [Parameter(Mandatory = $true)][bool]$TimelineValid,
        [Parameter(Mandatory = $true)][object[]]$ProviderEvidenceFields,
        [Parameter(Mandatory = $true)][string]$CheckoutRawResponseSha256,
        [Parameter(Mandatory = $true)][string]$VerifyRawResponseSha256,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$CollectorScriptGitSha,
        [Parameter(Mandatory = $true)][string]$CollectorScriptContentSha256,
        [Parameter(Mandatory = $true)][string]$PowerShellVersion,
        [Parameter(Mandatory = $true)][double]$MachineUtcOffsetMinutes
    )

    return [ordered]@{
        capture_session_id                = $CaptureSessionId
        test_label                        = $TestLabel
        tx_ref_sha256                      = $TxRefSha256
        transaction_id_sha256              = $TransactionIdSha256
        test_mode_confirmed                = $TestModeConfirmed
        api_version                        = $ApiVersion
        checkout_endpoint                  = $CheckoutEndpoint
        verify_endpoint                    = $VerifyEndpoint
        checkout_request_start_utc         = $CheckoutRequestStartUtc
        checkout_request_end_utc           = $CheckoutRequestEndUtc
        checkout_opened_utc                = $CheckoutOpenedUtc
        payment_completion_observed_utc    = $PaymentCompletionObservedUtc
        verify_request_start_utc           = $VerifyRequestStartUtc
        verify_request_end_utc             = $VerifyRequestEndUtc
        elapsed_seconds_since_checkout_opened = $ElapsedSecondsSinceCheckoutOpened
        timeline_valid                     = $TimelineValid
        provider_evidence_fields           = $ProviderEvidenceFields
        checkout_raw_response_sha256       = $CheckoutRawResponseSha256
        verify_raw_response_sha256         = $VerifyRawResponseSha256
        collector_script_git_sha           = $CollectorScriptGitSha
        collector_script_content_sha256    = $CollectorScriptContentSha256
        powershell_version                 = $PowerShellVersion
        machine_utc_offset_minutes         = $MachineUtcOffsetMinutes
    }
}
