#!/usr/bin/env node
// Real-PostgreSQL proof of named-user billing suspension, invitation reservations and the official Reporting Pack
// (20260925110000_named_user_billing_suspension_and_invitation_lifecycle.sql, 20260925120000_reporting_pack_issuance_binding.sql).
//
// P-03  active named users <= included + purchased seats after downgrade, expiry (with and without a licence write),
//       planned reduction, restoration and concurrent reactivation; suspended people keep their memberships and
//       history, get exactly an outsider's denial (authority, RLS, RPCs, Edge authority), and are reactivated only by
//       the account holder's explicit, version-checked selection; the service role cannot bypass it; each redefined
//       access function differs from its previous definition by exactly the one activity conjunct.
// P-04  pending invitations expire, can be cancelled or released, are never double-reserved, cannot be accepted
//       once invalid, and stay within capacity under concurrency.
// P-05  the official Reporting Pack is generated by the DATABASE from the saved output (no caller supplies bytes or
//       a hash); issuances are bound, short-lived, single-use, re-authorised when sealed, verifiable and audited.
//
//   DB_PROOF_MODULES_DIR=<dir whose node_modules has pg + embedded-postgres> node scripts/db-proof/billingSuspension.mjs
//
// It reads no Supabase credential and refuses every non-loopback host and the production project reference.

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath, pathToFileURL } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, "../..");
const PRODUCTION_REF = "bvyivmmfjejbmqoydezk";
const PG_CRON_FILE = "20260810044930_fcf7b034-7dc7-445d-a77d-99be66c3c4f4.sql";
const MIGRATION = "20260925110000_named_user_billing_suspension_and_invitation_lifecycle.sql";
const MODE = process.env.DB_PROOF_MODE ?? "embedded";
const MODULES_DIR = process.env.DB_PROOF_MODULES_DIR;
const CONCURRENCY = 12;

const req = createRequire(MODULES_DIR ? path.join(path.resolve(MODULES_DIR), "noop.js") : import.meta.url);
const { Pool, Client } = req("pg");

const results = [];
let currentGroup = "";
const group = (n) => { currentGroup = n; console.log(`\n== ${n}`); };
function record(name, ok, detail = "") {
  results.push({ group: currentGroup, name, ok });
  console.log(`  ${ok ? "PASS" : "FAIL"}  ${name}${ok || !detail ? "" : `\n        ${detail}`}`);
}
async function check(name, fn) {
  try {
    const r = await fn();
    record(name, r === true, r === true ? "" : `assertion returned ${JSON.stringify(r)}`);
  } catch (e) {
    record(name, false, String(e?.message ?? e).split("\n")[0]);
  }
}

let pool;
let admin;
let embeddedServer = null;
let embeddedDir = null;

function assertLocal(u) {
  const url = new URL(u);
  if (!["localhost", "127.0.0.1", "::1", "[::1]"].includes(url.hostname)) throw new Error(`REFUSED: ${url.hostname} is not loopback`);
  if (u.includes(PRODUCTION_REF)) throw new Error("REFUSED: production project reference");
}
async function startDatabase() {
  if (MODE === "external") { assertLocal(process.env.DB_PROOF_CONN); return process.env.DB_PROOF_CONN; }
  const modDir = MODULES_DIR ? path.resolve(MODULES_DIR) : REPO;
  const { default: EmbeddedPostgres } = await import(pathToFileURL(path.join(modDir, "node_modules/embedded-postgres/dist/index.js")).href);
  embeddedDir = fs.mkdtempSync(path.join(os.tmpdir(), "cfoclose-billing-suspension-proof-"));
  const port = 54000 + Math.floor(Math.random() * 900);
  embeddedServer = new EmbeddedPostgres({ databaseDir: path.join(embeddedDir, "data"), user: "postgres", password: "postgres", port, persistent: false, initdbFlags: ["--encoding=UTF8", "--locale=C"], onLog: () => {}, onError: () => {} });
  await embeddedServer.initialise();
  await embeddedServer.start();
  const boot = new Client({ host: "localhost", port, user: "postgres", password: "postgres", database: "postgres" });
  await boot.connect(); await boot.query("CREATE DATABASE billing_suspension_proof"); await boot.end();
  return `postgres://postgres:postgres@localhost:${port}/billing_suspension_proof`;
}
async function stopDatabase() {
  try { await pool?.end(); } catch { /* ignore */ }
  try { await admin?.end(); } catch { /* ignore */ }
  if (embeddedServer) { try { await embeddedServer.stop(); } catch { /* ignore */ } }
  if (embeddedDir) { try { fs.rmSync(embeddedDir, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 }); } catch { /* temp dir cleanup is best effort */ } }
}

const migrationFiles = () => fs.readdirSync(path.join(REPO, "supabase/migrations")).filter((f) => f.endsWith(".sql")).sort();
async function applyMigration(f) {
  let text = fs.readFileSync(path.join(REPO, "supabase/migrations", f), "utf8");
  if (f === PG_CRON_FILE) text = text.split("\n").slice(0, text.split("\n").findIndex((l) => l.includes("CREATE EXTENSION IF NOT EXISTS pg_cron"))).join("\n");
  try { await admin.query(text); } catch (e) { throw new Error(`migration ${f} failed: ${String(e.message).split("\n")[0]}`); }
}
function splitStatements(sql) {
  const out = []; let cur = ""; let i = 0;
  while (i < sql.length) {
    const c = sql[i], n = sql[i + 1];
    if (c === "-" && n === "-") { const e = sql.indexOf("\n", i); const j = e < 0 ? sql.length : e; cur += sql.slice(i, j); i = j; continue; }
    if (c === "/" && n === "*") { const e = sql.indexOf("*/", i + 2); const j = e < 0 ? sql.length : e + 2; cur += sql.slice(i, j); i = j; continue; }
    if (c === "'" || c === '"') { let j = i + 1; while (j < sql.length) { if (sql[j] === c) { if (sql[j + 1] === c) { j += 2; continue; } break; } j++; } cur += sql.slice(i, j + 1); i = j + 1; continue; }
    if (c === "$") { const m = /^\$[A-Za-z_]*\$/.exec(sql.slice(i)); if (m) { const e = sql.indexOf(m[0], i + m[0].length); const j = e < 0 ? sql.length : e + m[0].length; cur += sql.slice(i, j); i = j; continue; } }
    if (c === ";") { if (cur.replace(/--[^\n]*|\/\*[\s\S]*?\*\//g, "").trim()) out.push(cur.trim()); cur = ""; i++; continue; }
    cur += c; i++;
  }
  if (cur.replace(/--[^\n]*|\/\*[\s\S]*?\*\//g, "").trim()) out.push(cur.trim());
  return out;
}
const FINGERPRINT_SQL = `SELECT md5(string_agg(x, '|' ORDER BY x)) AS fp FROM (
  SELECT 'c:'||table_name||'.'||column_name||':'||data_type||':'||coalesce(column_default,'')||is_nullable AS x FROM information_schema.columns WHERE table_schema='public'
  UNION ALL SELECT 'r:'||c.relname||c.relkind::text FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public'
  UNION ALL SELECT 'f:'||p.oid::regprocedure::text||md5(pg_get_functiondef(p.oid)) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.prokind='f'
  UNION ALL SELECT 't:'||tgname||':'||tgrelid::regclass::text FROM pg_trigger WHERE NOT tgisinternal
  UNION ALL SELECT 'k:'||conname||':'||conrelid::regclass::text||':'||pg_get_constraintdef(oid) FROM pg_constraint WHERE connamespace='public'::regnamespace
  UNION ALL SELECT 'd:'||md5(coalesce((SELECT string_agg(to_jsonb(p)::text, ',' ORDER BY p.id) FROM public.commercial_plans p), '')
                          || coalesce((SELECT string_agg(to_jsonb(o)::text, ',' ORDER BY o.id) FROM public.commercial_offers o), '')
                          || coalesce((SELECT string_agg(to_jsonb(e)::text, ',' ORDER BY e.id) FROM public.entitlement_overrides e), ''))
) s`;
const fingerprint = async () => (await admin.query(FINGERPRINT_SQL)).rows[0].fp;

async function asCaller(caller, fn) {
  const c = await pool.connect();
  try {
    await c.query("BEGIN");
    if (caller.kind === "anon") {
      await c.query("SET LOCAL ROLE anon");
      await c.query("SELECT set_config('request.jwt.claim.role','anon',true), set_config('request.jwt.claim.sub','',true)");
    } else if (caller.kind === "service") {
      await c.query("SET LOCAL ROLE service_role");
      await c.query("SELECT set_config('request.jwt.claim.role','service_role',true), set_config('request.jwt.claim.sub','',true)");
    } else {
      await c.query("SET LOCAL ROLE authenticated");
      await c.query("SELECT set_config('request.jwt.claim.role','authenticated',true), set_config('request.jwt.claim.sub',$1,true)", [caller.uid]);
    }
    const out = await fn(c);
    await c.query("COMMIT");
    return out;
  } catch (e) {
    try { await c.query("ROLLBACK"); } catch { /* ignore */ }
    throw e;
  } finally { c.release(); }
}
const user = (uid) => ({ kind: "user", uid });
const ANON = { kind: "anon" };
const SERVICE = { kind: "service" };
const q = (caller, sql, params) => asCaller(caller, async (c) => (await c.query(sql, params)).rows);
const one = async (caller, sql, params) => (await q(caller, sql, params))[0];
const uuid = () => globalThis.crypto.randomUUID();
const count = async (sql, params = []) => Number((await admin.query(sql, params)).rows[0].n);
const codeOf = async (fn) => { try { await fn(); return "ok"; } catch (e) { return e.code; } };
const errOf = async (fn) => { try { await fn(); return null; } catch (e) { return e; } };

// The 19 access functions 20260925110000 redefines with one added conjunct each (see the migration's section 5).
const PATCHED = [
  "assert_engagement_write_authority(uuid)", "financial_statements_workspace_access(uuid)", "fs_actor_member_id(uuid)",
  "get_engagement_setup_state(uuid)", "get_member_company_ids()", "get_workspace_access(uuid)",
  "hesabu_write_validation(uuid,uuid,integer,text,integer,integer,integer,integer,numeric,numeric,numeric,uuid,text,jsonb)",
  "intake_financial_statement_document(uuid,integer,uuid,text,text,bigint,text,text,text)", "list_shared_workspaces()",
  "maono_write_board_pack(uuid,uuid,text,text,jsonb,text,text,integer)", "open_engagement_with_scope(uuid,integer,text[],text)",
  "record_engagement_data_start(uuid,text,text)", "resolve_account_review_batch(uuid,uuid,uuid,jsonb)", "safisha_recon_visible(uuid)",
  "set_company_filing_jurisdiction(uuid,text)", "tbu_can_view_workspace_audit(uuid)", "tbu_resolve_processing_actor(uuid,uuid)",
  "workspace_authority_basis(uuid,uuid,text)",
  "xbrl_write_instance(uuid,uuid,integer,text,text,text,text,text,integer,boolean,integer,integer,integer,uuid,text,jsonb)",
];
const defOf = async (sig) => (await admin.query("SELECT pg_get_functiondef($1::regprocedure) d", [`public.${sig}`])).rows[0].d;
// Line endings are normalised (some previous definitions came from CRLF migration files); nothing else is.
const stripPredicate = (d) => d.replace(/\r/g, "").replace(/\s*AND\s+public\.named_user_access_active\([^()]*\)/g, "");

async function main() {
  const url = await startDatabase();
  admin = new Client({ connectionString: url });
  await admin.connect();
  pool = new Pool({ connectionString: url, max: CONCURRENCY + 8 });
  await admin.query(fs.readFileSync(path.join(REPO, "scripts/db-contract-tests/00_bootstrap_roles_and_shims.sql"), "utf8"));
  await admin.query(`GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO anon, authenticated, service_role;`);

  const files = migrationFiles();
  const cut = files.indexOf(MIGRATION);
  const before = {};
  group("Migration — applies over every earlier migration; each access function changes by exactly one conjunct");
  await check(`every migration before ${MIGRATION} applies`, async () => {
    if (cut < 0) return "migration not found";
    for (const f of files.slice(0, cut)) await applyMigration(f);
    for (const sig of PATCHED) before[sig] = await defOf(sig);
    return true;
  });
  const after110 = {};
  await check(`${MIGRATION} and every later migration apply`, async () => {
    await applyMigration(MIGRATION);
    // Captured before the later migrations (20260925140000 replaces title checks in some of these with capability checks).
    for (const sig of PATCHED) after110[sig] = await defOf(sig);
    for (const f of files.slice(cut + 1)) await applyMigration(f);
    return true;
  });
  await check("each of the 19 redefined access functions equals its previous definition once the single activity conjunct is removed (no other logic changed)", async () => {
    const bad = [];
    for (const sig of PATCHED) {
      const now = after110[sig];
      const added = (now.match(/public\.named_user_access_active\(/g) ?? []).length;
      if (added < 1 || stripPredicate(now) !== before[sig].replace(/\r/g, "")) bad.push(`${sig}:${added}`);
    }
    return bad.length === 0 ? true : bad.join(" | ");
  });
  await check("a second application is refused before any change (55000)", async () => (await codeOf(() => applyMigration(MIGRATION))) === "55000"
    || (await errOf(() => admin.query(fs.readFileSync(path.join(REPO, "supabase/migrations", MIGRATION), "utf8"))))?.code === "55000");

  // ── Fixtures ──────────────────────────────────────────────────────────────────────────────
  const mkUser = async (label = "u") => { const id = uuid(); await admin.query("INSERT INTO auth.users (id,email) VALUES ($1,$2)", [id, `${label}-${id}@example.test`]); return id; };
  const U = { admin: await mkUser("admin"), outsider: await mkUser("outsider") };
  await admin.query("INSERT INTO public.commercial_admins (user_id) VALUES ($1)", [U.admin]);
  const product = (await admin.query("SELECT id FROM public.commercial_products WHERE code='CFOCLOSE'")).rows[0].id;
  const planId = async (code) => (await admin.query("SELECT id FROM public.commercial_plans WHERE product_id=$1 AND code=$2", [product, code])).rows[0].id;
  const account = async (planCode, seats = 0) => {
    const uid = await mkUser("acct");
    let lic = null;
    if (planCode) {
      const bc = (await admin.query("INSERT INTO public.billing_customers (owner_user_id, product_id) VALUES ($1,$2) RETURNING id", [uid, product])).rows[0].id;
      const id = (await admin.query(`INSERT INTO public.commercial_licences (billing_customer_id, plan_id, status, source, effective_start, additional_seats)
        VALUES ($1,$2,'ACTIVE','ADMIN_GRANT',now() - interval '1 day',$3) RETURNING id`, [bc, await planId(planCode), seats])).rows[0].id;
      lic = { bc, id };
    }
    const co = (await admin.query("INSERT INTO public.companies (user_id,name) VALUES ($1,'Seat Co') RETURNING id", [uid])).rows[0].id;
    if (!lic) lic = { bc: (await admin.query("SELECT id FROM public.billing_customers WHERE owner_user_id=$1", [uid])).rows[0].id, id: null };
    return { uid, co, lic };
  };
  const addActive = (acct, co, who, role = "preparer") => q(user(acct), "INSERT INTO public.firm_members (company_id,user_id,role,accepted_at) VALUES ($1,$2,$3,now()) RETURNING id", [co, who, role]);
  const invite = (acct, co, who) => q(user(acct), "INSERT INTO public.firm_members (company_id,user_id,role,accepted_at) VALUES ($1,$2,'preparer',NULL) RETURNING id", [co, who]);
  const grantTo = (acct, co, who, cap = "manage_source_files") => one(user(acct), "SELECT * FROM public.grant_workspace_capability($1,$2,$3)", [co, who, cap]);
  const roster = async (acct) => (await one(user(acct), "SELECT public.get_named_user_roster() r")).r;
  const choose = async (acct, keep, version) => (await one(user(acct), "SELECT public.choose_active_named_users($1::uuid[], $2) r", [keep, version])).r;
  const prepare = async (bc, future, keep, version, caller = U.admin) => (await one(user(caller), "SELECT public.admin_prepare_planned_reduction($1,$2,$3::uuid[],$4,'customer instruction') r", [bc, future, keep, version])).r;
  const setSeats = (licId, n) => one(user(U.admin), "SELECT public.admin_set_licence_additional_seats($1,$2,'seats changed') r", [licId, n]);
  const accept = async (who) => (await one(user(who), "SELECT public.accept_workspace_invitations() r")).r;
  const authz = async (who, co, cap = "COMPARATIVE_REPORTING") => (await one(user(who), "SELECT public.authorize_paid_action($1,$2) r", [co, cap])).r;
  const activeOf = async (acct) => (await admin.query(`SELECT array_agg(u.named_user_id::text ORDER BY u.named_user_id) a FROM public._account_named_users($1,false) u
      WHERE public._account_named_user_access_active($1, u.named_user_id)`, [acct])).rows[0].a ?? [];
  const allowedOf = async (acct) => (await admin.query("SELECT public._seat_capacity_for_account($1) c", [acct])).rows[0].c;
  const invariant = async (acct) => {
    const a = (await activeOf(acct)).length; const c = await allowedOf(acct);
    return c.determined ? a <= c.allowed_named_users : a === 1;
  };
  const openSuspensions = (acct) => count("SELECT count(*) n FROM public.named_user_billing_suspensions WHERE account_user_id=$1 AND lifted_at IS NULL", [acct]);
  const auditSnapshot = async () => (await admin.query(`SELECT
      coalesce((SELECT jsonb_agg(to_jsonb(b) ORDER BY b.id) FROM public.billing_audit_events b), '[]') ||
      coalesce((SELECT jsonb_agg(to_jsonb(g) ORDER BY g.id) FROM public.workspace_capability_grant_events g), '[]') a`)).rows[0].a;
  const auditBefore = await auditSnapshot();

  group("P-03 — the active-seat invariant after downgrade, expiry, reduction and restoration; memberships and history kept");
  let firm;
  const firmPeople = [];
  await check("Firm with 10 active named users downgrades to Free: exactly the account holder stays active; the nine memberships stay present, billing-suspended", async () => {
    firm = await account("FIRM", 9);
    for (let i = 0; i < 9; i++) { const p = await mkUser("firm"); firmPeople.push(p); await addActive(firm.uid, firm.co, p); }
    const activeBefore = (await activeOf(firm.uid)).length;
    const rowsBefore = (await admin.query("SELECT id, user_id, role, accepted_at FROM public.firm_members WHERE company_id=$1 ORDER BY id", [firm.co])).rows;
    await admin.query("UPDATE public.commercial_licences SET plan_id=$1 WHERE id=$2", [await planId("FREE"), firm.lic.id]);
    const rowsAfter = (await admin.query("SELECT id, user_id, role, accepted_at FROM public.firm_members WHERE company_id=$1 ORDER BY id", [firm.co])).rows;
    const active = await activeOf(firm.uid);
    const reasons = (await admin.query("SELECT DISTINCT reason FROM public.named_user_billing_suspensions WHERE account_user_id=$1", [firm.uid])).rows.map((r) => r.reason);
    return activeBefore === 10 && active.length === 1 && active[0] === firm.uid && (await openSuspensions(firm.uid)) === 9
      && JSON.stringify(rowsBefore) === JSON.stringify(rowsAfter) && rowsAfter.length === 10 && JSON.stringify(reasons) === '["ENTITLEMENT_LOST"]'
      && (await invariant(firm.uid)) ? true : JSON.stringify({ activeBefore, active: active.length, susp: await openSuspensions(firm.uid), reasons });
  });
  await check("restoring capacity reactivates NO ONE by itself; restoring one seat permits exactly one explicitly selected reactivation", async () => {
    await admin.query("UPDATE public.commercial_licences SET plan_id=$1, additional_seats=1 WHERE id=$2", [await planId("PRACTICE"), firm.lic.id]);
    const afterRestore = (await activeOf(firm.uid)).length;
    const r = await roster(firm.uid);
    const two = await choose(firm.uid, [firmPeople[0], firmPeople[1]], r.roster_version);
    const oneSel = await choose(firm.uid, [firmPeople[0]], r.roster_version);
    const active = await activeOf(firm.uid);
    return afterRestore === 1 && two.outcome === "selection_exceeds_allowance" && oneSel.outcome === "applied"
      && active.length === 2 && active.includes(firmPeople[0]) && (await openSuspensions(firm.uid)) === 8 && (await invariant(firm.uid))
      ? true : JSON.stringify({ afterRestore, two, oneSel, active });
  });
  await check("expiry (time) is enforced the instant it passes, with no job: the live predicate locks out everyone but the account holder, who keeps read access (new work needs a plan)", async () => {
    const a = await account("PRACTICE", 2);
    const p1 = await mkUser("e"), p2 = await mkUser("e");
    await addActive(a.uid, a.co, p1); await addActive(a.uid, a.co, p2);
    // Simulate time passing without any write to the licence (no trigger fires).
    await admin.query("BEGIN"); await admin.query("SET LOCAL session_replication_role = replica");
    await admin.query("UPDATE public.commercial_licences SET effective_end = now() - interval '1 second', effective_start = now() - interval '2 days' WHERE id=$1", [a.lic.id]);
    await admin.query("COMMIT");
    const denied = (await authz(p1, a.co)).code === "WORKSPACE_ACCESS_DENIED" && (await authz(p2, a.co)).code === "WORKSPACE_ACCESS_DENIED";
    // No free plan (20260925130000): the holder keeps workspace access (existing data stays readable) but no capability without a plan.
    const holder = (await authz(a.uid, a.co)).code === "ENTITLEMENT_REQUIRED";
    return denied && holder && (await activeOf(a.uid)).length === 1 && (await invariant(a.uid));
  });
  let practice;
  const pp = [];
  await check("Practice with four active users, planned reduction to one additional seat: the chosen person stays active; the others are suspended (PLANNED_REDUCTION)", async () => {
    practice = await account("PRACTICE", 3);
    for (let i = 0; i < 3; i++) { const p = await mkUser("p"); pp.push(p); await addActive(practice.uid, practice.co, p); }
    const unplannedRefused = (await errOf(() => setSeats(practice.lic.id, 1)))?.code;
    const r = await roster(practice.uid);
    const applied = await prepare(practice.lic.bc, 2, [pp[1]], r.roster_version);
    await setSeats(practice.lic.id, 1);
    const active = await activeOf(practice.uid);
    const reasons = (await admin.query("SELECT DISTINCT reason FROM public.named_user_billing_suspensions WHERE account_user_id=$1 AND lifted_at IS NULL", [practice.uid])).rows.map((x) => x.reason);
    return unplannedRefused === "22023" && applied.outcome === "applied" && active.length === 2 && active.includes(pp[1]) && active.includes(practice.uid)
      && JSON.stringify(reasons) === '["PLANNED_REDUCTION"]' && (await invariant(practice.uid)) ? true : JSON.stringify({ unplannedRefused, applied, active, reasons });
  });
  await check("a planned selection is refused when missing, invalid, stale, over the future allowance, or not from a commercial admin", async () => {
    const r = await roster(practice.uid);
    const missing = await prepare(practice.lic.bc, 2, null, r.roster_version);
    const invalid = await prepare(practice.lic.bc, 2, [uuid()], r.roster_version);
    const holderInKeep = await prepare(practice.lic.bc, 2, [practice.uid], r.roster_version);
    const stale = await prepare(practice.lic.bc, 2, [pp[1]], "0".repeat(32));
    const over = await prepare(practice.lic.bc, 2, [pp[0], pp[1]], r.roster_version);
    const notAdmin = await codeOf(() => prepare(practice.lic.bc, 2, [pp[1]], r.roster_version, practice.uid));
    return missing.outcome === "selection_required" && invalid.outcome === "invalid_selection" && holderInKeep.outcome === "invalid_selection"
      && stale.outcome === "stale_selection" && over.outcome === "selection_exceeds_allowance" && notAdmin === "42501"
      ? true : JSON.stringify({ missing, invalid, holderInKeep, stale, over, notAdmin });
  });
  await check(`concurrent reactivations from the same roster cannot exceed the allowance: of ${CONCURRENCY} simultaneous selections, exactly one applies; the rest are stale`, async () => {
    const r = await roster(practice.uid); // allowance 2: holder + pp[1]; pp[0], pp[2] suspended
    await choose(practice.uid, [], r.roster_version); // free the one seat: nobody but the holder active
    const r2 = await roster(practice.uid);
    const picks = Array.from({ length: CONCURRENCY }, (_, i) => [pp[i % 3]]);
    const out = await Promise.all(picks.map((k) => choose(practice.uid, k, r2.roster_version).catch((e) => ({ outcome: e.code }))));
    return out.filter((o) => o.outcome === "applied").length === 1 && out.filter((o) => o.outcome === "stale_selection").length === CONCURRENCY - 1
      && (await activeOf(practice.uid)).length === 2 && (await invariant(practice.uid)) ? true : JSON.stringify(out.map((o) => o.outcome));
  });
  await check(`the service role cannot lift suspensions past the allowance: ${CONCURRENCY} simultaneous direct lifts with one free seat → exactly one`, async () => {
    const a = await account("PRACTICE", 3);
    const ps = []; for (let i = 0; i < 3; i++) { const p = await mkUser("s"); ps.push(p); await addActive(a.uid, a.co, p); }
    const r = await roster(a.uid);
    await prepare(a.lic.bc, 1, [], r.roster_version);            // everyone but the holder suspended
    await setSeats(a.lic.id, 1);                                  // allowance 2: one free seat
    const lift = (p) => codeOf(() => q(SERVICE, "UPDATE public.named_user_billing_suspensions SET lifted_at=now(), lifted_by=$2, lift_reason='OWNER_SELECTION' WHERE account_user_id=$1 AND user_id=$3 AND lifted_at IS NULL", [a.uid, a.uid, p]));
    const out = await Promise.all(Array.from({ length: CONCURRENCY }, (_, i) => lift(ps[i % 3])));
    return (await activeOf(a.uid)).length === 2 && out.filter((c) => c === "PT402").length >= 1 && (await invariant(a.uid)) ? true : JSON.stringify(out);
  });
  await check("the service role cannot bypass the invariant with ordinary membership writes: no new member, grant or re-admission for a suspended person; history cannot be deleted", async () => {
    const newcomer = await mkUser("n");
    const svcMember = await codeOf(() => q(SERVICE, "INSERT INTO public.firm_members (company_id,user_id,role,accepted_at) VALUES ($1,$2,'viewer',now())", [firm.co, newcomer]));
    const second = (await admin.query("INSERT INTO public.companies (user_id,name) VALUES ($1,'Second') RETURNING id", [practice.uid])).rows[0].id;
    const suspended = (await admin.query("SELECT user_id FROM public.named_user_billing_suspensions WHERE account_user_id=$1 AND lifted_at IS NULL LIMIT 1", [practice.uid])).rows[0].user_id;
    const svcSuspended = await errOf(() => q(SERVICE, "INSERT INTO public.firm_members (company_id,user_id,role,accepted_at) VALUES ($1,$2,'viewer',now())", [second, suspended]));
    const grantSuspended = await errOf(() => q(SERVICE, "INSERT INTO public.workspace_capability_grants (company_id, grantee_user_id, capability, granted_by_user_id) VALUES ($1,$2,'manage_source_files',$3)", [second, suspended, practice.uid]));
    const del = await codeOf(() => q(SERVICE, "DELETE FROM public.named_user_billing_suspensions WHERE account_user_id=$1", [practice.uid]));
    const delOwner = await codeOf(() => admin.query("DELETE FROM public.named_user_billing_suspensions WHERE account_user_id=$1", [practice.uid]));
    const trunc = await codeOf(() => admin.query("TRUNCATE public.named_user_billing_suspensions"));
    const clientWrite = await codeOf(() => q(user(practice.uid), "UPDATE public.named_user_billing_suspensions SET lifted_at=now(), lifted_by=$1, lift_reason='OWNER_SELECTION' WHERE account_user_id=$1", [practice.uid]));
    return svcMember === "PT402" && svcSuspended?.code === "PT402" && svcSuspended.hint === "SUSPENDED" && grantSuspended?.code === "PT402"
      && del === "42501" && delOwner === "P0001" && trunc === "P0001" && clientWrite === "42501" ? true : JSON.stringify({ svcMember, svcSuspended: svcSuspended?.hint, grantSuspended: grantSuspended?.code, del, delOwner, trunc, clientWrite });
  });

  group("P-03 — a suspended person gets exactly what an outsider gets: no read, no write, no RPC, no Edge authority");
  const S = firmPeople[5];                // suspended in firm.co (Firm → Free → Practice+1, pp choice kept firmPeople[0])
  const O = U.outsider;
  const sameDenial = async (fn) => JSON.stringify(await fn(S)) === JSON.stringify(await fn(O));
  await check("paid-action authority, commercial state, seat state and workspace access: identical to an unrelated user", async () =>
    (await sameDenial((w) => authz(w, firm.co))) && (await authz(S, firm.co)).code === "WORKSPACE_ACCESS_DENIED"
    && (await sameDenial(async (w) => (await one(user(w), "SELECT public.get_workspace_commercial_state($1) r", [firm.co])).r))
    && (await sameDenial(async (w) => (await one(user(w), "SELECT public.get_workspace_seat_capacity($1) r", [firm.co])).r))
    && (await sameDenial(async (w) => (await q(user(w), "SELECT * FROM public.get_workspace_access($1)", [firm.co])).length))
    && (await sameDenial(async (w) => (await one(user(w), "SELECT public.financial_statements_workspace_access($1) r", [firm.co])).r)));
  await check("RLS: the suspended person reads none of the workspace's rows (own membership, sign-offs, issuances, member company list); an active member reads them", async () => {
    const active = firmPeople[0];
    const up = (await admin.query("INSERT INTO public.trial_balance_uploads (file_name,file_path,file_size,status,company_id,user_id,period_year) VALUES ('tb.csv',$1,10,'complete',$2,$3,2031) RETURNING id", [`${firm.uid}/${uuid()}.csv`, firm.co, firm.uid])).rows[0].id;
    await admin.query("INSERT INTO public.statement_sign_offs (company_id, period_year, upload_id) VALUES ($1,2031,$2)", [firm.co, up]);
    const reads = async (w) => ({
      members: (await q(user(w), "SELECT id FROM public.firm_members WHERE company_id=$1", [firm.co])).length,
      signoffs: (await q(user(w), "SELECT id FROM public.statement_sign_offs WHERE company_id=$1", [firm.co])).length,
      companies: (await q(user(w), "SELECT c FROM public.get_member_company_ids() c WHERE c=$1", [firm.co])).length,
    });
    const s = await reads(S), o = await reads(O), a = await reads(active);
    return JSON.stringify(s) === JSON.stringify(o) && s.members === 0 && s.signoffs === 0 && s.companies === 0 && a.signoffs === 1 && a.companies === 1
      ? true : JSON.stringify({ s, o, a });
  });
  await check("RPCs: actor resolution, engagement scope, filing jurisdiction and processing authority all refuse the suspended person like an outsider", async () => {
    await admin.query("UPDATE public.firm_members SET role='partner' WHERE company_id=$1 AND user_id=$2", [firm.co, S]);
    const actor = await codeOf(() => one(user(S), "SELECT public.fs_actor_member_id($1) r", [firm.co]));
    const actorO = await codeOf(() => one(user(O), "SELECT public.fs_actor_member_id($1) r", [firm.co]));
    const scope = await codeOf(() => one(user(S), "SELECT public.open_engagement_with_scope($1,2031,ARRAY['FINANCIAL_STATEMENTS'],NULL) r", [firm.co]));
    const juris = await codeOf(() => one(user(S), "SELECT public.set_company_filing_jurisdiction($1,'TZ') r", [firm.co]));
    const proc = (await admin.query("SELECT count(*) n FROM public.tbu_resolve_processing_actor($1,$2)", [S, firm.co])).rows[0].n;
    const procActive = (await admin.query("SELECT count(*) n FROM public.tbu_resolve_processing_actor($1,$2)", [firmPeople[0], firm.co])).rows[0].n;
    return actor === "42501" && actor === actorO && scope === "42501" && juris === "42501" && Number(proc) === 0 && Number(procActive) === 1
      ? true : JSON.stringify({ actor, actorO, scope, juris, proc, procActive });
  });
  await check("capability grants: a suspended grantee has no authority basis and the workspace disappears from their shared list", async () => {
    const a = await account("PRACTICE", 1);
    const g = await mkUser("g");
    await grantTo(a.uid, a.co, g, "prepare_trial_balance");
    const beforeBasis = (await admin.query("SELECT public.workspace_authority_basis($1,$2,'prepare_trial_balance') b", [g, a.co])).rows[0].b;
    const beforeShared = (await q(user(g), "SELECT * FROM public.list_shared_workspaces()")).length;
    const r = await roster(a.uid);
    await choose(a.uid, [], r.roster_version);
    const afterBasis = (await admin.query("SELECT public.workspace_authority_basis($1,$2,'prepare_trial_balance') b", [g, a.co])).rows[0].b;
    const afterShared = (await q(user(g), "SELECT * FROM public.list_shared_workspaces()")).length;
    return beforeBasis === "explicit_capability" && beforeShared === 1 && afterBasis === null && afterShared === 0 ? true : JSON.stringify({ beforeBasis, beforeShared, afterBasis, afterShared });
  });
  await check("Edge Function authority (service role) sees the suspension; a signed-in user can never probe anyone else's state", async () => {
    const svc = (await one(SERVICE, "SELECT public.named_user_access_active($1,$2) r", [firm.co, S])).r;
    const svcActive = (await one(SERVICE, "SELECT public.named_user_access_active($1,$2) r", [firm.co, firmPeople[0]])).r;
    const probe = (await one(user(O), "SELECT public.named_user_access_active($1,$2) r", [firm.co, firmPeople[0]])).r;
    const anonCall = await codeOf(() => one(ANON, "SELECT public.named_user_access_active($1,$2) r", [firm.co, S]));
    return svc === false && svcActive === true && probe === false && anonCall === "42501" ? true : JSON.stringify({ svc, svcActive, probe, anonCall });
  });
  await check("removing a suspended member never corrupts attribution: an attributed membership cannot be deleted; an unattributed one can, and its suspension history remains", async () => {
    const attributed = firmPeople[6], plain = firmPeople[7];
    const memberId = (await admin.query("SELECT id FROM public.firm_members WHERE company_id=$1 AND user_id=$2", [firm.co, attributed])).rows[0].id;
    await admin.query(`INSERT INTO public.financial_statement_reports (report_id, report_version, company_id, period_year, provenance_origin, report_document, content_hash, document_hash, created_by_firm_member_id)
      VALUES ($1,1,$2,2031,'TRIAL_BALANCE_DERIVED','{}'::jsonb,$3,$3,$4)`, [`r-${uuid()}`, firm.co, "b".repeat(64), memberId]);
    const delAttributed = await codeOf(() => q(user(firm.uid), "DELETE FROM public.firm_members WHERE company_id=$1 AND user_id=$2", [firm.co, attributed]));
    const stillAttributed = await count("SELECT count(*) n FROM public.financial_statement_reports WHERE created_by_firm_member_id=$1", [memberId]);
    const delPlain = await codeOf(() => q(user(firm.uid), "DELETE FROM public.firm_members WHERE company_id=$1 AND user_id=$2", [firm.co, plain]));
    const history = await count("SELECT count(*) n FROM public.named_user_billing_suspensions WHERE account_user_id=$1 AND user_id=$2", [firm.uid, plain]);
    return delAttributed !== "ok" && stillAttributed === 1 && delPlain === "ok" && history === 1 ? true : JSON.stringify({ delAttributed, stillAttributed, delPlain, history });
  });

  group("P-04 — invitation reservations expire, can be cancelled or released, are never double-reserved, and stay within capacity");
  const reserve = async (co, who, by) => (await one(SERVICE, "SELECT public.reserve_workspace_invitation($1,$2,'preparer',$3,$4) r", [co, who, by, `${who}@example.test`])).r;
  const reservedOf = async (acct) => Number((await admin.query("SELECT count(*) n FROM public._account_named_users($1,true)", [acct])).rows[0].n);
  await check("a pending invitation carries an explicit expiry (invitation_reservation_ttl) and can never be given a longer one", async () => {
    const a = await account("PRACTICE", 2);
    const r1 = await reserve(a.co, await mkUser("i"), a.uid);
    const far = await mkUser("i");
    await admin.query("INSERT INTO public.firm_members (company_id,user_id,role,accepted_at,invitation_expires_at) VALUES ($1,$2,'viewer',NULL, now() + interval '400 days')", [a.co, far]);
    const ttl = (await admin.query("SELECT extract(epoch FROM public.invitation_reservation_ttl()) s")).rows[0].s;
    const rows = (await admin.query("SELECT extract(epoch FROM invitation_expires_at - now()) s FROM public.firm_members WHERE company_id=$1 AND accepted_at IS NULL", [a.co])).rows;
    return r1.outcome === "reserved" && rows.length === 2 && rows.every((x) => Number(x.s) <= Number(ttl) + 5 && Number(x.s) > Number(ttl) - 120) ? true : JSON.stringify({ r1, ttl, rows });
  });
  await check("expiry releases the seat atomically (no job) and an expired invitation cannot be accepted; the row is kept", async () => {
    const a = await account("PRACTICE", 1);
    const p = await mkUser("x"), q2 = await mkUser("x");
    await reserve(a.co, p, a.uid);
    const full = await reserve(a.co, q2, a.uid);
    await admin.query("UPDATE public.firm_members SET invitation_expires_at = now() - interval '1 minute' WHERE company_id=$1 AND user_id=$2", [a.co, p]);
    const reservedAfter = await reservedOf(a.uid);
    const acc = await accept(p);
    const freed = await reserve(a.co, q2, a.uid);
    const kept = await count("SELECT count(*) n FROM public.firm_members WHERE company_id=$1 AND user_id=$2 AND accepted_at IS NULL", [a.co, p]);
    return full.outcome === "seat_limit_reached" && reservedAfter === 1 && acc.blocked.length === 1 && acc.blocked[0].code === "INVITATION_EXPIRED"
      && freed.outcome === "reserved" && kept === 1 ? true : JSON.stringify({ full, reservedAfter, acc, freed, kept });
  });
  await check("the account holder cancels a pending invitation: the seat is released at once, the invitation can no longer be accepted, the row is kept; nobody else can cancel it", async () => {
    const a = await account("PRACTICE", 1);
    const p = await mkUser("c"), q2 = await mkUser("c");
    const r = await reserve(a.co, p, a.uid);
    const byOther = (await one(user(U.outsider), "SELECT public.cancel_workspace_invitation($1) r", [r.member_id])).r;
    const byInvitee = (await one(user(p), "SELECT public.cancel_workspace_invitation($1) r", [r.member_id])).r;
    const cancel = (await one(user(a.uid), "SELECT public.cancel_workspace_invitation($1) r", [r.member_id])).r;
    const again = (await one(user(a.uid), "SELECT public.cancel_workspace_invitation($1) r", [r.member_id])).r;
    const acc = await accept(p);
    const next = await reserve(a.co, q2, a.uid);
    return byOther.outcome === "not_found" && byInvitee.outcome === "not_found" && cancel.outcome === "cancelled" && again.outcome === "already_cancelled"
      && acc.blocked[0]?.code === "INVITATION_CANCELLED" && next.outcome === "reserved"
      && (await count("SELECT count(*) n FROM public.firm_members WHERE id=$1", [r.member_id])) === 1 ? true : JSON.stringify({ byOther, byInvitee, cancel, again, acc, next });
  });
  await check("reissuing never double-reserves: the same person is one row; a valid invitation is refreshed, an expired or cancelled one is reissued only if a seat is free", async () => {
    const a = await account("PRACTICE", 1);
    const p = await mkUser("r"), q2 = await mkUser("r");
    const first = await reserve(a.co, p, a.uid);
    const again = await reserve(a.co, p, a.uid);
    const rows = await count("SELECT count(*) n FROM public.firm_members WHERE company_id=$1 AND user_id=$2", [a.co, p]);
    const reserved = await reservedOf(a.uid);
    await one(user(a.uid), "SELECT public.cancel_workspace_invitation($1) r", [first.member_id]);
    await reserve(a.co, q2, a.uid);                        // the released seat is taken by someone else
    const reissue = await reserve(a.co, p, a.uid);
    return first.outcome === "reserved" && again.outcome === "refreshed" && again.member_id === first.member_id && rows === 1 && reserved === 2
      && reissue.outcome === "seat_limit_reached" ? true : JSON.stringify({ first, again, rows, reserved, reissue });
  });
  await check("repeated invitation attempts cannot exhaust seats permanently: expired reservations hold nothing", async () => {
    const a = await account("PRACTICE", 2);
    for (let i = 0; i < 2; i++) await reserve(a.co, await mkUser("e"), a.uid);
    const blocked = await reserve(a.co, await mkUser("e"), a.uid);
    await admin.query("UPDATE public.firm_members SET invitation_expires_at = now() - interval '1 minute' WHERE company_id=$1 AND accepted_at IS NULL", [a.co]);
    const ok1 = await reserve(a.co, await mkUser("e"), a.uid);
    const ok2 = await reserve(a.co, await mkUser("e"), a.uid);
    return blocked.outcome === "seat_limit_reached" && ok1.outcome === "reserved" && ok2.outcome === "reserved";
  });
  await check("an email that could not be sent releases the reservation (release_workspace_invitation, service role only)", async () => {
    const a = await account("PRACTICE", 1);
    const p = await mkUser("m");
    const r = await reserve(a.co, p, a.uid);
    const clientCall = await codeOf(() => one(user(a.uid), "SELECT public.release_workspace_invitation($1) r", [r.member_id]));
    const rel = (await one(SERVICE, "SELECT public.release_workspace_invitation($1) r", [r.member_id])).r;
    const reserved = await reservedOf(a.uid);
    const reason = (await admin.query("SELECT invitation_cancel_reason x FROM public.firm_members WHERE id=$1", [r.member_id])).rows[0].x;
    return clientCall === "42501" && rel.outcome === "released" && reserved === 1 && reason === "EMAIL_FAILED" ? true : JSON.stringify({ clientCall, rel, reserved, reason });
  });
  await check(`${CONCURRENCY} simultaneous reservations (+2 seats): exactly 2; the same person reserved ${CONCURRENCY} times at once: one row`, async () => {
    const a = await account("PRACTICE", 2);
    const people = []; for (let i = 0; i < CONCURRENCY; i++) people.push(await mkUser("cc"));
    const out = await Promise.all(people.map((p) => reserve(a.co, p, a.uid)));
    const b = await account("PRACTICE", 2);
    const same = await mkUser("same");
    const out2 = await Promise.all(Array.from({ length: CONCURRENCY }, () => reserve(b.co, same, b.uid)));
    const rows = await count("SELECT count(*) n FROM public.firm_members WHERE company_id=$1 AND user_id=$2", [b.co, same]);
    return out.filter((o) => o.outcome === "reserved").length === 2 && out.filter((o) => o.outcome === "seat_limit_reached").length === CONCURRENCY - 2
      && rows === 1 && out2.filter((o) => o.outcome === "reserved").length === 1 ? true : JSON.stringify({ o1: out.map((o) => o.outcome), o2: out2.map((o) => o.outcome), rows });
  });
  await check("acceptance racing cancellation resolves to exactly one of them, never both", async () => {
    const results = [];
    for (let i = 0; i < 6; i++) {
      const a = await account("PRACTICE", 1);
      const p = await mkUser("race");
      const r = await reserve(a.co, p, a.uid);
      const [acc, can] = await Promise.all([accept(p), one(user(a.uid), "SELECT public.cancel_workspace_invitation($1) r", [r.member_id]).then((x) => x.r)]);
      const row = (await admin.query("SELECT accepted_at, invitation_cancelled_at FROM public.firm_members WHERE id=$1", [r.member_id])).rows[0];
      const accepted = row.accepted_at !== null, cancelled = row.invitation_cancelled_at !== null;
      results.push(accepted !== cancelled && (accepted ? can.outcome === "not_pending" && acc.accepted.length === 1 : can.outcome === "cancelled"));
    }
    return results.every(Boolean) ? true : JSON.stringify(results);
  });

  group("P-05 — the official Reporting Pack: generated by the DATABASE from the saved output, bound, single-use, re-authorised at seal time, verifiable, audited (B-4, N-1)");
  // The official document is rendered by the database from the persisted financial_statement_reports row named by the
  // closed output reference; nobody supplies bytes or a hash. The handler below is the Edge Function's own module
  // (supabase/functions/_shared/reportingPackSeal.mjs), run against THIS database through the service role. The
  // private bucket is modelled by an in-memory object store (Supabase Storage is not part of a PostgreSQL proof).
  const { issueOfficialPack, verifyStoredPack, verifyOfficialPack, parseSealRequest } = await import(pathToFileURL(path.join(REPO, "supabase/functions/_shared/reportingPackSeal.mjs")).href);
  const { createHash } = await import("node:crypto");
  const sha = (b) => createHash("sha256").update(b).digest("hex");
  const bucket = new Map();
  const serviceRpc = async (fn, args) => {
    const keys = Object.keys(args);
    try {
      const r = await one(SERVICE, `SELECT public.${fn}(${keys.map((k, i) => `${k} => $${i + 1}`).join(", ")}) r`, keys.map((k) => args[k]));
      return { data: r.r, error: null };
    } catch (e) { return { data: null, error: e }; }
  };
  // The bucket model records each object in storage.objects with its size, as Supabase Storage does on upload.
  const storeObject = async (p, b) => {
    bucket.set(p, b);
    await admin.query("DELETE FROM storage.objects WHERE bucket_id='reporting-packs' AND name=$1", [p]);
    await admin.query("INSERT INTO storage.objects (bucket_id, name, metadata) VALUES ('reporting-packs', $1, $2::jsonb)", [p, JSON.stringify({ size: b.byteLength, mimetype: "application/json" })]);
  };
  const dropObject = async (p) => { bucket.delete(p); await admin.query("DELETE FROM storage.objects WHERE bucket_id='reporting-packs' AND name=$1", [p]); };
  const deps = {
    rpc: serviceRpc,
    // No overwrite: check-and-reserve in one tick, then record the object.
    put: async (p, b) => { if (bucket.has(p)) return { error: { message: "exists" } }; bucket.set(p, b); await storeObject(p, b); return { error: null }; },
    remove: async (p) => dropObject(p),
    get: async (p) => bucket.get(p) ?? null,
    sha256Hex: async (b) => sha(b),
  };
  const official = (who, id) => issueOfficialPack(deps, { userId: who, issuanceId: id });
  // THE official-verification route (X-3): the Edge Function's own code — access check, download, re-hash.
  const edgeVerify = (who, id) => verifyOfficialPack(deps, who, id);
  const sealsOf = (id) => count("SELECT count(*) n FROM public.reporting_pack_issuances WHERE id=$1 AND consumed_at IS NOT NULL", [id]);
  // A saved statements version of a workspace and period (as the persistence RPC records it: document hash by the server).
  // A saved version and its publication history as fs_set_publication_state records it: DRAFT -> REVIEWED -> FINAL
  // (state = the last step recorded; null = never published). Returns the version's output reference.
  const pubOf = new Map();
  const STEPS = { DRAFT: ["DRAFT"], REVIEWED: ["DRAFT", "REVIEWED"], FINAL: ["DRAFT", "REVIEWED", "FINAL"] };
  const publish = async (co, rid, version, state, pubCompany = co) => {
    const member = (await admin.query("SELECT id FROM public.firm_members WHERE company_id=$1 AND role='owner'", [co])).rows[0]?.id;
    await admin.query("BEGIN"); await admin.query("SET LOCAL session_replication_role = replica");
    let last = null;
    for (const st of STEPS[state] ?? []) {
      last = (await admin.query("INSERT INTO public.financial_statement_publications (report_id, report_version, company_id, state, reason, actor_firm_member_id) VALUES ($1,$2,$3,$4,'proof publication step',$5) RETURNING id", [rid, version, pubCompany, st, member])).rows[0].id;
    }
    await admin.query("COMMIT");
    return last;
  };
  const savedOutput = async (acct, co, period, doc, state = "FINAL", rid = `r-${uuid()}`, version = 1) => {
    const member = (await admin.query("SELECT id FROM public.firm_members WHERE company_id=$1 AND user_id=$2", [co, acct])).rows[0]?.id;
    await admin.query("BEGIN"); await admin.query("SET LOCAL session_replication_role = replica");
    await admin.query(`INSERT INTO public.financial_statement_reports (report_id, report_version, company_id, period_year, provenance_origin, report_document, content_hash, document_hash, created_by_firm_member_id)
      VALUES ($1,$7,$2,$3,'TRIAL_BALANCE_DERIVED',$4::jsonb,$5, public.fs_sha256_hex($4::jsonb::text), $6)`, [rid, co, period, JSON.stringify(doc), "e".repeat(64), member, version]);
    await admin.query("COMMIT");
    const ref = `fs-report:${rid}:v${version}`;
    if (state) pubOf.set(ref, await publish(co, rid, version, state));
    return ref;
  };
  const uploadRef = async (acct, co, period = 2031) => `upload:${(await admin.query("INSERT INTO public.trial_balance_uploads (file_name,file_path,file_size,status,company_id,user_id,period_year) VALUES ('tb.csv',$1,10,'complete',$2,$3,$4) RETURNING id", [`${acct}/${uuid()}.csv`, co, acct, period])).rows[0].id}`;
  const issue = async (who, co, kind, ref, period = 2031, rid = uuid()) =>
    (await one(user(who), "SELECT public.issue_reporting_pack($1,$2,$3,$4,$5) r", [co, period, kind, ref, rid])).r;
  // An OFFICIAL issuance: bound by the server to the exact FINAL publication of the saved version (X-1).
  const issueO = async (who, co, ref, period = 2031, rid = uuid()) =>
    (await one(user(who), "SELECT public.issue_official_reporting_pack($1,$2,$3,$4) r", [co, period, ref, rid])).r;
  const DOC = { statements: { revenue: "1000000.00", profit: "250000.00" }, entity: { legalName: "Proof Ltd — Dar es Salaam" } };
  const pk = await account("PRACTICE", 1);
  const pkMember = await mkUser("pk");
  await addActive(pk.uid, pk.co, pkMember);
  const other = await account("PRACTICE", 0);
  const R = await savedOutput(pk.uid, pk.co, 2031, DOC);
  const R30 = await savedOutput(pk.uid, pk.co, 2030, { ...DOC, statements: { revenue: "900000.00", profit: "1.00" } });
  const RO = await savedOutput(other.uid, other.co, 2031, { ...DOC, entity: { legalName: "Other Co" } });
  const UP = await uploadRef(pk.uid, pk.co);

  await check("a workspace with no current plan cannot obtain an issuance at all (and the refusal is audited)", async () => {
    const f = await account("PRACTICE");
    const fr = await savedOutput(f.uid, f.co, 2031, DOC);
    await admin.query("UPDATE public.commercial_licences SET status='EXPIRED', effective_end = now() WHERE id=$1", [f.lic.id]);
    const r = await issueO(f.uid, f.co, fr);
    return r.outcome === "entitlement_required" && (await count("SELECT count(*) n FROM public.reporting_pack_issuance_events WHERE company_id=$1 AND event='REFUSED'", [f.co])) === 1;
  });
  await check("no path accepts bytes or a hash: the client-hash function is gone; prepare and seal are service-role only; the seal's only inputs are user, issuance and storage path", async () => {
    const i = await issueO(pk.uid, pk.co, R);
    const clientPrep = await codeOf(() => q(user(pk.uid), "SELECT public.prepare_official_reporting_pack($1,$2)", [pk.uid, i.issuance_id]));
    const clientSeal = await codeOf(() => q(user(pk.uid), "SELECT public.seal_reporting_pack_server($1,$2,$3)", [pk.uid, i.issuance_id, `${pk.co}/${i.issuance_id}.json`]));
    const oldConsume = (await admin.query("SELECT to_regproc('public.consume_reporting_pack_issuance') p")).rows[0].p;
    const sigs = (await admin.query("SELECT p.oid::regprocedure::text s, pg_get_function_identity_arguments(p.oid) a FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='seal_reporting_pack_server'")).rows;
    return clientPrep === "42501" && clientSeal === "42501" && oldConsume === null && sigs.length === 1 && sigs[0].a === "p_user uuid, p_issuance_id uuid, p_storage_path text"
      ? true : JSON.stringify({ clientPrep, clientSeal, oldConsume, sigs });
  });
  let canonical;
  await check("the canonical server-produced document of a saved output seals and verifies: deterministic, the stored bytes ARE the sealed bytes, the database's hash equals the SHA-256 of those bytes", async () => {
    const i = await issueO(pk.uid, pk.co, R);
    const docA = (await one(SERVICE, "SELECT public.prepare_official_reporting_pack($1,$2) r", [pk.uid, i.issuance_id])).r;
    // A different session time zone must not change a single byte.
    const docB = await asCaller(SERVICE, async (c) => {
      await c.query("SET LOCAL TimeZone = 'Pacific/Kiritimati'");
      return (await c.query("SELECT public.prepare_official_reporting_pack($1,$2) r", [pk.uid, i.issuance_id])).rows[0].r;
    });
    const r = await official(pk.uid, i.issuance_id);
    const row = (await admin.query("SELECT content_sha256, storage_path, byte_size FROM public.reporting_pack_issuances WHERE id=$1", [i.issuance_id])).rows[0];
    const stored = bucket.get(`${pk.co}/${i.issuance_id}.json`);
    const parsed = JSON.parse(r.body.document ?? "null");
    const member = await edgeVerify(pkMember, i.issuance_id);
    const intact = (await verifyStoredPack(deps, i.issuance_id)).outcome;
    canonical = { id: i.issuance_id, sha: row.content_sha256, document: r.body.document };
    const ok = r.body.outcome === "sealed" && docA.document === docB.document && docA.content_sha256 === row.content_sha256
      && sha(stored) === row.content_sha256 && Buffer.from(stored).toString("utf8") === r.body.document && Number(row.byte_size) === stored.byteLength
      && parsed.schema === "cfoclose.official-reporting-pack.v1" && parsed.source.report_id === R.split(":")[1] && parsed.source.report_version === 1
      && parsed.issuance.issuance_id === i.issuance_id && parsed.report.statements.revenue === DOC.statements.revenue
      && parsed.report.statements.profit === DOC.statements.profit && parsed.report.entity.legalName === DOC.entity.legalName && /Z$/.test(parsed.issuance.issued_at)
      && member.official === true && intact === "intact";
    return ok ? true : JSON.stringify({ outcome: r.body, row, member, intact });
  });
  await check("adversarial bytes — unrelated valid PDF, a doctored copy of the legitimate file, the canonical file of another period / workspace / output: every submission is refused, creates no seal, and none verifies as official", async () => {
    const i = await issueO(pk.uid, pk.co, R);
    const pdf = Buffer.from("%PDF-1.7\n1 0 obj <<>> endobj\ntrailer <<>>\n%%EOF\n");
    const doctored = Buffer.from(canonical.document.replace("1000000.00", "9000000.00"));
    const i30 = await issueO(pk.uid, pk.co, R30, 2030);
    const iO = await issueO(other.uid, other.co, RO);
    const foreignPeriod = Buffer.from((await one(SERVICE, "SELECT public.prepare_official_reporting_pack($1,$2) r", [pk.uid, i30.issuance_id])).r.document);
    const foreignWs = Buffer.from((await one(SERVICE, "SELECT public.prepare_official_reporting_pack($1,$2) r", [other.uid, iO.issuance_id])).r.document);
    const out = {};
    for (const [name, bytes] of [["unrelated_pdf", pdf], ["doctored", doctored], ["other_period", foreignPeriod], ["other_workspace", foreignWs]]) {
      // Every way a caller could hand those bytes to the Edge Function is refused before the database is reached.
      const submissions = [
        parseSealRequest("multipart/form-data; boundary=x", { action: "issue", issuance_id: i.issuance_id }),
        parseSealRequest("application/pdf", bytes),
        parseSealRequest("application/json", { action: "issue", issuance_id: i.issuance_id, document: bytes.toString("utf8") }),
        parseSealRequest("application/json", { action: "issue", issuance_id: i.issuance_id, content_sha256: sha(bytes) }),
      ];
      const official1 = (await edgeVerify(pk.uid, i.issuance_id)).official;
      out[name] = { refused: submissions.every((x) => x === null), official: official1 };
    }
    const noSeal = (await sealsOf(i.issuance_id)) === 0 && (await sealsOf(i30.issuance_id)) === 0 && (await sealsOf(iO.issuance_id)) === 0;
    // Even the service role storing substitute bytes at the issuance's own path cannot make them official: the
    // handler compares the stored object with the database's canonical hash BEFORE sealing, and the seal function
    // hashes its own regeneration, never the object.
    const svc = [];
    for (const bytes of [pdf, doctored, foreignPeriod, foreignWs]) {
      const j = await issueO(pk.uid, pk.co, R);
      const put = deps.put;
      deps.put = async (p) => { await storeObject(p, new Uint8Array(bytes)); return { error: null }; };
      const r = await official(pk.uid, j.issuance_id);
      deps.put = put;
      svc.push({ outcome: r.body.outcome, sealed: await sealsOf(j.issuance_id), stored: bucket.has(`${pk.co}/${j.issuance_id}.json`) });
    }
    const svcOk = svc.every((x) => x.outcome === "seal_failed" && x.sealed === 0 && x.stored === false);
    return Object.values(out).every((x) => x.refused && x.official === false) && noSeal && svcOk ? true : JSON.stringify({ out, noSeal, svc });
  });
  await check("post-seal storage substitution is detected (substituted / missing), and substitute bytes never verify as official", async () => {
    const i = await issueO(pk.uid, pk.co, R);
    const r = await official(pk.uid, i.issuance_id);
    const p = `${pk.co}/${i.issuance_id}.json`;
    const swapped = Buffer.from(r.body.document.replace("250000.00", "0.00"));
    bucket.set(p, new Uint8Array(swapped));
    const sub = (await verifyStoredPack(deps, i.issuance_id)).outcome;
    const swappedOfficial = (await edgeVerify(pk.uid, i.issuance_id)).official;
    await dropObject(p);
    const missing = (await verifyStoredPack(deps, i.issuance_id)).outcome;
    // Without its stored object a seal is never answered official.
    const noObject = (await edgeVerify(pk.uid, i.issuance_id)).official;
    return sub === "substituted" && swappedOfficial === false && missing === "missing" && noObject === false ? true : JSON.stringify({ sub, swappedOfficial, missing, noObject });
  });
  await check("no seal without the stored object: sealing before storing (or after it vanished) is refused as object_missing and nothing is sealed", async () => {
    const i = await issueO(pk.uid, pk.co, R);
    const r = (await one(SERVICE, "SELECT public.seal_reporting_pack_server($1,$2,$3) r", [pk.uid, i.issuance_id, `${pk.co}/${i.issuance_id}.json`])).r.outcome;
    // An object of the wrong size at the right path is not the canonical object either.
    await storeObject(`${pk.co}/${i.issuance_id}.json`, new Uint8Array(Buffer.from("x")));
    const wrongSize = (await one(SERVICE, "SELECT public.seal_reporting_pack_server($1,$2,$3) r", [pk.uid, i.issuance_id, `${pk.co}/${i.issuance_id}.json`])).r.outcome;
    await dropObject(`${pk.co}/${i.issuance_id}.json`);
    return r === "object_missing" && wrongSize === "object_missing" && (await sealsOf(i.issuance_id)) === 0 ? true : JSON.stringify({ r, wrongSize });
  });
  await check("SQL callers cannot supply a hash, size or path: the service role has no UPDATE; even the table owner's direct seal must be the canonical document", async () => {
    const i = await issueO(pk.uid, pk.co, R);
    const p = `${pk.co}/${i.issuance_id}.json`;
    const svc = await codeOf(() => q(SERVICE, "UPDATE public.reporting_pack_issuances SET consumed_at=now(), content_sha256=$2, consumed_plan_code='PRACTICE', storage_path=$3, byte_size=10 WHERE id=$1", [i.issuance_id, "a".repeat(64), p]));
    const forged = await codeOf(() => admin.query("UPDATE public.reporting_pack_issuances SET consumed_at=now(), content_sha256=$2, consumed_plan_code='PRACTICE', storage_path=$3, byte_size=10 WHERE id=$1", [i.issuance_id, "a".repeat(64), p]));
    const doc = (await one(SERVICE, "SELECT public.prepare_official_reporting_pack($1,$2) r", [pk.uid, i.issuance_id])).r;
    const wrongPath = await codeOf(() => admin.query("UPDATE public.reporting_pack_issuances SET consumed_at=now(), content_sha256=$2, consumed_plan_code='PRACTICE', storage_path=$3, byte_size=$4 WHERE id=$1", [i.issuance_id, doc.content_sha256, `${other.co}/${i.issuance_id}.json`, doc.byte_size]));
    const wrongSize = await codeOf(() => admin.query("UPDATE public.reporting_pack_issuances SET consumed_at=now(), content_sha256=$2, consumed_plan_code='PRACTICE', storage_path=$3, byte_size=$4 WHERE id=$1", [i.issuance_id, doc.content_sha256, p, doc.byte_size + 1]));
    const fnArgs = (await admin.query("SELECT string_agg(pg_get_function_identity_arguments(p.oid), ' | ') a FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname IN ('prepare_official_reporting_pack','seal_reporting_pack_server')")).rows[0].a;
    return svc === "42501" && forged === "P0001" && wrongPath === "P0001" && wrongSize === "P0001" && (await sealsOf(i.issuance_id)) === 0 && !/sha|hash|byte|content|document/.test(fnArgs)
      ? true : JSON.stringify({ svc, forged, wrongPath, wrongSize, fnArgs });
  });
  await check("storage success followed by seal failure leaves no uncontrolled orphan: an interrupted request's object is listed, never official, and a retry reuses exactly-canonical bytes or replaces foreign ones", async () => {
    const i = await issueO(pk.uid, pk.co, R);
    const p = `${pk.co}/${i.issuance_id}.json`;
    const doc = (await one(SERVICE, "SELECT public.prepare_official_reporting_pack($1,$2) r", [pk.uid, i.issuance_id])).r;
    await storeObject(p, new TextEncoder().encode(doc.document));   // stored, then the request died before sealing
    const listed = (await q(SERVICE, "SELECT storage_path FROM public.reporting_pack_storage_orphans()")).map((x) => x.storage_path).includes(p);
    const notOfficial = (await edgeVerify(pk.uid, i.issuance_id)).official === false;
    const retry = (await official(pk.uid, i.issuance_id)).body.outcome;
    const cleared = !(await q(SERVICE, "SELECT storage_path FROM public.reporting_pack_storage_orphans()")).map((x) => x.storage_path).includes(p);
    const j = await issueO(pk.uid, pk.co, R);
    const pj = `${pk.co}/${j.issuance_id}.json`;
    await storeObject(pj, new Uint8Array(Buffer.from("foreign bytes left behind")));
    const replaced = (await official(pk.uid, j.issuance_id)).body;
    const clientOrphans = await codeOf(() => q(user(pk.uid), "SELECT * FROM public.reporting_pack_storage_orphans()"));
    return listed && notOfficial && retry === "sealed" && cleared && replaced.outcome === "sealed" && sha(bucket.get(pj)) === replaced.content_sha256
      && (await verifyStoredPack(deps, j.issuance_id)).outcome === "intact" && clientOrphans === "42501"
      ? true : JSON.stringify({ listed, notOfficial, retry, cleared, replaced: replaced.outcome, clientOrphans });
  });
  await check("later live-data changes do not alter an issued document: a new saved version, a new upload and a new period leave the sealed document canonical and official; the saved version itself cannot be changed", async () => {
    const RL = await savedOutput(pk.uid, pk.co, 2031, DOC);
    const i = await issueO(pk.uid, pk.co, RL);
    const r = await official(pk.uid, i.issuance_id);
    const rid = RL.split(":")[1];
    const member = (await admin.query("SELECT id FROM public.firm_members WHERE company_id=$1 AND user_id=$2", [pk.co, pk.uid])).rows[0].id;
    await admin.query("BEGIN"); await admin.query("SET LOCAL session_replication_role = replica");
    await admin.query(`INSERT INTO public.financial_statement_reports (report_id, report_version, company_id, period_year, provenance_origin, report_document, content_hash, document_hash, created_by_firm_member_id)
      VALUES ($1,2,$2,2031,'TRIAL_BALANCE_DERIVED','{"statements":{"revenue":"1.00"}}'::jsonb,$3, public.fs_sha256_hex('{"statements":{"revenue":"1.00"}}'::jsonb::text), $4)`, [rid, pk.co, "e".repeat(64), member]);
    await admin.query("COMMIT");
    await uploadRef(pk.uid, pk.co, 2032);
    const obj = (await one(SERVICE, "SELECT public.reporting_pack_sealed_object($1) r", [i.issuance_id])).r;
    const stillOfficial = (await edgeVerify(pk.uid, i.issuance_id)).official;
    const ownerEdit = await codeOf(() => admin.query("UPDATE public.financial_statement_reports SET report_document='{}'::jsonb WHERE report_id=$1 AND report_version=1", [rid]));
    const svcEdit = await codeOf(() => q(SERVICE, "UPDATE public.financial_statement_reports SET report_document='{}'::jsonb WHERE report_id=$1 AND report_version=1", [rid]));
    const del = await codeOf(() => admin.query("DELETE FROM public.financial_statement_reports WHERE report_id=$1 AND report_version=1", [rid]));
    return obj.canonical_sha256 === r.body.content_sha256 && obj.object_present === true && stillOfficial === true && ownerEdit !== "ok" && svcEdit !== "ok" && del !== "ok"
      && (await verifyStoredPack(deps, i.issuance_id)).outcome === "intact" ? true : JSON.stringify({ obj, stillOfficial, ownerEdit, svcEdit, del });
  });
  await check("working copies and drafts never verify as official: an issued, unsealed working copy's bytes, and a draft reference, are never official", async () => {
    const w = await issue(pk.uid, pk.co, "financial_statements_pdf", UP);
    const bytes = Buffer.from(`%PDF working copy ${w.issuance_id}`);
    const v = (await edgeVerify(pk.uid, w.issuance_id)).official;
    const d = (await issueO(pk.uid, pk.co, "fs-draft:r1:abcdef0123456789")).outcome;
    const sealedWorkingCopies = await count("SELECT count(*) n FROM public.reporting_pack_issuances WHERE pack_kind <> 'financial_statements_data' AND consumed_at IS NOT NULL AND storage_path IS NOT NULL");
    return w.outcome === "issued" && v === false && d === "invalid_request" && sealedWorkingCopies === 0 ? true : JSON.stringify({ w, v, d, sealedWorkingCopies });
  });
  await check("a saved output altered after sealing (superuser forgery) is never official: generation refuses it and verification answers not_canonical / official false", async () => {
    const f = await savedOutput(pk.uid, pk.co, 2031, DOC);
    const i = await issueO(pk.uid, pk.co, f);
    const r = await official(pk.uid, i.issuance_id);
    await admin.query("BEGIN"); await admin.query("SET LOCAL session_replication_role = replica");
    await admin.query("UPDATE public.financial_statement_reports SET report_document = jsonb_set(report_document, '{statements,profit}', '\"999.00\"') WHERE report_id=$1", [f.split(":")[1]]);
    await admin.query("COMMIT");
    const verified = (await edgeVerify(pk.uid, i.issuance_id)).official;
    const stored = (await verifyStoredPack(deps, i.issuance_id)).outcome;
    const j = await issueO(pk.uid, pk.co, f);
    const regen = await codeOf(() => q(SERVICE, "SELECT public.prepare_official_reporting_pack($1,$2)", [pk.uid, j.issuance_id]));
    return r.body.outcome === "sealed" && verified === false && stored === "not_canonical" && regen === "XX001" ? true : JSON.stringify({ r: r.body.outcome, verified, stored, regen });
  });
  await check("wrong format and non-authoritative outputs are never official: a browser-rendered format, an upload-based output and every non-data kind are refused before anything is stored", async () => {
    const cases = [["financial_statements_pdf", R], ["financial_statements_spreadsheet", R], ["client_pack", R], ["filing_pack", R], ["financial_statements_data", UP], ["management_letter", UP], ["tax_computation", UP]];
    const out = [];
    for (const [kind, ref] of cases) {
      const i = await issue(pk.uid, pk.co, kind, ref);
      const r = await official(pk.uid, i.issuance_id);
      out.push(`${kind}:${i.outcome}:${r.body.outcome}:${await sealsOf(i.issuance_id)}:${bucket.has(`${pk.co}/${i.issuance_id}.json`)}`);
    }
    return out.every((x) => /:issued:official_sealing_unavailable:0:false$/.test(x)) ? true : JSON.stringify(out);
  });
  await check("cross-account, replay, closed output references and bindings stay enforced", async () => {
    const i = await issueO(pk.uid, pk.co, R);
    const cross = (await official(pkMember, i.issuance_id)).body.outcome;
    const outsider = (await official(U.outsider, i.issuance_id)).body.outcome;
    const first = (await official(pk.uid, i.issuance_id)).body.outcome;
    const replay = (await official(pk.uid, i.issuance_id)).body.outcome;
    const wrongPath = (await one(SERVICE, "SELECT public.seal_reporting_pack_server($1,$2,$3) r", [pk.uid, (await issueO(pk.uid, pk.co, R)).issuance_id, `${other.co}/x.json`])).r.outcome;
    const refs = [];
    for (const ref of ["fs-draft:r1:abcdef0123456789", RO, "fs-report:nope:v1", `fs-report:${R.split(":")[1]}:v2`, "anything"]) refs.push((await issueO(pk.uid, pk.co, ref)).outcome);
    const otherPeriod = (await issueO(pk.uid, pk.co, R, 2030)).outcome;
    return cross === "not_found" && outsider === "not_found" && first === "sealed" && replay === "already_sealed" && wrongPath === "binding_mismatch"
      && refs.every((o) => o === "invalid_request") && otherPeriod === "invalid_request" ? true : JSON.stringify({ cross, outsider, first, replay, wrongPath, refs, otherPeriod });
  });
  await check("a downgrade or a suspension between issue and generation is refused, and nothing is stored or sealed", async () => {
    const a = await account("PRACTICE", 1);
    const ar = await savedOutput(a.uid, a.co, 2031, DOC);
    const m = await mkUser("dg");
    await addActive(a.uid, a.co, m);
    const i = await issueO(a.uid, a.co, ar);
    const im = await issueO(m, a.co, ar);
    const r = await roster(a.uid);
    await choose(a.uid, [], r.roster_version);
    const memberSeal = (await official(m, im.issuance_id)).body.outcome;
    await admin.query("UPDATE public.commercial_licences SET status='EXPIRED', effective_end=now() WHERE id=$1", [a.lic.id]);
    const holderSeal = (await official(a.uid, i.issuance_id)).body.outcome;
    return memberSeal === "workspace_access_denied" && holderSeal === "entitlement_required" && (await sealsOf(i.issuance_id)) === 0 && (await sealsOf(im.issuance_id)) === 0
      && !bucket.has(`${a.co}/${i.issuance_id}.json`) ? true : JSON.stringify({ memberSeal, holderSeal });
  });
  await check(`${CONCURRENCY} concurrent generations of the same issuance: exactly one seal and one stored object`, async () => {
    const i = await issueO(pk.uid, pk.co, R);
    const out = await Promise.all(Array.from({ length: CONCURRENCY }, () => official(pk.uid, i.issuance_id).then((r) => r.body.outcome)));
    return out.filter((o) => o === "sealed").length === 1 && out.filter((o) => o === "already_sealed").length === CONCURRENCY - 1 && (await sealsOf(i.issuance_id)) === 1
      ? true : JSON.stringify(out);
  });
  await check("verification: official for the workspace's members only (also after the plan ends); unknown bytes never are", async () => {
    const v = await account("PRACTICE", 1);
    const vr = await savedOutput(v.uid, v.co, 2031, DOC);
    const vm = await mkUser("vm"); await addActive(v.uid, v.co, vm);
    const i = await issueO(v.uid, v.co, vr);
    const s = (await official(v.uid, i.issuance_id)).body.content_sha256;
    const member = await edgeVerify(vm, i.issuance_id);
    const outsider = await edgeVerify(U.outsider, i.issuance_id);
    const unknown = await edgeVerify(v.uid, uuid());
    await admin.query("UPDATE public.commercial_licences SET status='EXPIRED', effective_end=now() WHERE id=$1", [v.lic.id]);
    const afterExpiry = await edgeVerify(v.uid, i.issuance_id);
    const stored = (await one(SERVICE, "SELECT public.reporting_pack_sealed_object($1) r", [i.issuance_id])).r;
    return member.official === true && outsider.official === false && outsider.outcome === "not_found" && unknown.official === false && afterExpiry.official === true
      && stored.content_sha256 === s && stored.canonical_sha256 === s && stored.storage_path === `${v.co}/${i.issuance_id}.json` ? true : JSON.stringify({ member, outsider, unknown, afterExpiry, stored });
  });
  await check("issuances and their audit events cannot be written, changed or deleted by clients or the service role; issuances change only by one seal", async () => {
    const i = await issueO(pk.uid, pk.co, R);
    const clientIns = await codeOf(() => q(user(pk.uid), "INSERT INTO public.reporting_pack_issuance_events (event) VALUES ('ISSUED')"));
    const svcIns = await codeOf(() => q(SERVICE, "INSERT INTO public.reporting_pack_issuance_events (event) VALUES ('ISSUED')"));
    const evUpd = await codeOf(() => admin.query("UPDATE public.reporting_pack_issuance_events SET event='SEALED' WHERE issuance_id=$1", [i.issuance_id]));
    const evDel = await codeOf(() => admin.query("DELETE FROM public.reporting_pack_issuance_events WHERE issuance_id=$1", [i.issuance_id]));
    const kindUpd = await codeOf(() => admin.query("UPDATE public.reporting_pack_issuances SET pack_kind='client_pack' WHERE id=$1", [i.issuance_id]));
    const extend = await codeOf(() => admin.query("UPDATE public.reporting_pack_issuances SET expires_at = now() + interval '1 day' WHERE id=$1", [i.issuance_id]));
    await official(pk.uid, i.issuance_id);
    const reseal = await codeOf(() => admin.query("UPDATE public.reporting_pack_issuances SET content_sha256=$2 WHERE id=$1", [i.issuance_id, "f".repeat(64)]));
    const events = (await admin.query("SELECT event, detail->>'generated_by' g FROM public.reporting_pack_issuance_events WHERE issuance_id=$1 ORDER BY event", [i.issuance_id])).rows.map((r) => `${r.event}:${r.g ?? ""}`);
    return clientIns === "42501" && svcIns === "42501" && evUpd === "P0001" && evDel === "P0001" && kindUpd === "P0001" && extend === "P0001" && reseal === "P0001"
      && JSON.stringify(events) === '["ISSUED:","SEALED:database"]' ? true : JSON.stringify({ clientIns, svcIns, evUpd, evDel, kindUpd, extend, reseal, events });
  });

  group("X-1 — an official Reporting Pack requires the exact FINAL publication of the saved version");
  await check("never published, DRAFT and REVIEWED-only versions cannot be officially issued (and the refusal is audited); nothing is issued, stored or sealed", async () => {
    const out = {};
    for (const state of [null, "DRAFT", "REVIEWED"]) {
      const ref = await savedOutput(pk.uid, pk.co, 2031, DOC, state);
      const before = await count("SELECT count(*) n FROM public.reporting_pack_issuances WHERE output_ref=$1", [ref]);
      const r = await issueO(pk.uid, pk.co, ref);
      const after = await count("SELECT count(*) n FROM public.reporting_pack_issuances WHERE output_ref=$1", [ref]);
      out[state ?? "unpublished"] = `${r.outcome}:${after - before}`;
    }
    const audited = await count("SELECT count(*) n FROM public.reporting_pack_issuance_events WHERE company_id=$1 AND event='REFUSED' AND detail->>'code'='FINAL_PUBLICATION_REQUIRED'", [pk.co]);
    return Object.values(out).every((x) => x === "final_publication_required:0") && audited >= 3 ? true : JSON.stringify({ out, audited });
  });
  await check("a working-copy issuance of a FINAL version (no bound publication) can never be sealed; the bound publication id is immutable and only data packs carry one", async () => {
    const w = await issue(pk.uid, pk.co, "financial_statements_data", R);
    const r = await official(pk.uid, w.issuance_id);
    const direct = (await one(SERVICE, "SELECT public.seal_reporting_pack_server($1,$2,$3) r", [pk.uid, w.issuance_id, `${pk.co}/${w.issuance_id}.json`])).r.outcome;
    const o = await issueO(pk.uid, pk.co, R);
    const rebind = await codeOf(() => admin.query("UPDATE public.reporting_pack_issuances SET final_publication_id=NULL WHERE id=$1", [o.issuance_id]));
    const other = await savedOutput(pk.uid, pk.co, 2031, DOC);
    const swap = await codeOf(() => admin.query("UPDATE public.reporting_pack_issuances SET final_publication_id=$2 WHERE id=$1", [o.issuance_id, pubOf.get(other)]));
    const kindCheck = await codeOf(() => admin.query(`INSERT INTO public.reporting_pack_issuances (company_id, period_year, pack_kind, request_id, issued_by, plan_code, output_ref, expires_at, final_publication_id)
      VALUES ($1,2031,'financial_statements_pdf',gen_random_uuid(),$2,'PRACTICE',$3,now() + interval '5 minutes',$4)`, [pk.co, pk.uid, R, pubOf.get(R)]));
    const bound = (await admin.query("SELECT final_publication_id f FROM public.reporting_pack_issuances WHERE id=$1", [o.issuance_id])).rows[0].f;
    return r.body.outcome === "final_publication_required" && direct === "final_publication_required" && (await sealsOf(w.issuance_id)) === 0 && !bucket.has(`${pk.co}/${w.issuance_id}.json`)
      && rebind === "P0001" && swap === "P0001" && kindCheck === "23514" && bound === pubOf.get(R)
      ? true : JSON.stringify({ r: r.body.outcome, direct, rebind, swap, kindCheck, bound, want: pubOf.get(R) });
  });
  await check("FINAL of another version, another period or another workspace never qualifies", async () => {
    // One report: v1 REVIEWED only, v2 FINAL. Only v2 qualifies.
    const rid = `r-${uuid()}`;
    const v1 = await savedOutput(pk.uid, pk.co, 2031, DOC, "REVIEWED", rid, 1);
    const v2 = await savedOutput(pk.uid, pk.co, 2031, { ...DOC, statements: { revenue: "2.00" } }, "FINAL", rid, 2);
    const onV1 = (await issueO(pk.uid, pk.co, v1)).outcome;
    const onV2 = (await issueO(pk.uid, pk.co, v2)).outcome;
    // A FINAL record forged under another workspace's id for this workspace's version is not this workspace's FINAL.
    const lone = `r-${uuid()}`;
    const x = await savedOutput(pk.uid, pk.co, 2031, DOC, null, lone, 1);
    await publish(pk.co, lone, 1, "FINAL", other.co);
    const foreignFinal = (await issueO(pk.uid, pk.co, x)).outcome;
    // Another period: a FINAL version of 2030 cannot be issued for 2031, and another workspace's FINAL version is not ours.
    const p30 = await savedOutput(pk.uid, pk.co, 2030, DOC);
    const wrongPeriod = (await issueO(pk.uid, pk.co, p30, 2031)).outcome;
    const RF = await savedOutput(other.uid, other.co, 2031, DOC);
    const foreignWs = (await issueO(pk.uid, pk.co, RF)).outcome;
    return onV1 === "final_publication_required" && onV2 === "issued" && foreignFinal === "final_publication_required" && wrongPeriod === "invalid_request" && foreignWs === "invalid_request"
      ? true : JSON.stringify({ onV1, onV2, foreignFinal, wrongPeriod, foreignWs });
  });
  await check("the canonical document names the exact FINAL publication; a later FINAL version leaves an issued historical pack unchanged and official", async () => {
    const rid = `r-${uuid()}`;
    const v1 = await savedOutput(pk.uid, pk.co, 2031, DOC, "FINAL", rid, 1);
    const i = await issueO(pk.uid, pk.co, v1);
    const r = await official(pk.uid, i.issuance_id);
    const doc = JSON.parse(r.body.document);
    await savedOutput(pk.uid, pk.co, 2031, { ...DOC, statements: { revenue: "5.00" } }, "FINAL", rid, 2);
    const obj = (await one(SERVICE, "SELECT public.reporting_pack_sealed_object($1) r", [i.issuance_id])).r;
    const still = await edgeVerify(pk.uid, i.issuance_id);
    return doc.publication.publication_id === pubOf.get(v1) && doc.publication.state === "FINAL" && /Z$/.test(doc.publication.published_at)
      && obj.canonical_sha256 === r.body.content_sha256 && still.official === true ? true : JSON.stringify({ pub: doc.publication, want: pubOf.get(v1), obj, still });
  });

  group("X-3 — only the byte re-hash route may say official");
  await check("the metadata-only RPC is gone: a signed-in caller gets no official answer from the database, and no public function returns an official flag", async () => {
    const i = await issueO(pk.uid, pk.co, R);
    const r = await official(pk.uid, i.issuance_id);
    const rpc = await codeOf(() => q(user(pk.uid), "SELECT public.verify_reporting_pack($1)", [r.body.content_sha256]));
    const sealedObj = await codeOf(() => q(user(pk.uid), "SELECT public.reporting_pack_sealed_object($1)", [i.issuance_id]));
    const svcFacts = (await one(SERVICE, "SELECT public.reporting_pack_sealed_object($1) r", [i.issuance_id])).r;
    const flagged = (await admin.query(`SELECT p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
      WHERE n.nspname='public' AND p.prokind='f' AND pg_get_functiondef(p.oid) ~ '''official'',\\s*true' AND has_function_privilege('authenticated', p.oid, 'EXECUTE')`)).rows.map((x) => x.proname);
    return rpc === "42883" && sealedObj === "42501" && !("official" in svcFacts) && flagged.length === 0 ? true : JSON.stringify({ rpc, sealedObj, svcFacts, flagged });
  });
  await check("canonical stored bytes → official; same-size substituted bytes, bytes gone with metadata left, and a missing object → not official", async () => {
    const i = await issueO(pk.uid, pk.co, R);
    const r = await official(pk.uid, i.issuance_id);
    const p = `${pk.co}/${i.issuance_id}.json`;
    const good = await edgeVerify(pk.uid, i.issuance_id);
    const orig = bucket.get(p);
    const same = Buffer.from(orig); same[same.length - 3] = same[same.length - 3] === 0x31 ? 0x32 : 0x31;   // one byte changed, same size
    bucket.set(p, new Uint8Array(same));
    const sameSize = await edgeVerify(pk.uid, i.issuance_id);
    const metaLeft = (await admin.query("SELECT (metadata->>'size')::bigint s FROM storage.objects WHERE bucket_id='reporting-packs' AND name=$1", [p])).rows[0]?.s;
    bucket.delete(p);   // the bytes are gone; storage.objects still records the object and its size
    const bytesGone = await edgeVerify(pk.uid, i.issuance_id);
    await dropObject(p);
    const missing = await edgeVerify(pk.uid, i.issuance_id);
    return good.official === true && good.outcome === "intact" && same.length === orig.length && Number(metaLeft) === orig.length
      && sameSize.official === false && sameSize.outcome === "substituted" && bytesGone.official === false && bytesGone.outcome === "missing"
      && missing.official === false && r.body.outcome === "sealed" ? true : JSON.stringify({ good, sameSize, bytesGone, missing });
  });

  group("Invariant and history across everything above");
  await check("for EVERY account: active named users <= included + purchased seats (or only the account holder when capacity is unknown)", async () => {
    const accounts = (await admin.query("SELECT DISTINCT user_id u FROM public.companies WHERE user_id IS NOT NULL")).rows.map((r) => r.u);
    const bad = []; for (const a of accounts) if (!(await invariant(a))) bad.push(a);
    return bad.length === 0 ? true : bad.join(",");
  });
  await check("no pre-existing audit row changed (billing audit and capability-grant events): later events are only appended", async () => {
    const now = await auditSnapshot();
    return JSON.stringify(now.slice(0, auditBefore.length)) === JSON.stringify(auditBefore) || auditBefore.every((row) => now.some((r) => JSON.stringify(r) === JSON.stringify(row)));
  });
  await check("the suspension and activity functions pin search_path, and clients can execute only the intended entry points", async () => {
    const rows = (await admin.query(`SELECT p.proname, p.proconfig, has_function_privilege('anon', p.oid, 'EXECUTE') anon, has_function_privilege('authenticated', p.oid, 'EXECUTE') auth
      FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname IN
      ('_account_named_user_access_active','named_user_access_active','_named_user_suspended','_named_user_roster','_apply_named_user_selection','choose_active_named_users',
       'get_named_user_roster','admin_prepare_planned_reduction','reconcile_named_user_allowance','reconcile_all_named_user_allowances','reserve_workspace_invitation',
       'release_workspace_invitation','cancel_workspace_invitation','seal_reporting_pack_server','issue_official_reporting_pack','issue_reporting_pack')`)).rows;
    const pinned = rows.every((r) => (r.proconfig ?? []).some((c) => c.startsWith("search_path=")));
    const byName = Object.fromEntries(rows.map((r) => [r.proname, r]));
    const clientOk = ["named_user_access_active", "choose_active_named_users", "get_named_user_roster", "admin_prepare_planned_reduction", "cancel_workspace_invitation", "issue_official_reporting_pack", "issue_reporting_pack"];
    const internal = ["_account_named_user_access_active", "_named_user_suspended", "_named_user_roster", "_apply_named_user_selection", "reconcile_named_user_allowance", "reconcile_all_named_user_allowances", "reserve_workspace_invitation", "release_workspace_invitation", "seal_reporting_pack_server"];
    return rows.length === 16 && pinned && rows.every((r) => !r.anon) && clientOk.every((n) => byName[n]?.auth) && internal.every((n) => byName[n] && !byName[n].auth)
      ? true : JSON.stringify(rows.map((r) => [r.proname, r.anon, r.auth]));
  });

  const failed = results.filter((r) => !r.ok);
  console.log(`\n──────────────────────────────────────────\nassertions: ${results.length}   passed: ${results.length - failed.length}   failed: ${failed.length}`);
  console.log(failed.length === 0 ? "BILLING_SUSPENSION: ALL PASSED" : "BILLING_SUSPENSION: FAILED");
  return failed.length === 0;
}

let ok = false;
try { ok = await main(); } catch (e) { console.error(`FATAL: ${e?.stack ?? e}`); } finally { await stopDatabase(); }
process.exitCode = ok ? 0 : 1;
