#!/usr/bin/env node
// Real-PostgreSQL proof of the seven self-checking release wrappers (release/wrappers/, generated by
// scripts/release/selfCheckingWrapper.mjs from the committed migration bytes).
//
// On a database at the schema of main before the release (the source chain through 20261010100000, with a drizzle
// journal whose head is hosted entry 0032), for EVERY wrapper, at the state just before it:
//   refusals   altered payload byte, altered expected SHA-256, altered expected byte count, CRLF transport damage,
//              truncation, damaged payload quoting, the contract probe — each refused BEFORE any migration statement
//              runs (no DDL event reaches ddl_command_start), leaving the catalogue fingerprint and the journal exactly
//              as they were;
//   failures   an execution failure injected early (third DDL command) and late (first GRANT) inside the migration —
//              rolled back completely: no partial object, no journal row;
//   executors  every case under (a) a plain autocommit statement (no transaction opened by anyone: the wrapper is one
//              statement) and (b) the hosted-executor MODEL (BEGIN; submitted text; journal row; COMMIT);
//   valid      the wrapper applies (odd ones in their registered final-LF-removed form), its journal row records the
//              SHA-256 of the submitted text, and a repeated application is refused with nothing changed.
// Then, on fresh copies, drizzle-orm's REAL migrate() (the version this repository pins; nothing reimplemented):
// the seven wrappers as seven journal entries apply and record seven rows (hash = SHA-256 of each wrapper file); a
// second migrate() is a no-op; a payload failure injected inside the fifth wrapper rolls back ALL FIVE and records no
// row (drizzle runs every pending entry and its journal row in one transaction); an altered wrapper is refused with
// nothing applied. The documented read-only postcondition passes after the release.
//
//   DB_PROOF_MODULES_DIR=<dir with node_modules/pg + embedded-postgres> node scripts/db-proof/selfCheckingWrappers.mjs
//   RELEASE_BATCH=reporting-r1 runs the same proof for the reporting release's five wrappers (default: i1b-signoff, the
//   applied milestone); the base is then main's schema through the migration before that batch.
//   DB_PROOF_MODE=external DB_PROOF_CONN=postgres://… (a throwaway loopback server; creates and drops its own databases)
// drizzle-orm must resolve `pg` (CI: `bun add --no-save --ignore-scripts pg@8`). Loopback only; refuses production.
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath, pathToFileURL } from "node:url";
import { currentChain, migrationSql } from "./lib/parkedMigrations.mjs";
import { RELEASE_BATCHES, committedSource, enclosedPayload, render, wrapperFile } from "../release/selfCheckingWrapper.mjs";

const BATCH = RELEASE_BATCHES.find((b) => b.id === (process.env.RELEASE_BATCH ?? "i1b-signoff"));
if (!BATCH) throw new Error(`unknown RELEASE_BATCH ${process.env.RELEASE_BATCH}`);
const WRAPPED_SOURCES = BATCH.sources;
const N = WRAPPED_SOURCES.length;
// The object a drizzle-run failure is injected at, inside the batch's last-but-one wrapper, and two tables that must not
// exist after the rolled-back run (the first wrapper's and that one's).
// `rolledBack` is the SQL that must answer true after the rolled-back run.
const tablesAbsent = (a, b) => `SELECT to_regclass('${a}') IS NULL AND to_regclass('${b}') IS NULL AS ok`;
const DRIZZLE_FAILURE = BATCH.id === "commercial-c1"
  ? { object: "public.workspace_purpose_events", rolledBack: "SELECT to_regclass('public.service_enquiry_replies') IS NULL AND to_regclass('public.workspace_purpose_events') IS NULL AND has_table_privilege('authenticated', 'public.aje_lines', 'INSERT') AND EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'aje_insert') AND position('company_year_end' IN pg_get_constraintdef((SELECT oid FROM pg_constraint WHERE conname = 'chk_fp_dates_basis'))) = 0 AS ok" }
  : BATCH.id === "reporting-r5"
  ? { object: "public.fs_signoff_policy_events", rolledBack: "SELECT to_regclass('public.fs_signoff_policy_events') IS NULL AND to_regprocedure('public.fs_set_signoff_policy(uuid,text,text,text,uuid)') IS NULL AS ok" }
  : BATCH.id === "reporting-r2"
  ? { object: "public.fs_report_readiness(pg_catalog.uuid,pg_catalog.text,integer)", rolledBack: "SELECT provolatile = 's' AS ok FROM pg_proc WHERE oid = 'public.fs_report_readiness(uuid,text,integer)'::regprocedure" }
  : BATCH.id === "reporting-r1"
  ? { object: "public.fs_publication_bindings", rolledBack: tablesAbsent("public.fs_presentation_lines", "public.fs_publication_bindings") }
  : { object: "public.close_review_adjustment_bindings", rolledBack: tablesAbsent("public.tb_source_objects", "public.close_review_findings") };
// Sources that only remove objects (their fingerprint shrinks when applied), and sources that only replace objects (the
// fingerprint changes; its object count is not asserted).
const REMOVES_ONLY = new Set(["20261026100000_retire_browser_adjusting_journal_writes.sql"]);
const REPLACES_ONLY = new Set(["20261028100000_period_dates_from_company.sql"]);
// Where an execution failure is injected inside each migration: "early" at the batch's earlyAt-th DDL command, "late" at
// its first lateTag command. The readiness correction (r2) has exactly one DDL command, ALTER FUNCTION: both points are
// that command, which proves the change itself is rolled back. Every other batch keeps DDL #3 and the first GRANT.
// The commercial candidate's retirement migration grants nothing (it drops policies and revokes) and its period migration
// revokes nothing (it replaces a function): its late point is the first REVOKE or CREATE FUNCTION, which every one of its
// four sources reaches after at least three DDL commands.
const SHAPE = BATCH.id === "reporting-r2" ? { earlyAt: 1, lateTag: "ALTER FUNCTION", minDdl: 1 }
  : BATCH.id === "commercial-c1" ? { earlyAt: 3, lateTag: "REVOKE','CREATE FUNCTION", minDdl: 3 } : { earlyAt: 3, lateTag: "GRANT", minDdl: 3 };

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, "../..");
const PRODUCTION_REF = "bvyivmmfjejbmqoydezk";
const PG_CRON_FILE = "20260810044930_fcf7b034-7dc7-445d-a77d-99be66c3c4f4.sql";
const MODULES_DIR = process.env.DB_PROOF_MODULES_DIR;
const req = createRequire(MODULES_DIR ? path.join(path.resolve(MODULES_DIR), "noop.js") : import.meta.url);
const { Client, Pool } = req("pg");
const sha256 = (b) => crypto.createHash("sha256").update(b).digest("hex");

const results = [];
let currentGroup = "";
const group = (n) => { currentGroup = n; console.log(`\n== ${n}`); };
function record(name, ok, detail = "") { results.push({ group: currentGroup, name, ok }); console.log(`  ${ok ? "PASS" : "FAIL"}  ${name}${ok || !detail ? "" : `\n        ${detail}`}`); }
async function check(name, fn) {
  try { const r = await fn(); record(name, r === true, r === true ? "" : `assertion returned ${JSON.stringify(r)?.slice(0, 900)}`); }
  catch (e) { record(name, false, `exception ${e.code ?? ""}: ${String(e?.message ?? e).split("\n")[0]}`); }
}

// ── Server ──────────────────────────────────────────────────────────────────────────────────────────────────────────
let server = null, dir = null, baseUrl;
async function startServer() {
  if ((process.env.DB_PROOF_MODE ?? "embedded") === "external") {
    const conn = process.env.DB_PROOF_CONN ?? "";
    const u = new URL(conn);
    if (!["localhost", "127.0.0.1", "::1", "[::1]"].includes(u.hostname) || conn.includes(PRODUCTION_REF)) throw new Error("REFUSED: not a loopback database");
    return conn;
  }
  const modDir = MODULES_DIR ? path.resolve(MODULES_DIR) : REPO;
  const { default: EmbeddedPostgres } = await import(pathToFileURL(path.join(modDir, "node_modules/embedded-postgres/dist/index.js")).href);
  dir = fs.mkdtempSync(path.join(os.tmpdir(), "cfoclose-wrappers-"));
  const port = 59000 + Math.floor(Math.random() * 900);
  server = new EmbeddedPostgres({ databaseDir: path.join(dir, "data"), user: "postgres", password: "postgres", port, persistent: false, initdbFlags: ["--encoding=UTF8", "--locale=C"], onLog: () => {}, onError: () => {} });
  await server.initialise(); await server.start();
  return `postgres://postgres:postgres@localhost:${port}/postgres`;
}
const urlFor = (db) => { const u = new URL(baseUrl); u.pathname = `/${db}`; return u.toString(); };
async function maintenance(sql) { const c = new Client({ connectionString: urlFor(new URL(baseUrl).pathname.slice(1) || "postgres") }); await c.connect(); try { await c.query(sql); } finally { await c.end(); } }
const created = [];
async function cloneDb(name, template) { await maintenance(`DROP DATABASE IF EXISTS ${name}`); await maintenance(`CREATE DATABASE ${name}${template ? ` TEMPLATE ${template}` : ""}`); created.push(name); return urlFor(name); }
async function connect(url) { const c = new Client({ connectionString: url }); await c.connect(); return c; }

// ── The base: main's schema before the release, and a drizzle journal whose head is hosted entry 0032 ─────────────────
const DZ = path.join(REPO, "drizzle/migrations");
const JOURNAL = JSON.parse(fs.readFileSync(path.join(DZ, "meta/_journal.json"), "utf8"));
const HEAD_ENTRY = JOURNAL.entries[JOURNAL.entries.length - 1];
async function buildBase(url) {
  const c = await connect(url);
  try {
    await c.query(fs.readFileSync(path.join(REPO, "scripts/db-contract-tests/00_bootstrap_roles_and_shims.sql"), "utf8"));
    await c.query(`GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
      ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
      ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
      ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO anon, authenticated, service_role;
      CREATE SCHEMA IF NOT EXISTS extensions; GRANT USAGE ON SCHEMA extensions TO anon, authenticated, service_role;
      CREATE OR REPLACE FUNCTION extensions.digest(text, text) RETURNS bytea LANGUAGE sql IMMUTABLE STRICT AS 'SELECT public.digest($1, $2)';`);
    const chain = currentChain(REPO);
    // The seven are consecutive in the chain; later migrations belong to later releases and are not part of this proof.
    const first = chain.indexOf(WRAPPED_SOURCES[0]);
    const run = chain.slice(first, first + WRAPPED_SOURCES.length);
    if (first < 0 || JSON.stringify(run) !== JSON.stringify(WRAPPED_SOURCES)) throw new Error(`the ${N} wrapped sources are not consecutive in the chain: ${run}`);
    for (const f of chain.slice(0, first)) {
      let t = migrationSql(REPO, f);
      if (f === PG_CRON_FILE) t = t.split("\n").slice(0, t.split("\n").findIndex((l) => l.includes("CREATE EXTENSION IF NOT EXISTS pg_cron"))).join("\n");
      await c.query(t);
    }
    // The journal exactly as drizzle-orm creates it (drizzle-orm pg-core dialect migrate()), its head = hosted 0032.
    await c.query(`CREATE SCHEMA IF NOT EXISTS drizzle;
      CREATE TABLE IF NOT EXISTS drizzle.__drizzle_migrations (id SERIAL PRIMARY KEY, hash text NOT NULL, created_at bigint)`);
    await c.query("INSERT INTO drizzle.__drizzle_migrations (hash, created_at) VALUES ($1, $2)", [sha256(fs.readFileSync(path.join(DZ, `${HEAD_ENTRY.tag}.sql`))), HEAD_ENTRY.when]);
  } finally { await c.end(); }
}

// Everything a migration could create or change, plus the journal; the injection helpers live in schema proof_inject
// (present before and after every comparison, so they cancel out).
const FINGERPRINT = `SELECT md5(string_agg(x, E'\\n' ORDER BY x)) AS f, count(*) AS n FROM (
  SELECT 'n:' || nspname FROM pg_namespace WHERE nspname NOT LIKE 'pg\\_%' AND nspname <> 'information_schema'
  UNION ALL SELECT 'c:' || c.oid::regclass::text || ':' || c.relkind::text || ':' || c.relrowsecurity::text || ':' || coalesce(array_to_string(c.relacl, ','), '')
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname NOT LIKE 'pg\\_%' AND n.nspname <> 'information_schema'
  UNION ALL SELECT 'a:' || a.attrelid::regclass::text || '.' || a.attname || ':' || format_type(a.atttypid, a.atttypmod) || ':' || a.attnotnull::text
    FROM pg_attribute a JOIN pg_class c ON c.oid = a.attrelid JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname NOT LIKE 'pg\\_%' AND n.nspname <> 'information_schema' AND a.attnum > 0 AND NOT a.attisdropped
  UNION ALL SELECT 'p:' || p.oid::regprocedure::text || ':' || md5(p.prosrc) || ':' || coalesce(array_to_string(p.proacl, ','), '')
         || ':' || p.provolatile::text || ':' || p.prosecdef::text || ':' || coalesce(array_to_string(p.proconfig, ','), '')
    FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname NOT LIKE 'pg\\_%' AND n.nspname <> 'information_schema'
  UNION ALL SELECT 't:' || tgrelid::regclass::text || '.' || tgname || ':' || tgenabled::text FROM pg_trigger WHERE NOT tgisinternal
  UNION ALL SELECT 'pol:' || polrelid::regclass::text || '.' || polname FROM pg_policy
  UNION ALL SELECT 'con:' || conrelid::regclass::text || '.' || conname FROM pg_constraint WHERE conrelid <> 0
  UNION ALL SELECT 'ty:' || t.oid::regtype::text FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
   WHERE n.nspname NOT LIKE 'pg\\_%' AND n.nspname <> 'information_schema' AND t.typtype IN ('e', 'd', 'c') AND t.typrelid = 0
  UNION ALL SELECT 'rows:' || c.oid::regclass::text || ':' || (xpath('/row/n/text()', query_to_xml(format('SELECT count(*) AS n FROM %s', c.oid::regclass), false, true, '')))[1]::text
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relkind = 'r' AND n.nspname IN ('public', 'drizzle', 'storage')
  UNION ALL SELECT 'j:' || id || ':' || hash || ':' || coalesce(created_at::text, '') FROM drizzle.__drizzle_migrations
) s(x)`;
const fingerprint = async (c) => (await c.query(FINGERPRINT)).rows[0];
const journalRows = async (c) => (await c.query("SELECT id, hash, created_at::text AS created_at FROM drizzle.__drizzle_migrations ORDER BY id")).rows;

// DDL events reach ddl_command_start before any DDL statement runs; a NOTICE is delivered even when the transaction rolls
// back, so it is a side channel that survives the rollback it observes.
const INJECT = `CREATE SCHEMA IF NOT EXISTS proof_inject;
  CREATE TABLE IF NOT EXISTS proof_inject.config (singleton boolean PRIMARY KEY DEFAULT true, mode text NOT NULL DEFAULT 'off');
  INSERT INTO proof_inject.config DEFAULT VALUES ON CONFLICT DO NOTHING;
  CREATE OR REPLACE FUNCTION proof_inject.on_start() RETURNS event_trigger LANGUAGE plpgsql AS $f$
  BEGIN RAISE NOTICE 'PROOF_DDL_START %', tg_tag; END $f$;
  CREATE OR REPLACE FUNCTION proof_inject.on_end() RETURNS event_trigger LANGUAGE plpgsql AS $f$
  DECLARE v_mode text; v_n integer; r record;
  BEGIN
    SELECT mode INTO v_mode FROM proof_inject.config;
    v_n := coalesce(nullif(current_setting('proof_inject.n', true), ''), '0')::integer + 1;
    PERFORM set_config('proof_inject.n', v_n::text, true);
    IF v_mode = 'early' AND v_n = ${SHAPE.earlyAt} THEN RAISE EXCEPTION 'PROOF_INJECTED_FAILURE early at DDL #% (%)', v_n, tg_tag USING ERRCODE = 'XX000'; END IF;
    IF v_mode = 'late' AND tg_tag IN ('${SHAPE.lateTag}') THEN RAISE EXCEPTION 'PROOF_INJECTED_FAILURE late at % after % DDL commands', tg_tag, v_n USING ERRCODE = 'XX000'; END IF;
    IF v_mode LIKE 'object:%' THEN
      FOR r IN SELECT object_identity FROM pg_event_trigger_ddl_commands() LOOP
        IF r.object_identity = substr(v_mode, 8) THEN RAISE EXCEPTION 'PROOF_INJECTED_FAILURE at %', r.object_identity USING ERRCODE = 'XX000'; END IF;
      END LOOP;
    END IF;
  END $f$;
  DROP EVENT TRIGGER IF EXISTS proof_inject_start; DROP EVENT TRIGGER IF EXISTS proof_inject_end;
  CREATE EVENT TRIGGER proof_inject_start ON ddl_command_start EXECUTE FUNCTION proof_inject.on_start();
  CREATE EVENT TRIGGER proof_inject_end ON ddl_command_end EXECUTE FUNCTION proof_inject.on_end();`;
const setInjection = (c, mode) => c.query("UPDATE proof_inject.config SET mode = $1", [mode]);

// ── Executors ────────────────────────────────────────────────────────────────────────────────────────────────────────
/** Runs `text` and reports { ok, code, message, ddlStarted } — DDL starts counted from the NOTICE side channel. */
async function run(c, text, { model }) {
  const notices = [];
  const on = (m) => { if (String(m.message).startsWith("PROOF_DDL_START")) notices.push(m.message); };
  c.on("notice", on);
  try {
    if (model) {
      // MODEL of the stated hosted contract: one submitted string, its journal row, one transaction.
      await c.query("BEGIN");
      try {
        await c.query(text);
        await c.query("INSERT INTO drizzle.__drizzle_migrations (hash, created_at) VALUES ($1, $2)", [sha256(Buffer.from(text, "utf8")), Date.now()]);
        await c.query("COMMIT");
      } catch (e) { await c.query("ROLLBACK"); throw e; }
    } else {
      await c.query(text); // autocommit: nobody opens a transaction; the wrapper is one statement
    }
    return { ok: true, ddlStarted: notices.length };
  } catch (e) {
    return { ok: false, code: e.code, message: String(e.message).split("\n")[0], ddlStarted: notices.length };
  } finally { c.off("notice", on); }
}

const wrapperText = (source) => fs.readFileSync(path.join(REPO, wrapperFile(source)), "utf8");
function variants(source, text) {
  const tag = /\$cfoclose_payload_[0-9a-f]{16}\$/.exec(text)[0];
  const payloadStart = text.indexOf(tag) + tag.length;
  const payloadEnd = text.indexOf(tag, payloadStart);
  // A byte inside the payload's first comment line: SQL stays valid, the payload bytes change.
  const commentAt = text.indexOf("--", payloadStart) + 3;
  const flip = (s, i) => s.slice(0, i) + (s[i] === "a" ? "b" : "a") + s.slice(i + 1);
  const sha = /c_sha256  CONSTANT text    := '([0-9a-f]{64})'/.exec(text);
  const bytes = /c_bytes   CONSTANT integer := (\d+);/.exec(text);
  return {
    "altered payload byte": { text: flip(text, commentAt), expect: "55000" },
    "altered expected SHA-256": { text: text.replace(sha[0], sha[0].replace(sha[1], (sha[1][0] === "0" ? "1" : "0") + sha[1].slice(1))), expect: "55000" },
    "altered expected byte count": { text: text.replace(bytes[0], `c_bytes   CONSTANT integer := ${Number(bytes[1]) + 1};`), expect: "55000" },
    "CRLF transport damage": { text: text.replace(/\n/g, "\r\n"), expect: "55000" },
    "truncated in the payload": { text: text.slice(0, payloadStart + Math.floor((payloadEnd - payloadStart) * 0.6)), expect: "syntax" },
    "truncated after the payload": { text: text.slice(0, payloadEnd + tag.length + 40), expect: "syntax" },
    "damaged closing payload quote": { text: text.slice(0, payloadEnd) + tag.replace("payload", "paylaod") + text.slice(payloadEnd + tag.length), expect: "syntax" },
    "payload quote removed": { text: text.slice(0, payloadStart - tag.length) + "'" + text.slice(payloadStart, payloadEnd) + "'" + text.slice(payloadEnd + tag.length), expect: "syntax" },
    "the contract probe": { text: fs.readFileSync(path.join(REPO, "release/wrappers/contract_probe.sql"), "utf8"), expect: "55000" },
  };
}
const refusedAsExpected = (r, expect) => !r.ok && (expect === "syntax" ? ["42601", "42P01", "42883", "42703", "22P02"].includes(r.code) || /syntax|unterminated/i.test(r.message) : r.code === expect);

async function main() {
  baseUrl = await startServer();
  group("Generation — every wrapper is render() of the committed source; the payload is those bytes exactly");
  await check("each file in release/wrappers equals render(committed source) and encloses exactly the committed bytes", async () => {
    const bad = [];
    for (const s of WRAPPED_SOURCES) {
      const committed = committedSource(s, BATCH.commit);
      const file = fs.readFileSync(path.join(REPO, wrapperFile(s)));
      if (!file.equals(Buffer.from(render(s, committed, BATCH.commit), "utf8"))) bad.push(`${s}: not render()`);
      if (!enclosedPayload(file.toString("utf8"))?.equals(committed)) bad.push(`${s}: payload differs`);
      if (!committed.equals(fs.readFileSync(path.join(REPO, "supabase/migrations", s)))) bad.push(`${s}: working tree differs from the committed source`);
    }
    return bad.length === 0 ? true : bad;
  });

  group(`Base — main's schema before the ${BATCH.id} release; journal head = ${HEAD_ENTRY.tag}`);
  const baseDb = "wrappers_base";
  await check(`the source chain before ${WRAPPED_SOURCES[0]} applies; the journal head is ${HEAD_ENTRY.tag}`, async () => {
    await buildBase(await cloneDb(baseDb));
    const c = await connect(urlFor(baseDb));
    try { await c.query(INJECT); const j = await journalRows(c); return j.length === 1 && Number(j[0].created_at) === HEAD_ENTRY.when ? true : j; } finally { await c.end(); }
  });

  // ── Per wrapper, at the state just before it ──────────────────────────────────────────────────────────────────
  const stepUrl = await cloneDb("wrappers_step", baseDb);
  const c = await connect(stepUrl);
  try {
    for (const [i, s] of WRAPPED_SOURCES.entries()) {
      group(`Wrapper ${i + 1}/${N} — ${s}`);
      const text = wrapperText(s);
      for (const [label, v] of Object.entries(variants(s, text))) {
        for (const model of [false, true]) {
          await check(`${label} (${model ? "hosted-executor model" : "autocommit"}): refused before any migration statement; nothing changed, no journal row`, async () => {
            const before = await fingerprint(c);
            const r = await run(c, v.text, { model });
            const after = await fingerprint(c);
            return refusedAsExpected(r, v.expect) && r.ddlStarted === 0 && before.f === after.f ? true : { r, same: before.f === after.f };
          });
        }
      }
      for (const mode of ["early", "late"]) {
        for (const model of [false, true]) {
          await check(`execution failure injected ${mode} inside the migration (${model ? "hosted-executor model" : "autocommit"}): fully rolled back, no partial object, no journal row`, async () => {
            let before, r;
            await setInjection(c, mode);
            try { before = await fingerprint(c); r = await run(c, text, { model }); } finally { await setInjection(c, "off"); }
            const after = await fingerprint(c);
            return !r.ok && r.code === "XX000" && /PROOF_INJECTED_FAILURE/.test(r.message) && r.ddlStarted >= SHAPE.minDdl && before.f === after.f ? true : { r, same: before.f === after.f };
          });
        }
      }
      const form = i % 2 === 0 ? "final-LF-removed form" : "identical form";
      const submitted = i % 2 === 0 ? text.slice(0, -1) : text;
      await check(`valid (${form}, hosted-executor model): applies (the fingerprint sees it); one journal row = SHA-256 of the submitted text`, async () => {
        const j0 = await journalRows(c);
        const f0 = await fingerprint(c);
        const r = await run(c, submitted, { model: true });
        const f1 = await fingerprint(c);
        const j1 = await journalRows(c);
        const added = j1.slice(j0.length);
        // The fingerprint must SEE the migration (otherwise "unchanged" above would prove nothing).
        // A migration that only removes (the browser-write retirement drops policies and revokes) shrinks the fingerprint.
        const grew = REMOVES_ONLY.has(s) ? Number(f1.n) < Number(f0.n) : REPLACES_ONLY.has(s) ? true : Number(f1.n) > Number(f0.n);
        return r.ok && f0.f !== f1.f && grew && added.length === 1 && added[0].hash === sha256(Buffer.from(submitted, "utf8")) ? true : { r, added, sees: f0.f !== f1.f };
      });
      for (const model of [false, true]) {
        await check(`repeated application (${model ? "hosted-executor model" : "autocommit"}): refused by the migration's own preflight; nothing changed, no journal row`, async () => {
          const before = await fingerprint(c);
          const r = await run(c, text, { model });
          const after = await fingerprint(c);
          return !r.ok && r.code === "P0001" && /PREFLIGHT_REFUSED/.test(r.message) && before.f === after.f ? true : { r, same: before.f === after.f };
        });
      }
    }
    group(`After the ${N} — the documented read-only postcondition`);
    await check("postcondition.sql passes in a READ ONLY transaction", async () => {
      await c.query("DROP EVENT TRIGGER IF EXISTS proof_inject_start; DROP EVENT TRIGGER IF EXISTS proof_inject_end");
      const notices = []; const on = (m) => notices.push(m.message); c.on("notice", on);
      await c.query("BEGIN READ ONLY");
      try { await c.query(fs.readFileSync(path.join(REPO, BATCH.postcondition), "utf8")); } finally { await c.query("ROLLBACK"); c.off("notice", on); }
      return notices.includes("POSTCONDITION OK.") ? true : notices;
    });
    await check(`the journal holds exactly its head plus ${N} rows, one per wrapper, in order`, async () => {
      const j = await journalRows(c);
      return j.length === 1 + WRAPPED_SOURCES.length ? true : j.length;
    });
  } finally { await c.end(); }

  // ── drizzle-orm's real migrate() ─────────────────────────────────────────────────────────────────────────────────
  group("drizzle-orm migrate() — the repository-pinned migrator, not a model");
  const { drizzle } = await import("drizzle-orm/node-postgres");
  const { migrate } = await import("drizzle-orm/node-postgres/migrator");
  const folderWith = (texts) => {
    const d = fs.mkdtempSync(path.join(os.tmpdir(), "wrappers-drizzle-"));
    fs.cpSync(DZ, d, { recursive: true });
    const j = JSON.parse(fs.readFileSync(path.join(d, "meta/_journal.json"), "utf8"));
    texts.forEach((t, k) => {
      const idx = j.entries.length;
      const tag = `${String(idx).padStart(4, "0")}_wrapper_${WRAPPED_SOURCES[k].slice(0, 14)}`;
      j.entries.push({ ...j.entries[idx - 1], idx, tag, when: HEAD_ENTRY.when + (k + 1) * 1000 });
      fs.writeFileSync(path.join(d, `${tag}.sql`), t);
    });
    fs.writeFileSync(path.join(d, "meta/_journal.json"), JSON.stringify(j, null, 2));
    return d;
  };
  const migrateOn = async (url, folder) => {
    const pool = new Pool({ connectionString: url, max: 2 });
    try { await migrate(drizzle(pool), { migrationsFolder: folder }); return { ok: true }; }
    catch (e) { return { ok: false, message: String(e?.cause?.message ?? e?.message ?? e).split("\n")[0] }; }
    finally { await pool.end(); }
  };
  const texts = WRAPPED_SOURCES.map(wrapperText);
  await check(`the ${N} wrappers as ${N} entries: all apply; ${N} journal rows, each hash = SHA-256 of its wrapper file; a second migrate() changes nothing`, async () => {
    const url = await cloneDb("wrappers_drizzle_ok", baseDb);
    const folder = folderWith(texts);
    const r = await migrateOn(url, folder);
    const c2 = await connect(url);
    try {
      const j = await journalRows(c2);
      const f1 = await fingerprint(c2);
      const again = await migrateOn(url, folder);
      const f2 = await fingerprint(c2);
      const hashesOk = JSON.stringify(j.slice(1).map((x) => x.hash)) === JSON.stringify(texts.map((t) => sha256(Buffer.from(t, "utf8"))));
      return r.ok && again.ok && j.length === 1 + N && hashesOk && f1.f === f2.f ? true : { r, again, rows: j.length, hashesOk };
    } finally { await c2.end(); }
  });
  const failLabel = N > 1 ? `a failure injected inside wrapper ${N - 1} rolls back all ${N - 1} before it and records no journal row`
    : "a failure injected inside the wrapper rolls it back and records no journal row";
  await check(failLabel, async () => {
    const url = await cloneDb("wrappers_drizzle_fail", baseDb);
    const c3 = await connect(url);
    try {
      await setInjection(c3, `object:${DRIZZLE_FAILURE.object}`);
      const before = await fingerprint(c3);
      const r = await migrateOn(url, folderWith(texts));
      const after = await fingerprint(c3);
      const rolledBack = (await c3.query(DRIZZLE_FAILURE.rolledBack)).rows[0]?.ok === true;
      return !r.ok && /PROOF_INJECTED_FAILURE/.test(r.message) && before.f === after.f && rolledBack ? true : { r, same: before.f === after.f, rolledBack };
    } finally { await c3.end(); }
  });
  const ALTERED = Math.min(2, N - 1);
  await check(`an altered ${N > 2 ? "third" : "last"} wrapper (one payload byte) is refused: nothing applied, no journal row`, async () => {
    const url = await cloneDb("wrappers_drizzle_altered", baseDb);
    const altered = [...texts];
    altered[ALTERED] = variants(WRAPPED_SOURCES[ALTERED], texts[ALTERED])["altered payload byte"].text;
    const c4 = await connect(url);
    try {
      const before = await fingerprint(c4);
      const r = await migrateOn(url, folderWith(altered));
      const after = await fingerprint(c4);
      return !r.ok && /RELEASE_PAYLOAD_MISMATCH/.test(r.message) && before.f === after.f ? true : { r, same: before.f === after.f };
    } finally { await c4.end(); }
  });
}

let crashed = false;
try { await main(); } catch (e) { crashed = true; console.error(`\nINFRASTRUCTURE FAILURE: ${e?.stack ?? e}`); }
const failed = results.filter((r) => !r.ok);
console.log("\n──────────────────────────────────────────");
console.log(`assertions: ${results.length}   passed: ${results.length - failed.length}   failed: ${failed.length}`);
for (const f of failed) console.log(`  FAILED [${f.group}] ${f.name}`);
const ok = !crashed && failed.length === 0 && results.length > 0;
console.log(ok ? `SELF_CHECKING_WRAPPERS (${BATCH.id}): ALL PASSED` : `SELF_CHECKING_WRAPPERS (${BATCH.id}): FAILED`);
for (const d of created) { try { await maintenance(`DROP DATABASE IF EXISTS ${d} WITH (FORCE)`); } catch { /* */ } }
if (server) { try { await Promise.race([server.stop(), new Promise((r) => setTimeout(r, 5000))]); } catch { /* */ } }
if (dir) { try { fs.rmSync(dir, { recursive: true, force: true }); } catch { /* */ } }
process.exit(ok ? 0 : 1);
