-- CFOClose self-checking release wrapper. GENERATED by scripts/release/selfCheckingWrapper.mjs — do not edit.
-- Applies supabase/migrations/20261016100000_fs_reporting_input.sql
-- exactly as committed at 993774cd129a4bfd16946f6be1c339aaf93ac5d4: 11306 bytes, SHA-256 d6c019785cdd67301c539bfc7d4c413e365c917039da4dc27adcb4128c3a3a39.
-- ONE statement. Before any statement of the enclosed migration runs, PostgreSQL recomputes the payload's byte count
-- and SHA-256 and refuses (SQLSTATE 55000, nothing changed) unless both equal the identity below. Any failure inside
-- the migration rolls the whole statement back. Submit this file byte for byte.
DO $cfoclose_release_d6c019785cdd6730$
DECLARE
  c_source  CONSTANT text    := '20261016100000_fs_reporting_input.sql';
  c_bytes   CONSTANT integer := 11306;
  c_sha256  CONSTANT text    := 'd6c019785cdd67301c539bfc7d4c413e365c917039da4dc27adcb4128c3a3a39';
  c_payload CONSTANT text    := $cfoclose_payload_d6c019785cdd6730$-- ════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
-- Financial Statements — the authoritative reporting input (roadmap increment 11, foundation).
--
-- fs_reporting_input(company, year) is the ONE read the financial-statements workspace uses for figures:
--   (Adjustments: exactly those that APPLY to each certification — approved against it, or explicitly revalidated to
--   it after a re-check; one shared definition, _cr_adjustment_applies_to.)
--   current      the AUTHORITATIVE certification of the year (get_authoritative_certification — read-time authority,
--                staleness and invalidation included) with the approved adjustments bound to it applied as a layer
--                (close_review_adjusted_trial_balance), per account, in exact minor units, with the account's reviewed
--                placement (account_mappings) and its lineage: the certification, the upload, and every approved
--                adjustment that touched it;
--   comparative  the year before AS REPORTED: its authoritative certification with its own approved adjustments, or the
--                exact reason it is missing — a non-authoritative upload is never substituted;
--   adjustments  every approved adjustment applied, with whether it was self-approved (disclosure);
--   findings     the Close Review findings summary (unresolved blocking findings block Reviewed/Final, I8);
--   inputSha256  SHA-256 of the canonical identity of all of the above (certifications, adjustments, findings run):
--                a saved report records it; when it changes the report is stale.
-- Nothing here writes. Readable by members with workspace access while the financial-statements rollout allows the
-- company. No tax engine output is read (revision 5 §1.5).
--
-- PREFLIGHT: the function does not exist yet; the migration refuses if it does.
-- ════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

DO $preflight$
BEGIN
  IF to_regprocedure('public.fs_reporting_input(uuid, integer)') IS NOT NULL THEN
    RAISE EXCEPTION 'PREFLIGHT_REFUSED: fs_reporting_input already exists; nothing was changed' USING ERRCODE = 'P0001';
  END IF;
END;
$preflight$;

-- One period's accounts: its authoritative certification with the approved adjustments bound to it applied as a layer,
-- with the reviewed placement and the lineage (adjustments) of every account. Used for both the current and the
-- comparative period: a comparative is the prior year as it was reported (its own approved adjustments included).
CREATE OR REPLACE FUNCTION public._fs_adjusted_accounts(p_company_id uuid, p_period_year integer, p_certification_id uuid)
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
           'accountKey', l.account_key, 'accountCode', l.account_code, 'accountName', COALESCE(m.account_name, l.account_name),
           'statement', m.statement::text, 'classification', COALESCE(m.classification::text, l.classification), 'normalBalance', m.normal_balance,
           'isCashAccount', m.is_cash_account, 'isRetainedEarnings', m.is_retained_earnings, 'isPayrollAccount', m.is_payroll_account,
           'certifiedDebitMinor', l.certified_debit_minor::text, 'certifiedCreditMinor', l.certified_credit_minor::text,
           'adjustmentDebitMinor', l.adjustment_debit_minor::text, 'adjustmentCreditMinor', l.adjustment_credit_minor::text,
           'debitMinor', l.adjusted_debit_minor::text, 'creditMinor', l.adjusted_credit_minor::text,
           'adjustmentIds', COALESCE((SELECT jsonb_agg(DISTINCT x.id) FROM public.close_review_adjustments x
                                       JOIN public.close_review_adjustment_lines xl ON xl.adjustment_id = x.id
                                      WHERE x.company_id = p_company_id AND x.period_year = p_period_year
                                        AND xl.account_key = l.account_key AND public._cr_adjustment_applies_to(x.id, p_certification_id)), '[]'::jsonb))
         ORDER BY l.account_key), '[]'::jsonb)
    FROM public.close_review_adjusted_trial_balance(p_company_id, p_period_year) l
    LEFT JOIN public.account_mappings m ON m.company_id = p_company_id AND m.account_key = l.account_key
   WHERE l.certification_id = p_certification_id;
$$;

-- The approved adjustments applied to one period (for disclosure and identity).
CREATE OR REPLACE FUNCTION public._fs_applied_adjustments(p_company_id uuid, p_period_year integer, p_certification_id uuid)
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
  SELECT COALESCE(jsonb_agg(jsonb_build_object('id', x.id, 'number', x.number, 'kind', x.kind, 'reverses', x.reverses_id, 'totalMinor', x.total_minor::text,
           'reason', x.reason, 'selfApproved', COALESCE((SELECT (e.detail->>'selfApproved')::boolean FROM public.close_review_events e
             WHERE e.subject_kind = 'adjustment' AND e.subject_id = x.id::text AND e.event_type = 'adjustment_approved' LIMIT 1), false),
           -- Carried to this certification by its own proposer under the self-approval policy: disclosed like a self-approval.
           'selfRevalidated', EXISTS (SELECT 1 FROM public.close_review_adjustment_bindings b WHERE b.adjustment_id = x.id
             AND b.to_certification_id = p_certification_id AND b.decision = 'revalidated' AND b.self_approved))
         ORDER BY x.number), '[]'::jsonb)
    FROM public.close_review_adjustments x
   WHERE x.company_id = p_company_id AND x.period_year = p_period_year AND public._cr_adjustment_applies_to(x.id, p_certification_id);
$$;

CREATE OR REPLACE FUNCTION public._fs_period_meta(p_company_id uuid, p_certification_id uuid)
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
  SELECT jsonb_build_object('certificationId', c.id, 'uploadId', c.upload_id, 'periodYear', c.period_year, 'certifiedAt', c.certified_at,
           'periodId', t.period_id, 'currency', p.reporting_currency, 'exponent', cr.exponent,
           'reportingStart', p.reporting_start, 'reportingEnd', COALESCE(p.reporting_end, p.fiscal_year_end),
           'exact', NOT EXISTS (SELECT 1 FROM public._cr_certified_accounts(c.id) x WHERE NOT x.exact))
    FROM public.tb_certifications c
    JOIN public.trial_balance_uploads t ON t.id = c.upload_id
    LEFT JOIN public.fiscal_periods p ON p.id = t.period_id AND p.company_id = p_company_id
    LEFT JOIN public.currency_registry cr ON cr.code = p.reporting_currency
   WHERE c.id = p_certification_id;
$$;

CREATE OR REPLACE FUNCTION public.fs_reporting_input(p_company_id uuid, p_period_year integer)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE
  v_cert uuid;
  v_prior uuid;
  v_current jsonb;
  v_accounts jsonb;
  v_comparative jsonb;
  v_adjustments jsonb;
  v_findings jsonb;
  v_identity jsonb;
BEGIN
  IF p_company_id IS NULL OR p_period_year IS NULL THEN RETURN jsonb_build_object('state', 'invalid_request'); END IF;
  IF NOT public.close_review_readable(p_company_id) THEN RETURN jsonb_build_object('state', 'unavailable'); END IF;
  SELECT c.id INTO v_cert FROM public.get_authoritative_certification(p_company_id, p_period_year) c;
  IF v_cert IS NULL THEN RETURN jsonb_build_object('state', 'no_authority', 'periodYear', p_period_year); END IF;
  v_current := public._fs_period_meta(p_company_id, v_cert);
  IF NOT (v_current->>'exact')::boolean THEN RETURN jsonb_build_object('state', 'legacy_certification', 'periodYear', p_period_year); END IF;
  IF v_current->>'currency' IS NULL OR v_current->>'exponent' IS NULL THEN RETURN jsonb_build_object('state', 'currency_unknown', 'periodYear', p_period_year); END IF;

  v_accounts := public._fs_adjusted_accounts(p_company_id, p_period_year, v_cert);
  v_adjustments := public._fs_applied_adjustments(p_company_id, p_period_year, v_cert);

  -- Comparative: the authoritative prior year, or why there is none (never a substitute).
  SELECT c.id INTO v_prior FROM public.get_authoritative_certification(p_company_id, p_period_year - 1) c;
  IF v_prior IS NULL THEN
    v_comparative := jsonb_build_object('state', CASE WHEN EXISTS (SELECT 1 FROM public.trial_balance_uploads t
                                                                    WHERE t.company_id = p_company_id AND t.period_year = p_period_year - 1)
                                                      THEN 'not_authoritative' ELSE 'missing' END,
                                        'periodYear', p_period_year - 1);
  ELSE
    v_comparative := public._fs_period_meta(p_company_id, v_prior)
      || jsonb_build_object('state', CASE WHEN (public._fs_period_meta(p_company_id, v_prior)->>'exact')::boolean THEN 'available' ELSE 'legacy_certification' END,
                            'accounts', public._fs_adjusted_accounts(p_company_id, p_period_year - 1, v_prior),
                            'adjustments', public._fs_applied_adjustments(p_company_id, p_period_year - 1, v_prior));
  END IF;

  v_findings := public.close_review_findings_summary(p_company_id, p_period_year);
  v_identity := jsonb_build_object('contract', 'fs-reporting-input/1', 'certification', v_cert, 'prior', v_prior,
    'adjustments', (SELECT COALESCE(jsonb_agg(a->'id'), '[]'::jsonb) FROM jsonb_array_elements(v_adjustments) a),
    'priorAdjustments', CASE WHEN v_prior IS NULL THEN '[]'::jsonb
      ELSE (SELECT COALESCE(jsonb_agg(a->'id'), '[]'::jsonb) FROM jsonb_array_elements(v_comparative->'adjustments') a) END,
    'findingsRun', v_findings->'runId');
  RETURN jsonb_build_object('state', 'current', 'contract', 'fs-reporting-input/1',
    'current', v_current || jsonb_build_object('accounts', v_accounts), 'comparative', v_comparative,
    'adjustments', v_adjustments, 'findings', v_findings,
    'adjustmentsRequiringRevalidation', (SELECT count(*) FROM public.close_review_adjustments a
       WHERE a.company_id = p_company_id AND a.period_year = p_period_year AND public._cr_adjustment_binding_state(a.id, v_cert) = 'requires_revalidation'),
    'inputSha256', encode(sha256(convert_to(v_identity::text, 'UTF8')), 'hex'));
END;
$$;

REVOKE ALL ON FUNCTION public._fs_adjusted_accounts(uuid, integer, uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public._fs_applied_adjustments(uuid, integer, uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public._fs_period_meta(uuid, uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.fs_reporting_input(uuid, integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.fs_reporting_input(uuid, integer) TO authenticated;
$cfoclose_payload_d6c019785cdd6730$;
  v_bytes   integer;
  v_sha256  text;
BEGIN
  v_bytes  := octet_length(convert_to(c_payload, 'UTF8'));
  v_sha256 := encode(sha256(convert_to(c_payload, 'UTF8')), 'hex');
  IF v_bytes IS DISTINCT FROM c_bytes OR v_sha256 IS DISTINCT FROM c_sha256 THEN
    RAISE EXCEPTION 'RELEASE_PAYLOAD_MISMATCH: % encloses % bytes with SHA-256 %, expected % bytes with SHA-256 %; nothing was changed',
      c_source, v_bytes, v_sha256, c_bytes, c_sha256 USING ERRCODE = '55000';
  END IF;
  EXECUTE c_payload;
END
$cfoclose_release_d6c019785cdd6730$;
