-- CFOClose self-checking release wrapper. GENERATED by scripts/release/selfCheckingWrapper.mjs — do not edit.
-- Applies supabase/migrations/20261027100000_workspace_purpose.sql
-- exactly as committed at 015825859f4bd8641fba013636ae118f3aa5d5e8: 5638 bytes, SHA-256 c1daa138672875d148439017b1f5e09fd926574ede0a28c1e32b0a9580f45c7c.
-- ONE statement. Before any statement of the enclosed migration runs, PostgreSQL recomputes the payload's byte count
-- and SHA-256 and refuses (SQLSTATE 55000, nothing changed) unless both equal the identity below. Any failure inside
-- the migration rolls the whole statement back. Submit this file byte for byte.
DO $cfoclose_release_c1daa138672875d1$
DECLARE
  c_source  CONSTANT text    := '20261027100000_workspace_purpose.sql';
  c_bytes   CONSTANT integer := 5638;
  c_sha256  CONSTANT text    := 'c1daa138672875d148439017b1f5e09fd926574ede0a28c1e32b0a9580f45c7c';
  c_payload CONSTANT text    := $cfoclose_payload_c1daa138672875d1$-- 20261027100000_workspace_purpose.sql — explicit workspace purpose metadata (forward-only; nothing edited).
--
-- Test and training workspaces were indistinguishable from client work: many companies carry the same demo name and the
-- account home listed them all alike. A workspace's PURPOSE is now explicit, recorded metadata — never inferred from a
-- name, a code or an account number:
--   client    the company's own reporting
--   test      acceptance, demonstration or other testing
--   training  training
-- No recorded purpose means "not stated" (shown as such), never a default.
--
-- workspace_purpose_events is append-only (the latest event is in force; history is kept). Only the company's owner
-- records a purpose, with a reason, through set_workspace_purpose(); members with workspace access read it. Nothing about
-- a company, an engagement, an upload, a certification, a report version or a sealed pack is changed or deleted: purpose
-- is a label for the account home, and it gates nothing.

DO $preflight$
BEGIN
  IF to_regclass('public.workspace_purpose_events') IS NOT NULL THEN
    RAISE EXCEPTION 'PREFLIGHT_REFUSED: workspace purpose metadata already exists; nothing was changed' USING ERRCODE = 'P0001';
  END IF;
  IF to_regprocedure('public.can_access_workspace(uuid)') IS NULL THEN
    RAISE EXCEPTION 'PREFLIGHT_REFUSED: can_access_workspace(uuid) is required (20260925100000); nothing was changed' USING ERRCODE = 'P0001';
  END IF;
END;
$preflight$;

CREATE TABLE public.workspace_purpose_events (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  seq           bigserial   NOT NULL UNIQUE,
  company_id    uuid        NOT NULL REFERENCES public.companies(id) ON DELETE RESTRICT,
  purpose       text        NOT NULL CHECK (purpose IN ('client', 'test', 'training')),
  reason        text        NOT NULL CHECK (length(btrim(reason)) BETWEEN 3 AND 500),
  actor_user_id uuid        NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_wpe_company_seq ON public.workspace_purpose_events (company_id, seq DESC);

CREATE OR REPLACE FUNCTION public.workspace_purpose_events_guard()
RETURNS trigger LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
BEGIN
  RAISE EXCEPTION 'WORKSPACE_PURPOSE_APPEND_ONLY: % on workspace_purpose_events', TG_OP USING ERRCODE = '42501';
END;
$$;
CREATE TRIGGER trg_wpe_append_only BEFORE UPDATE OR DELETE ON public.workspace_purpose_events FOR EACH ROW EXECUTE FUNCTION public.workspace_purpose_events_guard();
CREATE TRIGGER trg_wpe_no_truncate BEFORE TRUNCATE ON public.workspace_purpose_events FOR EACH STATEMENT EXECUTE FUNCTION public.workspace_purpose_events_guard();

ALTER TABLE public.workspace_purpose_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.workspace_purpose_events FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.workspace_purpose_events TO authenticated;
GRANT ALL ON TABLE public.workspace_purpose_events TO service_role;
CREATE POLICY wpe_read ON public.workspace_purpose_events FOR SELECT TO authenticated USING (public.can_access_workspace(company_id));

-- The owner records a purpose with a reason. Replay-safe: recording the purpose already in force changes nothing.
CREATE OR REPLACE FUNCTION public.set_workspace_purpose(p_company_id uuid, p_purpose text, p_reason text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE
  v_uid    uuid := auth.uid();
  v_latest text;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'UNAUTHENTICATED' USING ERRCODE = '28000'; END IF;
  IF p_company_id IS NULL OR p_purpose IS NULL OR p_purpose NOT IN ('client', 'test', 'training')
     OR p_reason IS NULL OR length(btrim(p_reason)) NOT BETWEEN 3 AND 500 THEN
    RETURN jsonb_build_object('outcome', 'invalid_request');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.companies c WHERE c.id = p_company_id AND c.user_id = v_uid) THEN
    RETURN jsonb_build_object('outcome', 'forbidden');
  END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended('workspace_purpose:' || p_company_id::text, 0));
  SELECT e.purpose INTO v_latest FROM public.workspace_purpose_events e WHERE e.company_id = p_company_id ORDER BY e.seq DESC LIMIT 1;
  IF v_latest = p_purpose THEN RETURN jsonb_build_object('outcome', 'unchanged', 'purpose', p_purpose); END IF;
  INSERT INTO public.workspace_purpose_events (company_id, purpose, reason, actor_user_id) VALUES (p_company_id, p_purpose, btrim(p_reason), v_uid);
  RETURN jsonb_build_object('outcome', 'recorded', 'purpose', p_purpose);
END;
$$;
REVOKE ALL ON FUNCTION public.set_workspace_purpose(uuid, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.set_workspace_purpose(uuid, text, text) TO authenticated;
REVOKE ALL ON FUNCTION public.workspace_purpose_events_guard() FROM PUBLIC, anon, authenticated;

DO $postcondition$
BEGIN
  IF has_table_privilege('authenticated', 'public.workspace_purpose_events', 'INSERT')
     OR has_table_privilege('authenticated', 'public.workspace_purpose_events', 'UPDATE')
     OR has_table_privilege('authenticated', 'public.workspace_purpose_events', 'DELETE')
     OR has_table_privilege('anon', 'public.workspace_purpose_events', 'SELECT') THEN
    RAISE EXCEPTION 'POSTCONDITION_FAILED: workspace_purpose_events grants are wider than SELECT for members' USING ERRCODE = 'P0001';
  END IF;
  IF has_function_privilege('anon', 'public.set_workspace_purpose(uuid,text,text)', 'EXECUTE') THEN
    RAISE EXCEPTION 'POSTCONDITION_FAILED: set_workspace_purpose is executable by anon' USING ERRCODE = 'P0001';
  END IF;
END;
$postcondition$;
$cfoclose_payload_c1daa138672875d1$;
  v_bytes   integer;
  v_sha256  text;
BEGIN
  v_bytes  := octet_length(convert_to(c_payload, 'UTF8'));
  v_sha256 := encode(sha256(convert_to(c_payload, 'UTF8')), 'hex');
  IF v_bytes IS DISTINCT FROM c_bytes OR v_sha256 IS DISTINCT FROM c_sha256 THEN
    RAISE EXCEPTION 'RELEASE_PAYLOAD_MISMATCH: % encloses % bytes with SHA-256 %, expected % bytes with SHA-256 %; nothing was changed',
      c_source, v_bytes, v_sha256, c_bytes, c_sha256 USING ERRCODE = '55000';
  END IF;
  EXECUTE c_payload;
END
$cfoclose_release_c1daa138672875d1$;
