-- CFOClose self-checking release wrapper. GENERATED by scripts/release/selfCheckingWrapper.mjs — do not edit.
-- Applies supabase/migrations/20261028100000_period_dates_from_company.sql
-- exactly as committed at 015825859f4bd8641fba013636ae118f3aa5d5e8: 10136 bytes, SHA-256 da14459f7557fb41ec25d91cba40801ba85245c0ae89c75ea72141be841fbc71.
-- ONE statement. Before any statement of the enclosed migration runs, PostgreSQL recomputes the payload's byte count
-- and SHA-256 and refuses (SQLSTATE 55000, nothing changed) unless both equal the identity below. Any failure inside
-- the migration rolls the whole statement back. Submit this file byte for byte.
DO $cfoclose_release_da14459f7557fb41$
DECLARE
  c_source  CONSTANT text    := '20261028100000_period_dates_from_company.sql';
  c_bytes   CONSTANT integer := 10136;
  c_sha256  CONSTANT text    := 'da14459f7557fb41ec25d91cba40801ba85245c0ae89c75ea72141be841fbc71';
  c_payload CONSTANT text    := $cfoclose_payload_da14459f7557fb41$-- 20261028100000_period_dates_from_company.sql — a workspace's first period follows the company's recorded year-end
-- (forward-only; nothing edited).
--
-- Defect closed: open_engagement_with_scope (the launchpad's "choose a service" step) created every new period as the
-- calendar year in TZS, whatever the company recorded at first run. A company with a 30 June year-end and KES therefore
-- had its first trial balance filed in a 1 January – 31 December TZS period. Now, when the company STATED both its
-- year-end and a registered currency (created through create_entity — table defaults never count), the period ends on that month and day in the reporting year, starts the day after
-- the previous year's end (29 February clamps to the month's last day), and is in the company's currency. Its basis is
-- recorded as 'company_year_end' — derived from the company's own record, not a person's confirmation; the period can be
-- confirmed or corrected through the existing period functions. A company without both keeps the legacy behaviour
-- unchanged. Existing periods are not touched.
--
-- The function below is the 20261009100000 definition with exactly the marked [20261028100000] block (and its six
-- declarations) added; nothing else changes. When the derived dates would overlap a period the company already has (a
-- legacy calendar-year period), the legacy path is kept for that company rather than refusing the workspace.

DO $preflight$
BEGIN
  IF to_regprocedure('public.open_engagement_with_scope(uuid,integer,text[],text)') IS NULL THEN
    RAISE EXCEPTION 'PREFLIGHT_REFUSED: open_engagement_with_scope is missing; nothing was changed' USING ERRCODE = 'P0001';
  END IF;
  IF position('company_year_end' IN pg_get_constraintdef((SELECT oid FROM pg_constraint WHERE conname = 'chk_fp_dates_basis'))) > 0 THEN
    RAISE EXCEPTION 'PREFLIGHT_REFUSED: periods from the company year-end are already in force; nothing was changed' USING ERRCODE = 'P0001';
  END IF;
END;
$preflight$;

ALTER TABLE public.fiscal_periods DROP CONSTRAINT chk_fp_dates_basis;
ALTER TABLE public.fiscal_periods ADD CONSTRAINT chk_fp_dates_basis
  CHECK (dates_basis IS NULL OR dates_basis IN ('confirmed', 'v1_calendar_convention', 'company_year_end'));

CREATE OR REPLACE FUNCTION public.open_engagement_with_scope(p_company_id uuid, p_period_year integer, p_capabilities text[], p_engagement_type text DEFAULT 'composite'::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_member   UUID;
  v_period   UUID;
  v_eng      UUID;
  v_created  BOOLEAN := false;
  v_cap      TEXT;
  v_caps     TEXT[];
  v_granted  TEXT[];
  v_fye      TEXT;
  v_cur      TEXT;
  v_m        INTEGER;
  v_d        INTEGER;
  v_end      DATE;
  v_prev_end DATE;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'FORBIDDEN: an authenticated session is required' USING ERRCODE = '42501';
  END IF;
  IF p_period_year IS NULL OR p_period_year < 2000 OR p_period_year > 2100 THEN
    RAISE EXCEPTION 'INVALID: reporting year out of range' USING ERRCODE = '22023';
  END IF;
  SELECT array_agg(DISTINCT c ORDER BY c) INTO v_caps FROM unnest(COALESCE(p_capabilities, ARRAY[]::TEXT[])) c;
  IF v_caps IS NULL OR array_length(v_caps, 1) = 0 THEN
    RAISE EXCEPTION 'INVALID: choose at least one service' USING ERRCODE = '22023';
  END IF;
  FOREACH v_cap IN ARRAY v_caps LOOP
    IF v_cap NOT IN ('FINANCIAL_STATEMENTS', 'TAX_COMPUTATION', 'COMPLIANCE_REVIEW', 'FILING_PREPARATION', 'MONITORING') THEN
      RAISE EXCEPTION 'INVALID: unknown service %', v_cap USING ERRCODE = '22023';
    END IF;
  END LOOP;

  -- 1. authorise from the session (never from the request)
  SELECT fm.id INTO v_member FROM public.firm_members fm
   WHERE fm.user_id = auth.uid() AND fm.company_id = p_company_id AND fm.accepted_at IS NOT NULL AND public.named_user_access_active(fm.company_id, fm.user_id)
     AND public.workspace_capability_allowed(fm.company_id, fm.user_id, 'review_close') LIMIT 1;
  IF v_member IS NULL THEN
    RAISE EXCEPTION 'FORBIDDEN: choosing services needs the review_close capability in this workspace and a current plan' USING ERRCODE = '42501';
  END IF;
  FOREACH v_cap IN ARRAY v_caps LOOP PERFORM public.assert_capability_available(v_cap); END LOOP;

  -- 2. serialise on the company × year identity: every concurrent request for the same workspace queues here
  PERFORM pg_advisory_xact_lock(hashtextextended('open_engagement:' || p_company_id::text || ':' || p_period_year::text, 0));

  -- 3. the reporting period of record (earliest wins; the (company, year-end) UNIQUE key is the backstop)
  SELECT p.id INTO v_period FROM public.fiscal_periods p
   WHERE p.company_id = p_company_id
     AND EXTRACT(YEAR FROM COALESCE(p.reporting_end, p.fiscal_year_end))::INTEGER = p_period_year
   ORDER BY p.created_at, p.id LIMIT 1;
  -- [20261028100000] A company that recorded its year-end and currency (first run, create_entity) gets its period from
  -- THEM: it ends on the year-end's month and day in the reporting year and starts the day after the previous year's
  -- end; its currency is the company's. Recorded as 'company_year_end' (derived from the company's record, not stated
  -- by a person). A company without both keeps the legacy calendar-year TZS period below, unchanged.
  -- Only a company created through create_entity (creation_request_id set) STATED its year-end and currency: the columns'
  -- table defaults ('12-31', 'USD') are not a choice and are never used as one.
  SELECT btrim(c.fiscal_year_end), upper(btrim(c.currency)) INTO v_fye, v_cur FROM public.companies c
   WHERE c.id = p_company_id AND c.creation_request_id IS NOT NULL;
  -- companies.fiscal_year_end is text: a full date (create_entity) or month-day ('12-31'). Only its month and day count.
  IF v_fye ~ '^([0-9]{4}-)?[0-9]{2}-[0-9]{2}$' THEN
    v_m := split_part(right(v_fye, 5), '-', 1)::int;
    v_d := split_part(right(v_fye, 5), '-', 2)::int;
  END IF;
  IF v_period IS NULL AND v_m BETWEEN 1 AND 12 AND v_d BETWEEN 1 AND 31 AND v_cur IS NOT NULL
     AND EXISTS (SELECT 1 FROM public.currency_registry r WHERE r.code = v_cur) THEN
    v_end := LEAST(make_date(p_period_year, v_m, 1) + (v_d - 1), (make_date(p_period_year, v_m, 1) + interval '1 month' - interval '1 day')::date);
    v_prev_end := LEAST(make_date(p_period_year - 1, v_m, 1) + (v_d - 1), (make_date(p_period_year - 1, v_m, 1) + interval '1 month' - interval '1 day')::date);
    BEGIN
      PERFORM set_config('axiom.period_writer', txid_current()::text, true);
      INSERT INTO public.fiscal_periods (company_id, fiscal_year_end, reporting_start, reporting_end, period_label, created_by, reporting_currency, dates_basis)
      VALUES (p_company_id, v_end, v_prev_end + 1, v_end, 'FY' || p_period_year::text, auth.uid(), v_cur, 'company_year_end')
      ON CONFLICT (company_id, fiscal_year_end) DO NOTHING
      RETURNING id INTO v_period;
      PERFORM set_config('axiom.period_writer', '', true);
    EXCEPTION WHEN exclusion_violation THEN
      -- The derived dates overlap a period the company already has (for example a legacy calendar-year period): keep
      -- the company's existing convention (the legacy path below) rather than refuse the workspace.
      PERFORM set_config('axiom.period_writer', '', true);
      v_period := NULL;
    END;
    IF v_period IS NULL THEN
      SELECT p.id INTO v_period FROM public.fiscal_periods p WHERE p.company_id = p_company_id AND p.fiscal_year_end = v_end;
    END IF;
  END IF;
  IF v_period IS NULL THEN
    -- Legacy v1 path (retained unchanged in behaviour until the workbench setup replaces it): TZS is now stated
    -- explicitly here — the column no longer has a default — and the provenance of the calendar-year dates is recorded.
    PERFORM set_config('axiom.period_writer', txid_current()::text, true);
    INSERT INTO public.fiscal_periods (company_id, fiscal_year_end, reporting_start, reporting_end, period_label, created_by, reporting_currency, dates_basis)
    VALUES (p_company_id, make_date(p_period_year, 12, 31), make_date(p_period_year, 1, 1), make_date(p_period_year, 12, 31), 'FY' || p_period_year::text, auth.uid(), 'TZS', 'v1_calendar_convention')
    ON CONFLICT (company_id, fiscal_year_end) DO NOTHING
    RETURNING id INTO v_period;
    PERFORM set_config('axiom.period_writer', '', true);
    IF v_period IS NULL THEN
      SELECT p.id INTO v_period FROM public.fiscal_periods p
       WHERE p.company_id = p_company_id AND p.fiscal_year_end = make_date(p_period_year, 12, 31);
    END IF;
  END IF;

  -- 4. the open engagement, or exactly one new one (uq_engagements_one_open_per_period is the invariant)
  SELECT g.id INTO v_eng FROM public.engagements g WHERE g.fiscal_period_id = v_period AND g.status = 'open';
  IF v_eng IS NULL THEN
    INSERT INTO public.engagements (fiscal_period_id, company_id, engagement_type, created_by_member_id)
    VALUES (v_period, p_company_id, COALESCE(p_engagement_type, 'composite'), v_member)
    RETURNING id INTO v_eng;
    v_created := true;
  END IF;

  -- 5. grants: only what is missing (each goes through the validated, jurisdiction-aware command)
  FOREACH v_cap IN ARRAY v_caps LOOP
    IF NOT EXISTS (
      SELECT 1 FROM (
        SELECT DISTINCT ON (e.capability) e.action FROM public.engagement_mandate_events e
         WHERE e.engagement_id = v_eng AND e.capability = v_cap ORDER BY e.capability, e.sequence_no DESC
      ) l WHERE l.action = 'GRANT'
    ) THEN
      PERFORM public.grant_engagement_capability(v_eng, v_cap, 'Selected when the workspace was set up');
    END IF;
  END LOOP;

  SELECT COALESCE(array_agg(x.capability ORDER BY x.capability), ARRAY[]::TEXT[]) INTO v_granted FROM (
    SELECT DISTINCT ON (e.capability) e.capability, e.action FROM public.engagement_mandate_events e
     WHERE e.engagement_id = v_eng ORDER BY e.capability, e.sequence_no DESC
  ) x WHERE x.action = 'GRANT';

  RETURN jsonb_build_object('engagementId', v_eng, 'periodId', v_period, 'created', v_created, 'granted', to_jsonb(v_granted));
END;
$function$;
$cfoclose_payload_da14459f7557fb41$;
  v_bytes   integer;
  v_sha256  text;
BEGIN
  v_bytes  := octet_length(convert_to(c_payload, 'UTF8'));
  v_sha256 := encode(sha256(convert_to(c_payload, 'UTF8')), 'hex');
  IF v_bytes IS DISTINCT FROM c_bytes OR v_sha256 IS DISTINCT FROM c_sha256 THEN
    RAISE EXCEPTION 'RELEASE_PAYLOAD_MISMATCH: % encloses % bytes with SHA-256 %, expected % bytes with SHA-256 %; nothing was changed',
      c_source, v_bytes, v_sha256, c_bytes, c_sha256 USING ERRCODE = '55000';
  END IF;
  EXECUTE c_payload;
END
$cfoclose_release_da14459f7557fb41$;
