/**
 * Official Reporting Pack issuance (supabase/functions/_shared/reportingPackSeal.mjs, security corrections B-4 / N-1):
 * the document is generated by the DATABASE from the authoritative saved output; no caller supplies bytes or a hash.
 * Here the handler runs against a model of the database's contract (prepare → canonical document; seal → the database
 * regenerates and hashes it itself). The real canonical renderer, the real seal and the adversarial byte cases are
 * proven on real PostgreSQL, through this same module, in scripts/db-proof/billingSuspension.mjs.
 */
import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { issueOfficialPack, parseSealRequest, verifyStoredPack, type SealDeps } from "../../../supabase/functions/_shared/reportingPackSeal.mjs";
import { deliverOfficialPack, deliverWorkingCopy, isOfficiallySealable, parseOfficialDocument } from "./reportingPack";

const sha = (b: Uint8Array) => createHash("sha256").update(b).digest("hex");
const shaText = (t: string) => sha(new TextEncoder().encode(t));
const U = { user: "11111111-1111-4111-8111-111111111111", iss: "22222222-2222-4222-8222-222222222222", co: "33333333-3333-4333-8333-333333333333" };
const PATH = `${U.co}/${U.iss}.json`;
// The canonical document the database renders from the saved output of this issuance (a non-ASCII amount label on
// purpose: the bytes are the UTF-8 encoding the database hashed).
const CANONICAL = '{\n    "schema": "cfoclose.official-reporting-pack.v1",\n    "report": {"revenue": "TZS 1 000 000 — audited"}\n}\n';
const DOCTORED = CANONICAL.replace("1 000 000", "9 000 000");

function world(opts: { prepare?: string; seal?: string; sealHash?: string; tamperOnPut?: boolean; prepHash?: string } = {}) {
  const store = new Map<string, Uint8Array>();
  const rpcCalls: Array<[string, Record<string, unknown>]> = [];
  let sealed: { path: string; sha: string } | null = null;
  let canonicalNow = CANONICAL;
  const deps: SealDeps = {
    rpc: async (fn, args) => {
      rpcCalls.push([fn, args]);
      if (fn === "prepare_official_reporting_pack") {
        if ((opts.prepare ?? "ready") !== "ready") return { data: { outcome: opts.prepare }, error: null };
        if (sealed) return { data: { outcome: "already_sealed" }, error: null };
        return { data: { outcome: "ready", document: CANONICAL, content_sha256: opts.prepHash ?? shaText(CANONICAL), storage_path: PATH, file_name: "official-reporting-pack-2025.json" }, error: null };
      }
      if (fn === "seal_reporting_pack_server") {
        // The database takes no hash: it regenerates and hashes the canonical document itself.
        if (Object.keys(args).sort().join(",") !== "p_issuance_id,p_storage_path,p_user") return { data: null, error: { message: "unexpected arguments" } };
        const outcome = sealed ? "already_sealed" : opts.seal ?? "sealed";
        if (outcome !== "sealed") return { data: { outcome }, error: null };
        sealed = { path: String(args.p_storage_path), sha: opts.sealHash ?? shaText(CANONICAL) };
        return { data: { outcome, content_sha256: sealed.sha }, error: null };
      }
      if (fn === "reporting_pack_sealed_object") {
        return { data: sealed ? { storage_path: sealed.path, content_sha256: sealed.sha, canonical_sha256: shaText(canonicalNow), company_id: U.co } : null, error: null };
      }
      return { data: null, error: { message: "unexpected" } };
    },
    put: async (p, b) => {
      if (store.has(p)) return { error: { message: "exists" } };
      store.set(p, opts.tamperOnPut ? new TextEncoder().encode("tampered in transit") : b);
      return { error: null };
    },
    remove: async (p) => store.delete(p),
    get: async (p) => store.get(p) ?? null,
    sha256Hex: async (b) => sha(b),
  };
  return { deps, store, rpcCalls, setCanonical: (t: string) => { canonicalNow = t; } };
}

describe("official bytes are generated by the server; a caller cannot supply them", () => {
  it("seals and stores exactly the database's canonical document, and returns it to be saved", async () => {
    const w = world();
    const r = await issueOfficialPack(w.deps, { userId: U.user, issuanceId: U.iss });
    expect(r).toEqual({ httpStatus: 200, body: { outcome: "sealed", issuance_id: U.iss, content_sha256: shaText(CANONICAL), document: CANONICAL, file_name: "official-reporting-pack-2025.json" } });
    expect(w.store.get(PATH)).toEqual(new TextEncoder().encode(CANONICAL));
    expect(w.rpcCalls.map(([fn]) => fn)).toEqual(["prepare_official_reporting_pack", "seal_reporting_pack_server"]);
    expect(w.rpcCalls[1][1]).toEqual({ p_user: U.user, p_issuance_id: U.iss, p_storage_path: PATH });
  });
  it("the Edge Function refuses any upload (non-JSON) and any body other than { action, issuance_id }: unrelated, doctored and foreign bytes never reach the database", () => {
    const src = fs.readFileSync(path.join(__dirname, "../../../supabase/functions/seal-reporting-pack/index.ts"), "utf8");
    expect(src).toContain('const request = parseSealRequest(req.headers.get("content-type"), await req.json().catch(() => null));');
    expect(src).toContain('if (!request) return json(400, { outcome: "invalid_request" });');
    expect(src).not.toMatch(/formData|p_content_sha256/);
    const pdf = "%PDF-1.7 unrelated but syntactically valid";
    const cases: Array<[string, unknown]> = [
      ["multipart/form-data; boundary=x", { action: "issue", issuance_id: U.iss }],
      ["application/pdf", pdf],
      ["application/json", { action: "issue", issuance_id: U.iss, file: pdf }],
      ["application/json", { action: "issue", issuance_id: U.iss, document: DOCTORED }],
      ["application/json", { action: "issue", issuance_id: U.iss, content_sha256: shaText(CANONICAL) }],
      ["application/json", { action: "issue", issuance_id: U.iss, output_ref: "fs-report:other:v1", company_id: U.co }],
      ["application/json", { action: "seal", issuance_id: U.iss }],
      ["application/json", { action: "issue", issuance_id: "not-a-uuid" }],
      ["application/json", [U.iss]],
    ];
    for (const [type, body] of cases) expect(parseSealRequest(type, body)).toBeNull();
    expect(parseSealRequest("application/json; charset=utf-8", { action: "issue", issuance_id: U.iss })).toEqual({ action: "issue", issuanceId: U.iss });
  });
  it("even extra fields slipped into the handler input are ignored: only the canonical document is ever stored or sealed", async () => {
    for (const extra of [{ bytes: new TextEncoder().encode("%PDF-1.7 unrelated"), content_sha256: "a".repeat(64) }, { document: DOCTORED }]) {
      const w = world();
      const r = await issueOfficialPack(w.deps, { userId: U.user, issuanceId: U.iss, ...extra } as never);
      expect(r.body.content_sha256).toBe(shaText(CANONICAL));
      expect(w.store.get(PATH)).toEqual(new TextEncoder().encode(CANONICAL));
      expect(JSON.stringify(w.rpcCalls)).not.toMatch(/p_content_sha256|p_bytes|aaaaaaaa|9 000 000/);
    }
  });
  it("refusals before anything is stored: not sealable (every browser-rendered format), plan, capability, expiry, replay, foreign issuance", async () => {
    const cases: Array<[string, number]> = [["official_sealing_unavailable", 422], ["entitlement_required", 402], ["capability_required", 403], ["expired", 410], ["already_sealed", 409], ["not_found", 404], ["binding_mismatch", 409]];
    for (const [outcome, status] of cases) {
      const w = world({ prepare: outcome });
      const r = await issueOfficialPack(w.deps, { userId: U.user, issuanceId: U.iss });
      expect(r).toEqual({ httpStatus: status, body: { outcome } });
      expect(w.store.size).toBe(0);
      expect(w.rpcCalls.map(([fn]) => fn)).toEqual(["prepare_official_reporting_pack"]);
    }
  });
  it("a seal refused at the last moment (downgrade, race, cross-account) removes the stored object: nothing official remains", async () => {
    for (const outcome of ["entitlement_required", "capability_required", "already_sealed", "expired", "binding_mismatch"]) {
      const w = world({ seal: outcome });
      expect((await issueOfficialPack(w.deps, { userId: U.user, issuanceId: U.iss })).body.outcome).toBe(outcome);
      expect(w.store.size).toBe(0);
    }
  });
  it("any disagreement with the database's own hash fails closed: re-encoded bytes, an object altered in storage (nothing sealed), a different sealed hash", async () => {
    const enc = world({ prepHash: "b".repeat(64) });
    expect((await issueOfficialPack(enc.deps, { userId: U.user, issuanceId: U.iss })).body.outcome).toBe("seal_failed");
    expect(enc.store.size).toBe(0);
    const tamper = world({ tamperOnPut: true });
    expect((await issueOfficialPack(tamper.deps, { userId: U.user, issuanceId: U.iss })).body).toEqual({ outcome: "seal_failed" });
    expect(tamper.store.size).toBe(0);
    expect(tamper.rpcCalls.map(([fn]) => fn)).not.toContain("seal_reporting_pack_server");
    expect((await verifyStoredPack(tamper.deps, U.iss)).outcome).toBe("not_found");
    const other = world({ sealHash: "c".repeat(64) });
    expect((await issueOfficialPack(other.deps, { userId: U.user, issuanceId: U.iss })).body).toEqual({ outcome: "seal_failed" });
  });
  it("orphan recovery: an interrupted request's canonical object is reused (one seal); foreign unsealed bytes are replaced, never sealed", async () => {
    const w = world();
    w.store.set(PATH, new TextEncoder().encode(CANONICAL));
    expect((await issueOfficialPack(w.deps, { userId: U.user, issuanceId: U.iss })).body.outcome).toBe("sealed");
    expect(w.store.get(PATH)).toEqual(new TextEncoder().encode(CANONICAL));
    const f = world();
    f.store.set(PATH, new TextEncoder().encode(DOCTORED));
    const r = await issueOfficialPack(f.deps, { userId: U.user, issuanceId: U.iss });
    expect(r.body.outcome).toBe("sealed");
    expect(f.store.get(PATH)).toEqual(new TextEncoder().encode(CANONICAL));
    expect((await verifyStoredPack(f.deps, U.iss)).outcome).toBe("intact");
  });
  it("a sealed object is never removed or replaced by a later or concurrent request", async () => {
    const w = world();
    await issueOfficialPack(w.deps, { userId: U.user, issuanceId: U.iss });
    const out = await Promise.all(Array.from({ length: 12 }, () => issueOfficialPack(w.deps, { userId: U.user, issuanceId: U.iss }).then((x) => x.body.outcome)));
    expect(out.every((o) => o === "already_sealed")).toBe(true);
    expect(w.store.get(PATH)).toEqual(new TextEncoder().encode(CANONICAL));
  });
  it("one issuance is stored once (no overwrite); bad ids never reach the database", async () => {
    const w = world();
    await issueOfficialPack(w.deps, { userId: U.user, issuanceId: U.iss });
    expect((await issueOfficialPack(w.deps, { userId: U.user, issuanceId: U.iss })).body.outcome).toBe("already_sealed");
    const v = world();
    for (const bad of [{ userId: "x", issuanceId: U.iss }, { userId: U.user, issuanceId: "nope" }]) expect((await issueOfficialPack(v.deps, bad)).body.outcome).toBe("invalid_request");
    expect(v.rpcCalls).toEqual([]);
  });
});

describe("verification after sealing", () => {
  it("intact → substituted → missing; a seal that is not the canonical document of its source is never official", async () => {
    const w = world();
    await issueOfficialPack(w.deps, { userId: U.user, issuanceId: U.iss });
    expect((await verifyStoredPack(w.deps, U.iss)).outcome).toBe("intact");
    w.store.set(PATH, new TextEncoder().encode(DOCTORED));
    expect((await verifyStoredPack(w.deps, U.iss)).outcome).toBe("substituted");
    w.store.delete(PATH);
    expect((await verifyStoredPack(w.deps, U.iss)).outcome).toBe("missing");
    w.setCanonical("a different source now");
    expect((await verifyStoredPack(w.deps, U.iss)).outcome).toBe("not_canonical");
    expect((await verifyStoredPack(world().deps, U.iss)).outcome).toBe("not_found");
  });
});

describe("the client never produces official bytes", () => {
  const rpc = async () => ({ data: { outcome: "issued", issuance_id: U.iss }, error: null });
  it("official path: issue → the server's document is saved as-is; nothing is built in the browser; only saved statements versions qualify", async () => {
    const saved: Array<{ text: string; name: string }> = [];
    const calls: string[] = [];
    const out = await deliverOfficialPack(rpc, async (id) => { calls.push(id); return { data: { outcome: "sealed", document: CANONICAL, file_name: "official.json", content_sha256: shaText(CANONICAL) }, error: null }; },
      { companyId: U.co, periodYear: 2025, kind: "financial_statements_data", outputRef: "fs-report:r1:v3" }, (blob, name) => void blob.text().then((text) => saved.push({ text, name })));
    await new Promise((r) => setTimeout(r, 0));
    expect(out).toBe("delivered");
    expect(calls).toEqual([U.iss]);
    expect(saved).toEqual([{ text: CANONICAL, name: "official.json" }]);
    const notSealable = [["financial_statements_pdf", "fs-report:r1:v3"], ["financial_statements_data", "upload:x"], ["financial_statements_data", "fs-draft:r1:abc"], ["board_pack", "variance-run:x"]] as const;
    for (const [kind, ref] of notSealable) {
      expect(isOfficiallySealable(kind, ref)).toBe(false);
      expect(await deliverOfficialPack(rpc, async () => { throw new Error("must not be called"); }, { companyId: U.co, periodYear: 2025, kind, outputRef: ref }, () => { throw new Error("must not save"); })).toBe("failed");
    }
    expect(parseOfficialDocument({ outcome: "sealed", document: CANONICAL, file_name: "x", content_sha256: "bad" })).toBeNull();
    expect(await deliverOfficialPack(rpc, async () => ({ data: { outcome: "official_sealing_unavailable" }, error: null }), { companyId: U.co, periodYear: 2025, kind: "financial_statements_data", outputRef: "fs-report:r1:v3" }, () => { throw new Error("must not save"); })).toBe("failed");
  });
  it("the official path asks the server for an OFFICIAL issuance; a version without a FINAL publication yields not_final and nothing else happens", async () => {
    const called: string[] = [];
    const notFinal = async (fn: string) => { called.push(fn); return { data: { outcome: "final_publication_required" }, error: null }; };
    expect(await deliverOfficialPack(notFinal, async () => { throw new Error("must not be called"); }, { companyId: U.co, periodYear: 2025, kind: "financial_statements_data", outputRef: "fs-report:r1:v3" }, () => { throw new Error("must not save"); })).toBe("not_final");
    expect(called).toEqual(["issue_official_reporting_pack"]);
  });
  it("only the byte re-hash route answers official: intact → official; substituted, missing, not canonical or no access → not official", async () => {
    const { verifyOfficialPack } = await import("../../../supabase/functions/_shared/reportingPackSeal.mjs");
    const w = world();
    await issueOfficialPack(w.deps, { userId: U.user, issuanceId: U.iss });
    const access = (code: string) => ({ ...w.deps, rpc: async (fn: string, args: Record<string, unknown>) => (fn === "authorize_paid_action_for_user" ? { data: { code }, error: null } : w.deps.rpc(fn, args)) });
    expect(await verifyOfficialPack(access("ALLOWED"), U.user, U.iss)).toEqual({ outcome: "intact", official: true });
    expect(await verifyOfficialPack(access("WORKSPACE_ACCESS_DENIED"), U.user, U.iss)).toEqual({ outcome: "not_found", official: false });
    w.store.set(PATH, new TextEncoder().encode(CANONICAL.replace("audited", "restatd")));
    expect(await verifyOfficialPack(access("ALLOWED"), U.user, U.iss)).toEqual({ outcome: "substituted", official: false });
    w.store.delete(PATH);
    expect(await verifyOfficialPack(access("ALLOWED"), U.user, U.iss)).toEqual({ outcome: "missing", official: false });
  });
  it("working copies are issued and saved but never sent for sealing", async () => {
    const saved: string[] = [];
    expect(await deliverWorkingCopy(rpc, { companyId: U.co, periodYear: 2025, kind: "financial_statements_pdf", outputRef: "upload:x" }, (id) => new Blob([id]), (_b, n) => saved.push(String(n)))).toBe("delivered");
    expect(saved).toEqual(["null"]);
    const src = fs.readFileSync(path.join(__dirname, "reportingPack.ts"), "utf8");
    expect(src.slice(src.indexOf("export async function deliverWorkingCopy"))).not.toMatch(/seal|issueOfficial/i);
    expect(fs.readFileSync(path.join(__dirname, "requestReportingPack.ts"), "utf8")).toContain('body: { action: "issue", issuance_id: issuanceId }');
  });
});
