/**
 * Reporting Pack (REPORTING_PACK_EXPORT) on the client.
 *
 * Every deliverable is ISSUED by the server first (issue_reporting_pack: entitlement, the format's plan feature and the
 * person's issue_reporting_pack capability; 20260925120000 / 20260925140000). What happens next depends on whether the
 * server can produce the bytes itself (security correction N-1):
 *
 *   OFFICIAL      only bytes the DATABASE generates from the authoritative saved output named by the closed output
 *                 reference: today financial_statements_data for a saved statements version (fs-report:<id>:v<n>).
 *                 The seal-reporting-pack Edge Function stores exactly those bytes and the database seals its own
 *                 hash of them; the browser saves the server's document. The browser never sends document bytes or a
 *                 hash, so a doctored or unrelated file can never be sealed.
 *   WORKING COPY  every other format (browser-rendered PDFs, spreadsheets, board packs, letters, notes, tax papers,
 *                 upload-based outputs): issued, rendered in the browser and saved, but NEVER sealed and never official.
 *
 * Not deliverables (never gated): the blank trial-balance template and exports of the user's own inputs. Free printing
 * carries DRAFT_PRINT_MARK on every printed page.
 */
export const REPORTING_PACK_KINDS = [
  "financial_statements_pdf",
  "financial_statements_spreadsheet",
  "financial_statements_data",
  "filing_pack",
  "client_pack",
  "board_pack",
  "management_letter",
  "disclosure_notes",
  "tax_computation",
  "tax_workpaper",
] as const;
export type ReportingPackKind = (typeof REPORTING_PACK_KINDS)[number];

/** The marking every free (not entitled) printed page carries. */
export const DRAFT_PRINT_MARK = "DRAFT — NOT CERTIFIED — NOT FOR FILING OR CLIENT ISSUE";

/** Shown whenever a browser-rendered file is saved: it is a working copy, never an official Reporting Pack. */
export const WORKING_COPY_NOTICE =
  "Working copy — not a sealed official Reporting Pack. Official packs are generated by the server from a saved statements version.";

/** The formats the server can generate itself, and so seal as official (mirrors _reporting_pack_officially_sealable). */
export const OFFICIALLY_SEALABLE_KINDS: readonly ReportingPackKind[] = ["financial_statements_data"];
export function isOfficiallySealable(kind: ReportingPackKind, outputRef: string | null | undefined): boolean {
  return OFFICIALLY_SEALABLE_KINDS.includes(kind) && /^fs-report:[A-Za-z0-9_-]{1,120}:v[0-9]{1,6}$/.test(outputRef ?? "");
}

export type IssueOutcome =
  | { readonly status: "issued"; readonly issuanceId: string }
  | { readonly status: "locked" }
  /** The person does not hold issue_reporting_pack in this workspace (a capability, never a job title). */
  | { readonly status: "not_permitted" }
  | { readonly status: "failed" };

/** Strict parse of issue_reporting_pack(); only a server "issued"/"already_issued" with an id may proceed. */
export function parseIssueOutcome(raw: unknown): IssueOutcome {
  if (!raw || typeof raw !== "object") return { status: "failed" };
  const r = raw as Record<string, unknown>;
  if ((r.outcome === "issued" || r.outcome === "already_issued") && typeof r.issuance_id === "string" && r.issuance_id.length > 0 && r.sealed !== true) {
    return { status: "issued", issuanceId: r.issuance_id };
  }
  if (r.outcome === "entitlement_required") return { status: "locked" };
  if (r.outcome === "capability_required") return { status: "not_permitted" };
  return { status: "failed" };
}

export type SealOutcome = "sealed" | "locked" | "not_permitted" | "unavailable" | "failed";

/** Strict parse of the seal-reporting-pack answer; anything but "sealed" means nothing official exists. */
export function parseSealOutcome(raw: unknown): SealOutcome {
  const o = raw && typeof raw === "object" ? (raw as Record<string, unknown>).outcome : null;
  if (o === "sealed") return "sealed";
  if (o === "entitlement_required" || o === "workspace_access_denied") return "locked";
  if (o === "capability_required") return "not_permitted";
  if (o === "official_sealing_unavailable") return "unavailable";
  return "failed";
}

type Rpc = (fn: string, args: Record<string, unknown>) => PromiseLike<{ data: unknown; error: unknown }>;

/** The bindings an issuance is made for, and checked against again when it is sealed. */
export interface PackBinding {
  readonly companyId: string;
  readonly periodYear: number;
  readonly kind: ReportingPackKind;
  /** The saved output / version the pack is for (e.g. "fs-report:<id>:v3", "upload:<id>"). */
  readonly outputRef: string;
}

/** Asks the server to issue one deliverable. A transport error is a failure, never an issuance. */
export async function issueReportingPack(rpc: Rpc, b: PackBinding, requestId: string = crypto.randomUUID()): Promise<IssueOutcome> {
  const { data, error } = await rpc("issue_reporting_pack", {
    p_company_id: b.companyId, p_period_year: b.periodYear, p_pack_kind: b.kind, p_output_ref: b.outputRef, p_request_id: requestId,
  });
  return error ? { status: "failed" } : parseIssueOutcome(data);
}

/**
 * The output reference of a financial-statements export: a saved version the server can check, or a named draft. A
 * draft reference is refused by the server's closed output-reference scheme: drafts are never official.
 */
export function financialStatementsOutputRef(lineage: { reportId: string; reportVersion: number | null; persisted: boolean; contentHash: string } | null): string | null {
  if (!lineage) return null;
  return lineage.persisted && lineage.reportVersion !== null
    ? `fs-report:${lineage.reportId}:v${lineage.reportVersion}`
    : `fs-draft:${lineage.reportId}:${lineage.contentHash.slice(0, 16)}`;
}

export type DeliveryOutcome = "delivered" | "locked" | "not_permitted" | "failed";

/** Asks the seal-reporting-pack Edge Function to generate, store and seal the official document of an issuance. */
export type OfficialIssue = (issuanceId: string) => Promise<{ data: unknown; error: unknown }>;

export interface OfficialDocument {
  readonly document: string;
  readonly fileName: string;
  readonly contentSha256: string;
}

/** Strict parse of a sealed answer: the server's own document, its file name and its hash, or null. */
export function parseOfficialDocument(raw: unknown): OfficialDocument | null {
  if (parseSealOutcome(raw) !== "sealed") return null;
  const r = raw as Record<string, unknown>;
  if (typeof r.document !== "string" || typeof r.file_name !== "string" || !/^[0-9a-f]{64}$/.test(String(r.content_sha256))) return null;
  return { document: r.document, fileName: r.file_name, contentSha256: String(r.content_sha256) };
}

/**
 * The OFFICIAL path: issue → the SERVER generates, stores and seals the document → save exactly the server's document.
 * Nothing is built in the browser, no bytes or hash are sent, and nothing is saved unless the server sealed it. A format
 * the server cannot generate is never issued here.
 */
export async function deliverOfficialPack(
  rpc: Rpc, issueOfficial: OfficialIssue, b: PackBinding, save: (blob: Blob, fileName: string) => void,
): Promise<DeliveryOutcome> {
  if (!isOfficiallySealable(b.kind, b.outputRef)) return "failed";
  const issued = await issueReportingPack(rpc, b);
  if (issued.status !== "issued") return issued.status;
  const { data, error } = await issueOfficial(issued.issuanceId);
  if (error) return "failed";
  const sealed = parseSealOutcome(data);
  if (sealed !== "sealed") return sealed === "unavailable" ? "failed" : sealed;
  const doc = parseOfficialDocument(data);
  if (!doc) return "failed";
  save(new Blob([doc.document], { type: "application/json" }), doc.fileName);
  return "delivered";
}

/** A browser-rendered file, optionally with its own file name. */
export type BuiltPack = Blob | { readonly blob: Blob; readonly fileName: string };

/**
 * The WORKING-COPY path for every browser-rendered format: issue (entitlement and capability) → build (the issue
 * reference may be printed in it) → save. It is never sealed and never official.
 */
export async function deliverWorkingCopy(
  rpc: Rpc, b: PackBinding, build: (issuanceId: string) => BuiltPack | Promise<BuiltPack>,
  save: (blob: Blob, fileName: string | null) => void,
): Promise<DeliveryOutcome> {
  const issued = await issueReportingPack(rpc, b);
  if (issued.status !== "issued") return issued.status;
  const built = await build(issued.issuanceId);
  save(built instanceof Blob ? built : built.blob, built instanceof Blob ? null : built.fileName);
  return "delivered";
}
