// seal-reporting-pack — the only way a Reporting Pack becomes OFFICIAL (security corrections B-4, N-1).
//
// POST application/json { action: "issue", issuance_id }
//   → the DATABASE renders the canonical document from the authoritative saved output of the issuance, this function
//     stores exactly those bytes (private bucket, no overwrite) and the database seals its own hash of them. The
//     response carries the sealed document for the caller to save.
// POST application/json { action: "verify", issuance_id }
//   → intact | substituted | not_canonical | missing | not_found, and official = (intact): the ONLY route that may
//     answer official, because it downloads the stored bytes and re-hashes them (workspace access required).
// No request may carry document bytes or a hash: non-JSON bodies, extra fields and any other action are refused.
// The user id comes from the verified JWT only.

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
// @deno-types="../_shared/reportingPackSeal.d.mts"
import { issueOfficialPack, parseSealRequest, verifyOfficialPack, type SealDeps } from "../_shared/reportingPackSeal.mjs";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};
const json = (status: number, body: unknown) =>
  new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } });

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  if (req.method !== "POST") return json(405, { outcome: "invalid_request" });
  // Official bytes are generated by the server: an upload is refused before anything else is read.
  if (!(req.headers.get("content-type") ?? "").startsWith("application/json")) return json(400, { outcome: "invalid_request" });
  try {
    const url = Deno.env.get("SUPABASE_URL")!;
    const caller = createClient(url, Deno.env.get("SUPABASE_ANON_KEY")!, {
      global: { headers: { Authorization: req.headers.get("Authorization") ?? "" } },
    });
    const { data: { user }, error: authErr } = await caller.auth.getUser();
    if (authErr || !user) return json(401, { outcome: "unauthenticated" });

    const admin = createClient(url, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!, { auth: { autoRefreshToken: false, persistSession: false } });
    const bucket = admin.storage.from("reporting-packs");
    const deps: SealDeps = {
      rpc: (fn, args) => admin.rpc(fn, args),
      put: async (path, bytes, contentType) => ({ error: (await bucket.upload(path, bytes, { contentType, upsert: false })).error }),
      remove: (path) => bucket.remove([path]),
      get: async (path) => {
        const { data, error } = await bucket.download(path);
        return error || !data ? null : new Uint8Array(await data.arrayBuffer());
      },
      sha256Hex: async (bytes) => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", bytes))).map((b) => b.toString(16).padStart(2, "0")).join(""),
    };

    const request = parseSealRequest(req.headers.get("content-type"), await req.json().catch(() => null));
    if (!request) return json(400, { outcome: "invalid_request" });
    if (request.action === "issue") {
      const r = await issueOfficialPack(deps, { userId: user.id, issuanceId: request.issuanceId });
      return json(r.httpStatus, r.body);
    }
    // The only route that may answer official: the stored bytes are downloaded and re-hashed (workspace access required).
    const v = await verifyOfficialPack(deps, user.id, request.issuanceId);
    return json(v.outcome === "not_found" ? 404 : 200, v);
  } catch (err) {
    console.error("seal-reporting-pack error:", (err as Error)?.message ?? "unknown");
    return json(500, { outcome: "seal_failed" });
  }
});
