-- ============================================================
-- Migration: 20260707200000 — Iron Dome Nuclear Design (5 Core Gaps)
-- Date: 2026-07-07
--
-- IMPLEMENTS:
--   1. period_closing_balances  — multi-period persistence engine
--      Enables SCF (working capital Δ), SOCIE (equity roll-forward),
--      comparative columns, true deferred tax movement (OD-14 resolved),
--      loss carry-forward accumulation, W&T WDV continuity.
--
--   2. adjusting_journal_entries + aje_lines
--      Double-entry AJE layer between raw TB and certified statements.
--      Auto-generated by kinga-tax-engine for CIT gap (Module E) and
--      DTL/DTA (Module D). CPA can also post manual AJEs.
--
--   3. statement_sign_offs
--      3-tier CPA sign-off chain: Preparer → Reviewer → Approver.
--      When Approver locks the period: fiscal_periods.status → 'locked';
--      new trial balance uploads for that company+year are BLOCKED.
--
-- PURELY ADDITIVE. No data destroyed.
-- ============================================================

BEGIN;

-- ════════════════════════════════════════════════════════════
-- 1. PERIOD CLOSING BALANCES
-- The foundational multi-period engine.
-- One row per company per year-end.  Next year's computation
-- reads THIS year's row as opening balances.
-- ════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.period_closing_balances (
  id                          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id                  UUID        NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  period_year                 INTEGER     NOT NULL,
  period_month                INTEGER     NOT NULL DEFAULT 12,   -- 12 = calendar year-end

  -- ── SFP SNAPSHOT (from canonical statements, positive amounts) ────────
  current_assets_tzs            NUMERIC   NOT NULL DEFAULT 0,
  non_current_assets_tzs        NUMERIC   NOT NULL DEFAULT 0,
  current_liabilities_tzs       NUMERIC   NOT NULL DEFAULT 0,
  non_current_liabilities_tzs   NUMERIC   NOT NULL DEFAULT 0,
  equity_tzs                    NUMERIC   NOT NULL DEFAULT 0,
  cash_balance_tzs              NUMERIC   NOT NULL DEFAULT 0,   -- detected cash + bank accounts

  -- ── EQUITY COMPONENTS (for SOCIE roll-forward) ───────────────────────
  share_capital_tzs             NUMERIC   NOT NULL DEFAULT 0,
  retained_earnings_tzs         NUMERIC   NOT NULL DEFAULT 0,
  other_reserves_tzs            NUMERIC   NOT NULL DEFAULT 0,

  -- ── DEFERRED TAX POSITION (for Module D true movement) ───────────────
  closing_dtl_tzs               NUMERIC   NOT NULL DEFAULT 0,
  closing_dta_tzs               NUMERIC   NOT NULL DEFAULT 0,
  net_deferred_tax_position_tzs NUMERIC   NOT NULL DEFAULT 0,   -- +ve = net DTL

  -- ── LOSS CARRY-FORWARD (for ITA s.19(2) multi-year accumulation) ─────
  cumulative_unrelieved_loss_tzs NUMERIC  NOT NULL DEFAULT 0,

  -- ── W&T WRITTEN-DOWN VALUES by ITA class (for capital_allowances continuity) ─
  wdv_class1_tzs    NUMERIC NOT NULL DEFAULT 0,   -- Class 1: 37.5% RB
  wdv_class2_tzs    NUMERIC NOT NULL DEFAULT 0,   -- Class 2: 25% RB
  wdv_class3_tzs    NUMERIC NOT NULL DEFAULT 0,   -- Class 3: 12.5% RB
  wdv_class5_tzs    NUMERIC NOT NULL DEFAULT 0,   -- Class 5: 20% SL (ag bldgs)
  wdv_class6_tzs    NUMERIC NOT NULL DEFAULT 0,   -- Class 6: 5% SL (commercial)
  wdv_class7_tzs    NUMERIC NOT NULL DEFAULT 0,   -- Class 7: intangible (1/useful life)
  wdv_class8_tzs    NUMERIC NOT NULL DEFAULT 0,   -- Class 8: 100% immediate (ag plant)

  -- ── PROVENANCE ────────────────────────────────────────────────────────
  upload_id         UUID     REFERENCES public.trial_balance_uploads(id) ON DELETE SET NULL,
  engine_version    TEXT,
  computed_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (company_id, period_year, period_month)
);

CREATE INDEX IF NOT EXISTS idx_pcb_company_period
  ON public.period_closing_balances (company_id, period_year DESC, period_month DESC);

ALTER TABLE public.period_closing_balances ENABLE ROW LEVEL SECURITY;

CREATE POLICY "pcb_select" ON public.period_closing_balances FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM public.firm_members fm
    WHERE fm.user_id = auth.uid() AND fm.company_id = period_closing_balances.company_id
  ));

CREATE POLICY "pcb_insert" ON public.period_closing_balances FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.firm_members fm
    WHERE fm.user_id = auth.uid() AND fm.company_id = period_closing_balances.company_id
  ));

CREATE POLICY "pcb_update" ON public.period_closing_balances FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM public.firm_members fm
    WHERE fm.user_id = auth.uid() AND fm.company_id = period_closing_balances.company_id
  ));

GRANT SELECT, INSERT, UPDATE ON public.period_closing_balances TO authenticated;
GRANT ALL ON public.period_closing_balances TO service_role;

COMMENT ON TABLE public.period_closing_balances IS
  'Closing SFP snapshot + equity components + deferred tax position + '
  'W&T WDV pools per company per period. '
  'Next year reads this as opening balances, enabling: '
  '(1) SCF working capital movements (IFRS for SMEs s.7), '
  '(2) SOCIE equity roll-forward (s.6), '
  '(3) Module D true deferred tax movement (OD-14 resolved), '
  '(4) Loss carry-forward accumulation (ITA s.19), '
  '(5) Capital allowances WDV continuity (ITA s.17).';


-- ════════════════════════════════════════════════════════════
-- 2. ADJUSTING JOURNAL ENTRIES (MASTER)
-- Formal AJE layer between raw client TB and certified statements.
-- auto_generated=true when written by kinga-tax-engine.
-- ════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.adjusting_journal_entries (
  id            UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id    UUID    NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  upload_id     UUID    NOT NULL REFERENCES public.trial_balance_uploads(id) ON DELETE CASCADE,
  period_year   INTEGER NOT NULL,

  aje_number    TEXT    NOT NULL,
  -- AJE-001, AJE-002 (auto) or AJE-M001, AJE-M002 (manual CPA)
  description   TEXT    NOT NULL,

  aje_type      TEXT    NOT NULL
    CHECK (aje_type IN ('accrual','reclassification','tax','depreciation',
                        'correction','deferred_tax','loss_provision')),
  -- tax = CIT gap AJE from Module E
  -- deferred_tax = DTL/DTA AJE from Module D
  -- accrual/depreciation/correction = manual CPA entries

  source        TEXT    NOT NULL DEFAULT 'cpa_manual'
    CHECK (source IN ('kinga_auto','cpa_manual','module_d','module_e')),

  auto_generated BOOLEAN NOT NULL DEFAULT false,

  -- 2-step approval: created → approved
  created_by    UUID    NOT NULL REFERENCES auth.users(id),
  approved_by   UUID    REFERENCES auth.users(id),
  approved_at   TIMESTAMPTZ,
  status        TEXT    NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft','approved','reversed')),

  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (company_id, upload_id, aje_number)
);

CREATE INDEX IF NOT EXISTS idx_aje_company_period
  ON public.adjusting_journal_entries (company_id, period_year, upload_id);
CREATE INDEX IF NOT EXISTS idx_aje_status
  ON public.adjusting_journal_entries (status);

ALTER TABLE public.adjusting_journal_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "aje_select" ON public.adjusting_journal_entries FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM public.firm_members fm
    WHERE fm.user_id = auth.uid() AND fm.company_id = adjusting_journal_entries.company_id
  ));

CREATE POLICY "aje_insert" ON public.adjusting_journal_entries FOR INSERT
  WITH CHECK (
    auth.uid() = created_by AND
    EXISTS (
      SELECT 1 FROM public.firm_members fm
      WHERE fm.user_id = auth.uid() AND fm.company_id = adjusting_journal_entries.company_id
    )
  );

CREATE POLICY "aje_update" ON public.adjusting_journal_entries FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM public.firm_members fm
    WHERE fm.user_id = auth.uid() AND fm.company_id = adjusting_journal_entries.company_id
  ));

GRANT SELECT, INSERT, UPDATE ON public.adjusting_journal_entries TO authenticated;
GRANT ALL ON public.adjusting_journal_entries TO service_role;

COMMENT ON TABLE public.adjusting_journal_entries IS
  'AJE master table. Each AJE has Dr/Cr lines in aje_lines. '
  'auto_generated=true + source=module_e: Dr Tax Expense Cr Tax Payable (CIT gap). '
  'auto_generated=true + source=module_d: Dr/Cr Deferred Tax Liability/Asset. '
  'Adjusted TB = Raw TB + all approved AJEs.';


-- ════════════════════════════════════════════════════════════
-- 3. AJE LINES (DOUBLE-ENTRY DETAIL)
-- ════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.aje_lines (
  id            UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  aje_id        UUID    NOT NULL REFERENCES public.adjusting_journal_entries(id) ON DELETE CASCADE,
  line_number   INTEGER NOT NULL,
  account_code  TEXT    NOT NULL,
  account_name  TEXT    NOT NULL,
  classification TEXT   NOT NULL,
  -- Maps to canonical section: current_liabilities | taxes | non_current_liabilities | non_current_assets
  debit_tzs     NUMERIC NOT NULL DEFAULT 0,
  credit_tzs    NUMERIC NOT NULL DEFAULT 0,
  narration     TEXT,

  -- Double-entry integrity: a line is either debit OR credit, not both
  CHECK (NOT (debit_tzs > 0 AND credit_tzs > 0)),
  CHECK (debit_tzs >= 0 AND credit_tzs >= 0),

  UNIQUE (aje_id, line_number)
);

CREATE INDEX IF NOT EXISTS idx_aje_lines_aje
  ON public.aje_lines (aje_id);

ALTER TABLE public.aje_lines ENABLE ROW LEVEL SECURITY;

CREATE POLICY "aje_lines_select" ON public.aje_lines FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM public.adjusting_journal_entries a
    JOIN public.firm_members fm ON fm.company_id = a.company_id
    WHERE a.id = aje_lines.aje_id AND fm.user_id = auth.uid()
  ));

CREATE POLICY "aje_lines_insert" ON public.aje_lines FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.adjusting_journal_entries a
    JOIN public.firm_members fm ON fm.company_id = a.company_id
    WHERE a.id = aje_lines.aje_id AND fm.user_id = auth.uid()
  ));

GRANT SELECT, INSERT ON public.aje_lines TO authenticated;
GRANT ALL ON public.aje_lines TO service_role;

COMMENT ON TABLE public.aje_lines IS
  'Double-entry lines per AJE. Dr + Cr must balance across all lines for an aje_id. '
  'classification maps to canonical statement sections for adjusted-TB reconstruction. '
  'Adjusted TB = Raw TB balances + net effect of all approved aje_lines.';


-- ════════════════════════════════════════════════════════════
-- 4. STATEMENT SIGN-OFFS + 3-TIER CPA LOCK
-- ════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.statement_sign_offs (
  id                  UUID  PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id          UUID  NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  period_year         INTEGER NOT NULL,
  upload_id           UUID  NOT NULL REFERENCES public.trial_balance_uploads(id),

  -- SHA-256 of canonical JSON of all 4 statements (set when approver locks).
  -- Provides non-repudiation: any post-sign change is detectable.
  statements_hash     TEXT,

  -- ── TIER 1: PREPARER ─────────────────────────────────────────────────
  preparer_id         UUID  REFERENCES auth.users(id),
  preparer_signed_at  TIMESTAMPTZ,
  preparer_note       TEXT,

  -- ── TIER 2: REVIEWER ─────────────────────────────────────────────────
  reviewer_id         UUID  REFERENCES auth.users(id),
  reviewer_signed_at  TIMESTAMPTZ,
  reviewer_note       TEXT,

  -- ── TIER 3: APPROVER (partner / director — final authority) ──────────
  approver_id         UUID  REFERENCES auth.users(id),
  approver_signed_at  TIMESTAMPTZ,
  approver_note       TEXT,

  -- Status flow: draft → preparer_signed → reviewer_signed → approved → locked
  status              TEXT  NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft','preparer_signed','reviewer_signed','approved','locked')),

  -- Period is IMMUTABLE once locked_at IS NOT NULL.
  -- New TB uploads for this company+year are BLOCKED (trigger below).
  locked_at           TIMESTAMPTZ,
  locked_by           UUID  REFERENCES auth.users(id),

  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (company_id, period_year)
);

CREATE INDEX IF NOT EXISTS idx_sso_company_period
  ON public.statement_sign_offs (company_id, period_year DESC);
CREATE INDEX IF NOT EXISTS idx_sso_status
  ON public.statement_sign_offs (status);

ALTER TABLE public.statement_sign_offs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "sso_select" ON public.statement_sign_offs FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM public.firm_members fm
    WHERE fm.user_id = auth.uid() AND fm.company_id = statement_sign_offs.company_id
  ));

CREATE POLICY "sso_insert" ON public.statement_sign_offs FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.firm_members fm
    WHERE fm.user_id = auth.uid() AND fm.company_id = statement_sign_offs.company_id
  ));

-- RLS UPDATE: only permitted while not yet locked (locked_at IS NULL).
-- Once locked, even authorized users cannot update — DB enforces immutability.
CREATE POLICY "sso_update" ON public.statement_sign_offs FOR UPDATE
  USING (
    locked_at IS NULL AND
    EXISTS (
      SELECT 1 FROM public.firm_members fm
      WHERE fm.user_id = auth.uid() AND fm.company_id = statement_sign_offs.company_id
    )
  );

GRANT SELECT, INSERT, UPDATE ON public.statement_sign_offs TO authenticated;
GRANT ALL ON public.statement_sign_offs TO service_role;

COMMENT ON TABLE public.statement_sign_offs IS
  '3-tier CPA sign-off chain (Preparer → Reviewer → Approver) per company per period. '
  'When locked_at IS NOT NULL: fiscal_periods.status is set to "locked" by trigger, '
  'and new trial_balance_uploads for this company+year are blocked by trigger. '
  'statements_hash (SHA-256) provides non-repudiation of the signed statement set.';


-- ════════════════════════════════════════════════════════════
-- 5. PERIOD LOCK CASCADE TRIGGER
-- When statement_sign_offs.locked_at is set, cascade to
-- fiscal_periods.status = 'locked'.
-- ════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.cascade_period_lock()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  -- LOCK event: locked_at newly populated
  IF NEW.locked_at IS NOT NULL AND (OLD.locked_at IS NULL) THEN
    -- Cascade to fiscal_periods
    UPDATE public.fiscal_periods
    SET    status     = 'locked',
           updated_at = now()
    WHERE  company_id = NEW.company_id
      AND  EXTRACT(YEAR FROM fiscal_year_end)::INTEGER = NEW.period_year;

    -- Enforce status on this row
    NEW.status := 'locked';
  END IF;

  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_cascade_period_lock ON public.statement_sign_offs;
CREATE TRIGGER trg_cascade_period_lock
  BEFORE UPDATE ON public.statement_sign_offs
  FOR EACH ROW EXECUTE FUNCTION public.cascade_period_lock();


-- ════════════════════════════════════════════════════════════
-- 6. UPLOAD GUARD — BLOCK UPLOADS FOR LOCKED PERIODS
-- Prevents new trial balance uploads for a company+year that
-- has been locked via statement_sign_offs.locked_at.
-- The lock is enforced at the DB layer, not just application code.
-- ════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.guard_upload_on_locked_period()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  lock_ts     TIMESTAMPTZ;
  upload_year INTEGER;
BEGIN
  -- Derive upload year from the uploaded_at timestamp (or now if null)
  upload_year := EXTRACT(YEAR FROM COALESCE(NEW.uploaded_at::TIMESTAMPTZ, now()))::INTEGER;

  SELECT sso.locked_at INTO lock_ts
  FROM   public.statement_sign_offs sso
  WHERE  sso.company_id  = NEW.company_id
    AND  sso.period_year = upload_year
    AND  sso.locked_at IS NOT NULL
  LIMIT  1;

  IF FOUND AND lock_ts IS NOT NULL THEN
    RAISE EXCEPTION
      'Upload blocked: FY% for this company is LOCKED (signed off on %). '
      'Unlock the approved statements before re-processing.',
      upload_year, lock_ts
      USING ERRCODE = 'P0001';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_guard_upload_locked ON public.trial_balance_uploads;
CREATE TRIGGER trg_guard_upload_locked
  BEFORE INSERT ON public.trial_balance_uploads
  FOR EACH ROW EXECUTE FUNCTION public.guard_upload_on_locked_period();


-- ════════════════════════════════════════════════════════════
-- 7. HELPER VIEW — AJE BALANCE CHECK
-- Verifies that each AJE's debit total = credit total.
-- A non-balancing AJE signals a data integrity problem.
-- ════════════════════════════════════════════════════════════

CREATE OR REPLACE VIEW public.v_aje_balance_check AS
SELECT
  a.id                           AS aje_id,
  a.company_id,
  a.period_year,
  a.aje_number,
  a.description,
  a.status,
  SUM(l.debit_tzs)               AS total_debit_tzs,
  SUM(l.credit_tzs)              AS total_credit_tzs,
  SUM(l.debit_tzs) - SUM(l.credit_tzs) AS imbalance_tzs,
  CASE WHEN ABS(SUM(l.debit_tzs) - SUM(l.credit_tzs)) < 1
       THEN true ELSE false END  AS balanced
FROM public.adjusting_journal_entries a
JOIN public.aje_lines l ON l.aje_id = a.id
GROUP BY a.id, a.company_id, a.period_year, a.aje_number, a.description, a.status;

COMMENT ON VIEW public.v_aje_balance_check IS
  'Verifies debit = credit for each AJE. '
  'Rows where balanced = false indicate data integrity problems.';


COMMIT;


-- ════════════════════════════════════════════════════════════
-- VERIFICATION SQL (run in Supabase SQL editor after applying)
-- ════════════════════════════════════════════════════════════

-- V1: All 4 new tables exist with RLS enabled
-- SELECT tablename, rowsecurity FROM pg_tables
-- WHERE schemaname = 'public'
--   AND tablename IN ('period_closing_balances','adjusting_journal_entries','aje_lines','statement_sign_offs')
-- ORDER BY tablename;
-- Expected: 4 rows, all rowsecurity = true

-- V2: All 4 new indexes exist
-- SELECT indexname FROM pg_indexes
-- WHERE schemaname = 'public'
--   AND tablename IN ('period_closing_balances','adjusting_journal_entries','aje_lines','statement_sign_offs');

-- V3: Triggers exist
-- SELECT trigger_name, event_object_table FROM information_schema.triggers
-- WHERE trigger_schema = 'public'
--   AND trigger_name IN ('trg_cascade_period_lock','trg_guard_upload_locked');
-- Expected: 2 rows

-- V4: AJE balance view
-- SELECT * FROM public.v_aje_balance_check LIMIT 1;
