-- ════════════════════════════════════════════════════════════════════════════
-- Ω∞ PHASE 0A — LOVABLE LIVE EXECUTION MARKER (COMMENT-ONLY)
--
-- This file contains ZERO executable SQL. It intentionally performs no DDL.
--
-- WHAT THIS VERSION IDENTITY IS:
--   20260902052434 is the migration identity Lovable's tooling generated and
--   recorded as applied on the live AXIOM/SAFF ERP project
--   (bvyivmmfjejbmqoydezk). The executable SQL that ran under this identity
--   was verified — by direct comment-stripped diff against the reviewed
--   source — to be byte-for-byte identical to the canonical Phase 0A
--   migration's executable content (268/268 non-comment lines matched
--   exactly; only comment/header formatting differed). That historical
--   execution event is not altered, disputed, or rewritten by this file.
--
-- WHY THIS FILE IS NOW INERT:
--   Canonical repository replay authority remains:
--
--     supabase/migrations/20260901120000_engine_execution_foundation.sql
--     Pre-live (hardened) SHA-256:
--     acaaf0a49741d9a038682bd0d507088598e728c93b83888816a46e9bcd5b3b29
--
--   Because 20260901120000 sorts before 20260902052434 by timestamp, leaving
--   both files fully executable would cause a fresh migration replay (a
--   clean clone, CI, or disaster-recovery rebuild) to run 20260901120000
--   first, then fail on this file's duplicate CREATE TABLE/CREATE FUNCTION
--   statements. Model B (the same reconciliation model already used for the
--   Phase 2A migration identity) resolves this the same way: the reviewed,
--   hash-certified, meaningfully-named file stays canonical; this generated
--   capture becomes a permanent, inert historical marker.
--
-- LIVE ACL DEFECT DISCOVERED AT THIS EXECUTION:
--   The DDL that ran here (matching 20260901120000 exactly) left
--   `authenticated` with full arwdDxtm privileges on both engine_runs and
--   idempotency_keys, because the canonical migration's REVOKE ALL
--   statement named only PUBLIC and anon — never authenticated — before
--   granting it SELECT. Since this project's pg_default_acl already grants
--   authenticated broad privileges at CREATE TABLE time
--   (DEFECT-DEFAULT-ACL-AUTHENTICATED-001, project-wide, still open), the
--   subsequent GRANT SELECT only added to that inherited grant rather than
--   replacing it. This is a real defect in the canonical migration's own
--   text, not a platform quirk. It is corrected by a separate, additive
--   migration — see 20260902110000_phase0a_acl_hardening.sql — not by
--   editing this marker or the canonical file's historical record.
--
-- DO NOT DELETE THIS MARKER. It preserves the live-history provenance of
-- what actually executed against the real project, independent of what the
-- repository's canonical replay file now contains.
--
-- See MIGRATION_RECONCILIATION.md for the complete reconciliation record.
-- ════════════════════════════════════════════════════════════════════════════
