-- ════════════════════════════════════════════════════════════════════════════
-- Ω∞ PHASE 2A MIGRATION RECONCILIATION — AUDIT MARKER (COMMENT-ONLY)
--
-- This file contains ZERO executable SQL. It intentionally performs no DDL.
--
-- WHAT THIS VERSION IDENTITY IS:
--   20260818040518 is the migration identity that Lovable's tooling
--   generated and recorded as applied on the live AXIOM/SAFF ERP project
--   (bvyivmmfjejbmqoydezk) on 2026-08-18. Equivalent Phase 2A professional
--   account-review-authority SQL (account_review_batches,
--   account_review_decisions, account_review_decisions_seq,
--   resolve_account_review_batch, get_effective_non_reporting_status, RLS,
--   immutability trigger) historically EXECUTED against that project under
--   this exact version identity. That historical execution event is not
--   altered, disputed, or rewritten by this file — Postgres already ran it,
--   and the live migration-history tracking row for this version already
--   records that fact independently of what this repository file now says.
--
-- WHY THIS FILE IS NOW INERT:
--   The migration actually authored, reviewed, and security-certified across
--   this project's Phase 2A design gates (identity/concurrency model,
--   SECURITY DEFINER search_path safety, RLS, drift guard, idempotency) is:
--
--     supabase/migrations/20260816120000_account_review_authority.sql
--     SHA-256: c588462dfa82718488fc6ea02236d6efcc40f83c94f87e60bad1426b1c6ec8d5
--
--   Diffing the two files proved their executable SQL is identical — the
--   only difference was a trailing rollback-comment block and a missing
--   final newline in this file, both non-executing. Because
--   20260816120000 sorts BEFORE 20260818040518 by timestamp, leaving both
--   files fully executable would cause a fresh migration replay (a clean
--   clone, CI, or disaster-recovery rebuild) to run 20260816120000 first
--   (creating every Phase 2A object), then fail on 20260818040518's
--   duplicate CREATE TABLE / CREATE FUNCTION statements.
--
--   Model B (of five reconciliation models evaluated) resolves this by
--   keeping 20260816120000 — the reviewed, hash-certified, meaningfully
--   named source — as the sole executable creation authority going forward,
--   and converting this file to the inert marker you are reading now.
--
-- WHAT THIS DOES NOT DO:
--   This repository-level change does not itself update the LIVE project's
--   migration-history tracking table. bvyivmmfjejbmqoydezk still needs a
--   separate, metadata-only repair (`supabase migration repair --status
--   applied 20260816120000` — per Supabase's own documentation, this
--   updates the history record only and does not execute any migration
--   SQL) so that a future `supabase db push` against that same project does
--   not attempt to run 20260816120000 either. That live repair has NOT
--   been performed as of this commit — this environment has no
--   authenticated access to that project. See MIGRATION_RECONCILIATION.md
--   for the full forensic record and current status.
--
-- ORIGINAL EXECUTABLE CONTENT:
--   The original, fully executable form of this file (SHA-256:
--   84bc842bb52701679d3fa196fe5ba2532a3934974064004e9271d8d1aa02c774) is
--   permanently retrievable from Git history — see
--   supabase/migrations/20260818040518_97684879-c329-4fe6-b411-71faf2452152.sql
--   at commit 06c4b3d593024da2ac1d2e07f864acc1ee2803b1 (or any ancestor of
--   this commit).
--
-- See MIGRATION_RECONCILIATION.md for the complete reconciliation record.
-- ════════════════════════════════════════════════════════════════════════════
